wp-cli/wp-cli

- templates/install-wp-tests.sh
Hi!
Another simple tweak to help folks using Windows: set a directory for `WP_CORE_DIR`, just as `WP_TESTS_DIR` is.
Without this I couldn't get phpunit tests to run because the `require '/tmp/wordpress/...'` bits were not making my install too happy :-Þ
Side note: I'm preparing a WordCamp speech about plugin unit testing and there will be things specifically for people on Windows. When I'm done, I'll write a blog post about it and will let you know, this would be probably helpful for other windowsians as well :)
> Use env variable for WP_CORE_DIR if set

- php/commands/cli.php
This will give us more visibility into what might be broken.
Also explicitly marks some methods as public.
> For `cli check-update`, report HTTP code on error

- features/upgradables.feature
WordPress.org API is giving us junk results for `per_page=1`
See https://meta.trac.wordpress.org/ticket/866
> Fix builds by increasing the # of items per page

- templates/install-package-tests.sh
- templates/install-wp-tests.sh
This also removes the wget-call from install-package-tests as curl is
already a requirement.
> Support downloading via curl or wget in install-wp-tests.sh

- features/search-replace.feature
- php/commands/search-replace.php
with issue https://github.com/wp-cli/wp-cli/pull/1304 released in wpcli 0.17 search-replace only applies to tables registered on wpdb
the problem is that plugins can create and use different tables non registered on wpdb, so it should be possible to run the command on all tables without explicitly listing them, with some optional flag like `--all-tables`
makes sense?
the optional behaviour could be:
- all the tables with the prefix in use (like pre-0.17)
- all the tables in the db
preferences? both with different flags?
> Use `--all-tables` search-replace flag to do all tables in the db

- php/commands/import.php
Proper use is to provide the class name as a string
From #1645
> Don't instantiate the `Import_Command` class when registering

- features/scaffold.feature
- php/commands/scaffold.php
- templates/post_type.mustache
Right now no `menu_icon` is set during the scaffolding of `post_types`. 
I implemented a new optional argument for `$ wp scaffold post-type` to give developers the option to add an icon from the official [dashicons](https://developer.wordpress.org/resource/dashicons/) in a very easy way. 
I also implemented a default value that is equal to the standard value so the icon argument is optional. But by adding the extra line in the generated `post_type` code the developer is hinted to the existence of this easily customisable icon. 
Lastly I added some behat tests to test with and without the argument.
The command can be used like so:
```
$ wp scaffold post-type zombie --icon="cloud"
```
This will put the [cloud](https://developer.wordpress.org/resource/dashicons/#cloud) dashicon in front of …
> Add icon argument to scaffold post-type command

- features/command.feature
- php/class-wp-cli.php
When non-existent class given to `add_command()`.
> Provide human-friendly error if invalid class is specified for a command

- php/commands/export.php
It's helpful in many cases to have these files automatically ordered correctly. Without padded zeros, they will be ordered something like:
```
*.1.xml
*.10.xml
*.2.xml
*.3.xml
...
```
> Pad export filenames with zeros

- php/commands/cron.php
In WordPress 4.0, the value of the `sslverify` argument when spawning cron was changed from `true` to `false`. This means that currently, the `wp cron test` command can return a false negative for a site which has an untrusted SSL certificate.
Ref: https://core.trac.wordpress.org/changeset/28781
This change contains the correct version comparison.
> When testing WP-Cron, correctly set the `sslverify` argument

- php/utils.php
See #1434
When we download the `non-phar` version of `wp-cli` we have to run `composer install` to install it's dependencies.
If we try to run `wp` when we haven't run `composer install`, we get this error:
`Internal error: Can't find Composer autoloader.`
which doesn't help. Instead I added:
`Try running: composer install\n`
Giving:
`Internal error: Can't find Composer autoloader.\nTry running: composer install\n`
Which makes more sense.
> Elaborated error message

- features/core.feature
WPorg started serving WordPress downloads with a historic filemtime,
meaning our cache gets cleared as soon as we try to use it.
Fixes #1681
> Ensure our fake cached WordPress download is considered fresh

- php/export/class-wp-export-query.php
> If a term is missing a parent, be more descriptive as to where it's missing

- php/commands/import.php
`create_author_mapping_file()` uses WP_Error to report that an author
mapping file needs to be updated. However, when importing a directory of
WXR files, only using `::warning()` means the second file will use the
author mapping file of the first, which should've been edited.
Fixes #1682
> Throw hard error if importing a file returns WP_Error

- php/commands/core.php
The multisite install and convert code does not include:
`define( 'WP_ALLOW_MULTISITE', true );`
If this isn't present, the "Network Settings" and "Network Setup"
menu items are not available in the network admin.
> Added allow multisite constant to multisite install and convert.

- features/core.feature
- php/class-wp-cli.php
When using the --url global option (or during core install), URLs with an https scheme were being treated as http.
The WP is_ssl() function checks for the $_SERVER['HTTPS'] flag or port 443 being set. This change allows standard and non-standard ports to be used so is_ssl() will return true when the supplied URL has an https scheme. This helps with the wp_guess_url() call during wp_install() so the proper URL is used when populating the database.
> Honor https scheme on --url option

- features/search-replace.feature
- php/commands/search-replace.php
- php/utils.php
Adds a new flag, `--all-tables`, to the `search-replace` command. This allows the command to be run against all tables in the database, rather than strictly WordPress tables or even prefixed tables. Because of the possibility for destruction, the flag also prompts the user to confirm the action.
There are also some Behat tests to cover the functionality.
> Add `--all-tables` flag to `search-replace` command

- php/commands/import.php
```
PHP Strict Standards:  Only variables should be passed by reference in
/home/vagrant/.wp-cli/php/commands/import.php on line 358
```
> Fix PHP strict standards in importer

- features/post-meta.feature
- php/WP_CLI/CommandWithMeta.php
check for unchanged value, rather than failing with error
> apply option unchanged logic to post meta

- php/commands/option.php
If a plugin defines a sanitize_option filter, the equality check in 'wp
option update' may indicate that the the new option value is different
from the original when in fact it is not.  The result is a spurious
error message on an unchanged option, instead of succeeding with 'Value
passed for 'foo' option is unchanged'.
I see this with the Yoast SEO plugin which defines this filter.
I would write a test but it seems like a hard thing to test easily.
> sanitize option before checking value equality

- composer.json
- utils/make-phar.php
`rhumsaa/array_column` isn't supported by the author, and he recommends switching to `ramsey/array_column` (same author, different Composer username).
See #1724.
> Switch from rhumsaa/array_column to ramsey/array_column

- features/post-term.feature
- features/user-term.feature
- php/WP_CLI/CommandWithTerms.php
Should I add support to `--ids` as well?
> Add `--format=ids` to `wp post term list`

- features/scaffold.feature
- php/commands/scaffold.php
Includes new functional test for `wp scaffold _s --activate`; I’m planning on also creating a parallel issue for that command, though I’m not sure what the option should be called, because the nomenclature seems different (`wp theme enable` vs `wp plugin activate`).
See #1709
> Add scaffold plugin --activate-network option

- templates/child_theme_functions.mustache
The generated code was returning an error of an undefined function, and without enqueueing the child theme in its functions.php file, style changes in the child theme's styles.css file were not reflected on the site.
Completes #1706
> Correctly enqueue parent and child themes in functions.php

- php/Spyc.php
- php/WP_CLI/CommandWithDBObject.php
- php/WP_CLI/CommandWithTranslation.php
- php/WP_CLI/CommandWithUpgrade.php
- php/class-wp-cli.php
- php/commands/cache.php
- php/commands/cli.php
- php/commands/comment.php
- php/commands/core.php
- php/commands/cron.php
- php/commands/db.php
- php/commands/media.php
- php/commands/menu.php
- php/commands/option.php
- php/commands/plugin.php
- php/commands/post.php
- php/commands/rewrite.php
- php/commands/role.php
- php/commands/scaffold.php
- php/commands/search-replace.php
- php/commands/shell.php
- php/commands/site.php
- php/commands/term.php
- php/commands/theme.php
- php/commands/transient.php
- php/commands/user.php
- php/commands/widget.php
- php/export/class-wp-export-query.php
- php/utils.php
Function to check if a command flag is set and has the expected value.
This should work as addressed by @JPry in https://github.com/wp-cli/wp-cli/issues/1696#issuecomment-79081557 and fixed by him for the `wp search-replace` command in #1697.
Should I replace the following uses in this PR or do it in another, if this is merged?
```php
$flag = isset( $args['flag'] ) && $args['flag'];
// by
$flag = \WP_CLI::check_flag( $args, 'flag' );
// and
$flag = isset( $args['flag'] ) && $args['flag'] == 'yes';
// by
$flag = \WP_CLI::check_flag( $args, 'flag', 'yes' );
// and
$flag = isset( $args['flag'] ) && $args['flag'] != 0;
// by
$flag = ! \WP_CLI::check_flag( $args, 'flag', 0 );
```
> Add `\WP_CLI\Utils\ get_flag_value` function

- features/scaffold.feature
- features/theme.feature
- php/commands/theme.php
If a child theme is dependent on parent functions, WP can fatal.
Fixes #1765
> Don't permit child themes to be activated without their parent

- features/media.feature
- php/commands/media.php
This allows old thumbnails to remain around afterwards, which can be
important on many sites.
Fixes #1712
> Add `--skip-delete` flag to `wp media regenerate`

- php/commands/import.php
- php/utils-wp.php
WordPress' internal object cache can grow until all memory is consumed
because cache invalidation is disabled. On large imports, this can fatal
the import.
See #1791, #1704
> Periodically clear object cache on import

- features/plugin.feature
- php/commands/plugin.php
Adds `--uninstall` flag to `wp plugin deactivate`, and `--deactivate` flag to `wp plugin uninstall`.
Fixes #1249
> Deactivate and uninstall a plugin in one go

- php/WP_CLI/CommandWithUpgrade.php
Example:
Enabling Maintenance mode...
Downloading update from https://downloads.wordpress.org/plugin/akismet.3.0.2.zip...
Using cached file '/home/jeichorn/.wp-cli/cache/plugin/akismet-3.0.2.zip'...
Unpacking the update...
Installing the latest version...
Removing the old version of the plugin...
Plugin updated successfully.
Disabling Maintenance mode...
Success: Updated 1/1 plugins.
+---------+-------------+-------------+---------+
| name    | old_version | new_version | status  |
+---------+-------------+-------------+---------+
| akismet | 3.0.0       | 3.0.2       | Updated |
+---------+-------------+-------------+---------+
> Add a summary table to the output of (plugin|theme) update

- php/commands/media.php
We need it to continue with the operation
Fixes #1782
> Bail early if there's no `file` set

- features/theme.feature
- php/commands/theme.php
`template` is shared by parent and child themes, which means the child
theme couldn't ever be enabled
Previously #1670
> Use `stylesheet` to track enabled themes

- templates/.travis.yml
> Improve `.travis.yml` for plugin scaffolding

- php/commands/user.php
Hi.
If I run create user command like
```
$ wp user create "JohnDoe" "john.doe@example.com" --user_pass="password" --first_name="John" --last_name="Doe"
```
it throws a notice `Notice: Undefined variable: role in [path-to-wp-cli]\wp-cli\php\commands\user.php on line 309` since v0.19.
Thanks for feedback.
> Notice on creating user

- features/comment.feature
- php/commands/comment.php
Supports `--count` to start
See #671
> Simple `wp comment generate` command

- features/core.feature
- features/term.feature
- php/commands/term.php
When running `wp term generate` against a database that already has terms, the current method of generating term names results in a `WP_Error` being thrown: "A term with the name provided already exists in this taxonomy". This is due to the fact that the label is being generated using the `$i` loop iterator, which always starts from 0.
My suggested fix is to grab the max existing `term_taxonomy_id` and pad it. This should ensure unique labels in all but the weirdest situations.
> In `wp term generate`, try to generate unique term names.

- php/commands/term.php
When generating terms in a hierarchical category, `clean_term_cache()` triggers
a rebuild of the taxonomy hierarchy with every call to `wp_insert_term()`.
This is extremely slow when the taxonomy has many terms. We only need to bust
the cache once, after all terms have been generated.
See https://core.trac.wordpress.org/changeset/32498.
@danielbachhuber I tried writing a behat test for this, but I couldn't figure out how. I'd need to, say, pull up the term_id + parent of the term last created, and then pull up the taxonomy hierarchy, and then make sure that the hierarchy reflects the term/parent relationships correctly. I tried all sorts of `Then save STDOUT` regex tricks, but got stuck, so here's the PR without any tests. If you have any tips on testing, I'd love to hear them.
> Skip cache invalidation when generating terms.

- features/scaffold.feature
- php/commands/scaffold.php
If a plugin slug is provided, use that instead of the directory
basename. But, if no slug is provided, use directory basename.
See #1828
> More sensible behavior for scaffolding plugin tests with `--dir=<dir>` arg

- features/term.feature
- php/commands/term.php
It's a bit hacky, but that's alright. We can work around WP core.
See #1818
> Filter taxonomy terms by `term_id`

- features/search-replace.feature
- php/commands/search-replace.php
Hi there,
I took a stab at #1429 for my first issue :)
If you run `wp search-replace foo bar --verbose` it will log the table and column being updated (not the row). Not sure how useful this is in it's current form?
Thanks!
k
> Adds searchreplace --verbose flag

- features/search-replace.feature
- php/WP_CLI/Iterators/Query.php
- php/WP_CLI/Iterators/Table.php
- php/WP_CLI/SearchReplacer.php
- php/commands/search-replace.php
This aims to address #1600 
It's going to be remarkably slower, given instead of only acting on rows that have values needing replacement, it has to go through all rows. MySQL's REGEXP operator is quite a bit different than PHP's...
Thoughts?
> Regex support for search-replace

- features/scaffold.feature
- php/class-wp-cli.php
- php/commands/scaffold.php
For issue #1797 
Uses `WP_CLI::confirm()` so there's a `--yes` flag.
Output looks like this:
```
Warning: Scaffold will overwrite: 
/Users/kevindoole/code/htdocs/agcanada/wp-content/plugins/blah/blah.php
/Users/kevindoole/code/htdocs/agcanada/wp-content/plugins/blah/readme.txt
/Users/kevindoole/code/htdocs/agcanada/wp-content/plugins/blah/package.json
/Users/kevindoole/code/htdocs/agcanada/wp-content/plugins/blah/Gruntfile.js
Overwrite files and continue? [y/n] y
Success: Created /Users/kevindoole/code/htdocs/agcanada/wp-content/plugins/blah
Warning: Scaffold will overwrite: 
/Users/kevindoole/code/htdocs/agcanada/wp-content/plugins/blah/tests/bootstrap.php
Overwrite files and continue? [y/n] y
Success: Created test files.
```
In the first commit, it warned about overwriting files one at …
> Adds confirms to scaffold

- features/export.feature
- php/commands/export.php
- php/export/class-wp-export-query.php
Ran into this issue when sending files to WordPress.com VIP:
Over time, as more and more data is being imported from WXRs, the process slows down as each database check becomes more an more intensive. Eventually, we decided that a greater number of smaller WXR files would be necessary to keep the import process (of a rather large site) running without completely exhausting system resources.
Not wanting to throw away the content that had already been imported, we needed a way to specify a starting post ID to re-export using a lower `--max-file-size` value, hence the `--start_id` argument was born.
Props to @ryanmarkel for his assistance on this.
> Enable the export command to specify a starting post ID

- php/WP_CLI/CommandWithTranslation.php
The function was introduced in WP 4.1
Fixes #1849
> Internalize `wp_clean_update_cache()` to prevent fatals in WP 4.0

- features/help.feature
- php/WP_CLI/Runner.php
When WordPress is loaded, we may have a plugin adding commands to a
namespace
See #1795
> Only run `help` early when WordPress isn't loaded

- php/commands/cli.php
If the `wp cli update` command errors, it tells you to attempt `wp cli self-update` again, which is incorrect.
> Correct the error message text in `wp cli update`

- templates/.travis.yml
The [Travis linter](http://lint.travis-ci.org/) complains about the `notifications` syntax in the `.travis.yml` file generated by the tests scaffold. This fixes that.
> Update the Travis notification syntax in tests scaffold

- templates/install-wp-tests.sh
In 49e9a59f5c47513a1581a3f5260a70c0350c27c1, the default value was
changed to include `includes` in the path. Because this change broke
compatibility with existing use of `WP_TESTS_DIR`, and broke
scaffolding generally, we should restore the expected behavior.
Fixes #1885
See #1843, #1840
> Restore expected behavior of `WP_TESTS_DIR` environment variable

- php/commands/media.php
This is a minor issue, but seeing `Do you realy want to regenerate all images? [y/n]` annoyed me one too many times so I needed to fix it.
> Fixed the 'realy' typo that annoyed me.

- php/commands/core.php
And provide a helpful error message
See #1892
> Catch failure to extract WordPress archive file

- php/commands/rewrite.php
> Backtick `wp rewrite flush` snippet, so it gets formatted in docs

- php/commands/cli.php
This will let root update WP-CLI when it errored previously
See #1914
> Pass thru `--allow-root` in `cli update`

- php/commands/cli.php
`exec()` only _returns_ the last line, and renders the rest.
`WP_CLI\Process` is more versatile for our needs
See #1914
> Properly pass error message to `error_multi_line()` in `cli update`

- php/utils.php
```
PHP Warning:  unlink(/tmp/wp-cli-cacert.pem): No such file or directory
in phar:///home/vagrant/.wp-cli/test.phar/php/utils.php on line 28
```
Because we make a remote request against Github twice, the shutdown
function is registered (and called) twice. The file is deleted the first
time.
See #1914
> Prevent error notice in `cli update`

- php/WP_CLI/CommandWithTerms.php
```
PHP Notice:  Undefined index: format in
/home/vagrant/.wp-cli/php/WP_CLI/CommandWithTerms.php on line 80
```
> Prevent undefined notice when no `--format=<format>` is supplied

- features/post.feature
- php/commands/post.php
> Permit categories to be assigned with `wp post update`

- php/commands/import.php
With large imports, this can cause memory issues due to parsing the data
twice and keeping it loaded in memory.
Fixes #1963
> Unset things we don't need during import

- php/commands/server.php
Was getting the following error when trying to run the `server` command:
```bash
$ php wp-cli-nightly.phar server --host=0.0.0.0 --port=8888 --docroot=web/wp
Error: Parameter errors:
unknown --docroot parameter
```
This addresses that by adding the option to the `@synopsis` annotation, allowing `wp-cli` to parse it and use it as a valid option.
> Add the docroot option to the synopsis so wp-cli parses it as a valid option

- php/wp-settings-cli.php
Core sets the variable in `wp-includes/vars.php`
Fixes #1983
> Ensure `$pagenow` global is always set

- ci/prepare.sh
When using `wp cli update --nightly`, the short hash will be helpful for
keeping track of which version you're running.
See #1800
> Append git short hash to alpha versions

- features/core.feature
- php/WP_CLI/CoreUpgrader.php
- php/commands/core.php
392aba67ebb58d6a6568f4065a808807d0992903 for v0.17.2
See #1898
> WP-CLI shouldn't use cached WP partials in full upgrades (for v0.17.2)

- features/core.feature
- php/WP_CLI/CoreUpgrader.php
- php/commands/core.php
> WP-CLI shouldn't use cached WP partials in full upgrades (for v0.19.3)

- features/core.feature
- php/WP_CLI/CoreUpgrader.php
- php/commands/core.php
> WP-CLI shouldn't use cached WP partials in full upgrades (for v0.18.1)

- features/core.feature
- php/WP_CLI/CommandWithTranslation.php
See #1879.
`wp_download_language_pack()` prevents the installation of a language if the `DISALLOW_FILE_MODS` constant is truthy.
This change introduces the `\WP_CLI\CommandWithTranslation::download_language_pack()` method which mostly copies the functionality in `wp_download_language_pack()`.
Also introduces an extra test for installing an invalid language.
> Switch away from using wp_download_language_pack()

- php/commands/cli.php
`rename()` requires both the file and directory to be writeable.
Erroring earlier is more helpful to the end user.
See #1962
> Warn on cli update when directory isn't writeable

- features/cli.feature
The other `cli.feature` scenarios are fine to run each Travis build
> Deliberately flag specific scenarios dependent on Github API

- php/commands/cache.php
> Deprecate `@synopsis` for `wp cache` in favor of better docs

- php/wp-settings-cli.php
http://core.trac.wordpress.org/changeset/33748
Originally #2010
> Load WP_HTTP with require_once because core now loads in http.php

- features/scaffold.feature
- php/commands/scaffold.php
If you run `wp scaffold plugin-tests foo` and the `foo` plugin doesn't exist, you get the following not very helpful error message:
`Error: Error creating file: ~wp-content/plugins/foo/tests/bootstrap.php`
If you haven't realised you've made a typo in the plugin slug, you might waste time investigating file permission errors.
This change tests for the existence of the plugin's directory and returns a more useful error message if it doesn't exist.
> Return a more useful error message when running `wp scaffold plugin-tests` with an invalid plugin slug.

- features/theme.feature
- php/commands/theme.php
This will more clearly distinguish between a genuinely inactive theme
vs. an "inactive" theme being used as a parent theme.
Fixes #2033
> In `wp theme list`, indicate a parent theme with `status=parent`

- php/commands/menu.php
See https://github.com/wp-cli/wp-cli.github.com/pull/63
> Fix example in `wp menu item delete`

- php/commands/core.php
WordPress multisite needs extra constants in `wp-config.php`. If WP-CLI
can't add them, we should let the user know instead of failing silently.
Fixes #2040
> Warn user when `wp-config.php` isn't writable for multisite convert

- php/commands/search-replace.php
This description used to emphasize that search-replace worked on all tables.  That's not true.  If plugins create tables and don't register the tables on the $wpdb object, search-replace will ignore them in the default configuration.  This clarifies it I hope.
Hopefully also clarifies that --all-tables ignores the wpdb registry.
> Improve description of search-replace behavior

- php/commands/comment.php
... including setting a post ID
See #725
> Generic args for `wp comment create` should always be optional

- features/export.feature
- php/commands/export.php
This argument makes it easier to generate an export with all post types
_except_ those identified.
Previously #528
> Add `--post_type__not_in` argument to `wp export`

- features/rewrite.feature
- php/commands/rewrite.php
WordPress don't generate .htaccess for multisite installs:
https://github.com/WordPress/WordPress/blob/ce557062f4123d8513378cf415b4e8b612c33ccc/wp-admin/includes/misc.php#L162
> Add error message when trying to use `wp rewrite flush --hard` on a multisite install

- php/WP_CLI/Configurator.php
- tests/test-configurator.php
Resolves #1894
I may be missing something here, but it didn't seem to me that this had much to do with #1745 as it does with the way args are sorted into positional and associative - there doesn't seem to be a reason to enforce right-side data in associative args so I've just modified the regex.
> Accept associative args with no right-side data

- features/core.feature
- php/commands/core.php
This lets a custom WP-CLI command download WP to a different directory,
when loaded from the scope of an existing WP install.
Fixes #646
Previously #647
> Permit `--path` for `wp core download`, even when WP is detected

- features/rewrite.feature
- php/commands/rewrite.php
Previously https://github.com/wp-cli/wp-cli/pull/2017#issuecomment-135852742
> Pass any `rewrite flush` warnings when using `rewrite structure`

- features/db.feature
Bug in argument parser was addressed in #1904
Fixes #1188
> Update db tests to use empty `DB_CHARSET` instead of file mod hack

- php/wp-settings-cli.php
> Support APC cache with WP-CLI,  but only after warning with confirmation

- features/site.feature
- php/WP_CLI/Iterators/Table.php
- php/WP_CLI/Runner.php
- php/commands/site.php
Also uses `get_site_url()` to produce `url` in `wp site list` for
consistency with other resources
See #2070
> Deprecate `wp site url` in favor of `wp site list --field=url`

- php/commands/cap.php
- php/commands/eval.php
- php/commands/help.php
- php/commands/option.php
- php/commands/site.php
- php/commands/transient.php
- php/commands/user.php
> Deprecate `@synopsis` for `cap`, `eval`, `help`, `option`, and others

- features/config.feature
- php/WP_CLI/Runner.php
- php/wp-cli.php
`eval()`'ing `wp-config.php` and reading the value of the constant is much more durable than using regex to parse `wp-config.php`
Previously #1362
Fixes #1667
> Let eval'd `DOMAIN_CURRENT_SITE` set URL, unless `--url` is passed.

- php/commands/option.php
```
salty-wordpress ➜  wordpress-test.dev  wp option list --search="apple"
Warning: The `wp option list` command has an invalid synopsis part: The
Warning: The `wp option list` command has an invalid synopsis part:
serialization
Warning: The `wp option list` command has an invalid synopsis part:
format
Warning: The `wp option list` command has an invalid synopsis part: for
Warning: The `wp option list` command has an invalid synopsis part: the
Warning: The `wp option list` command has an invalid synopsis part:
value.
Warning: The `wp option list` command has an invalid synopsis part:
total_bytes
Warning: The `wp option list` command has an invalid synopsis part:
displays
Warning: The `wp option list` command has an invalid synopsis part: the
Warning: The `wp option list` command has an …
```
> Fix invalid synopsis part for `wp option list`

- php/commands/comment.php
From https://wordpress.slack.com/archives/cli/p1443138041000281
> Support multiple comment ids for `comment (spam|trash|approve)` et al

- features/core.feature
- php/commands/core.php
> Only run `wp core update-db --network` on active sites

- php/commands/plugin.php
- php/commands/theme.php
This is a very simple PR for aliasing the `update` command as `upgrade` for both plugins and themes.
The `core update` command [already has the same alias](https://github.com/wp-cli/wp-cli/blob/3da87744c242c81e978fffe4b12ec23097679467/php/commands/core.php#L881), and I think it makes a lot of sense to allow for either with plugins and themes as well.
1. For consistency with the core command, as well as `apt-get`
2. It would be unintuitive for it to do anything else
> Alias update as upgrade

- php/commands/core.php
> Clarify expected output for `wp core check-update`

- features/export.feature
- php/commands/export.php
This makes it easier to pass IDs returned by one command into export.
Fixes #2103
> Permit space-delimited IDs for `wp export --post__in`

- features/framework.feature
- php/WP_CLI/Runner.php
- php/wp-cli.php
- php/wp-settings-cli.php
This also lets other commands running before WordPress loads to load
WordPress on their own.
Fixes #2089
> Load WordPress with `WP_CLI\Runner::load_wordpress()`

- utils/wp-cli-updatedeb.sh
When mariadb-client is already installed on a system, installing wpcli
currently requires to remove mariadb-client because mariadb-client and
mysql-client are in conflict.
> Support MariaDB client library.

- features/upgradables.feature
Every time WordPress.org changes their algorithm, this breaks. I'd
rather not keep fixing it.
> Remove string match on upgradeable list search

- features/framework.feature
- php/WP_CLI/Runner.php
Because commands can call this method directly, we want to make sure
everything is set up as expected.
See #2089
> Check for version and wp-config.php inside of `Runner::load_wordpress()`

- php/wp-settings-cli.php
Along the lines of #2118, but for https://core.trac.wordpress.org/changeset/34928
:sparkles:
> Load the REST API in wp-settings

- templates/install-wp-tests.sh
for #2050 
Use $WP_VERSION when checkout WordPress Repository.
If $WP_VERSION is regular version number, checkout from the version tag. 
If not use trunk.
Please test!!.
> Use $WP_VERSION when checkout WordPress tests. #2050

- features/eval.feature
- php/commands/eval-file.php
- php/commands/eval.php
> `eval` or `eval-file` without WordPress via `--skip-wordpress`

- php/WP_CLI/Runner.php
Without `$blog_id` globalized, users with persistent object cache
drop-ins experience cache pollution.
```
vagrant@vip:/srv/www$ wp option get home
http://vip.local
vagrant@vip:/srv/www$ sudo service memcached restart
Restarting memcached: memcached.
vagrant@vip:/srv/www$ wp option get home
http://vip.local/fusion
vagrant@vip:/srv/www$ wp option get home --url=vip.local
http://vip.local/fusion
vagrant@vip:/srv/www$ sudo service memcached restart
Restarting memcached: memcached.
vagrant@vip:/srv/www$ wp option get home --url=vip.local
http://vip.local
```
Somewhere, there's usage of `$blog_id` in WordPress that should be
explicitly globalized, but isn't.
See https://github.com/wp-cli/wp-cli/issues/2089#issuecomment-146289129
> Globalize `$blog_id`, `$site_id`, and `$public` before loading WordPress

- php/WP_CLI/Runner.php
- php/wp-settings-cli.php
See https://core.trac.wordpress.org/changeset/34961
See #2089
> Globalize `$blog_id` as core does

- features/config.feature
- features/flags.feature
- php/WP_CLI/Loggers/Base.php
- php/WP_CLI/Loggers/Quiet.php
- php/WP_CLI/Loggers/Regular.php
- php/WP_CLI/Runner.php
- php/class-wp-cli.php
- php/config-spec.php
- php/wp-cli.php
```
salty-wordpress ➜  wordpress-test.dev  wp option get home --debug
Debug: Using default global config: /home/vagrant/.wp-cli/config.yml
(0.057s)
Debug: Using project config: /srv/www/wordpress-test.dev/wp-cli.yml
(0.061s)
Debug: Required file from config: /srv/www/wp-rest-cli/wp-rest-cli.php
(0.144s)
Debug: ABSPATH defined: /srv/www/wordpress-test.dev/ (0.145s)
Debug: Begin WordPress load (0.148s)
Debug: wp-config.php path: /srv/www/wordpress-test.dev/wp-config.php
(0.15s)
Debug: Set URL: wordpress-test.dev/ (0.152s)
Debug: Loaded WordPress (0.925s)
http://wordpress-test.dev
```
Fixes #1022
> Use `--debug` for more verbosity during WP-CLI bootstrap process

- composer.json
- php/commands/cli.php
- php/utils.php
- tests/test-utils.php
- utils/make-phar.php
Also, if `--major`, `--minor` or `--patch` is specified in a check, then
success message will parrot the supplied flag.
Fixes #1390
Previously #1547
> Update `wp cli check-update` to accommodate major releases

- features/core-checksums.feature
- features/core.feature
- php/commands/core.php
> Support for verifying checksums without loading WordPress

- php/commands/media.php
Because we're passing `$id`, and only ever using the `ID` attribute from
`$image`, we don't need to assign `$image`
> Remove unnecessary `get_post()` from `_process_regeneration()`

- php/commands/user.php
> Accommodate `wp_new_user_notification()`'s deprecated second argument

- features/core-update-db.feature
- features/core.feature
- php/commands/core.php
It can be helpful to know what version we were at, and what we updated to.
```
salty-wordpress ➜  wordpress-test.dev  wp core update-db --network
WordPress database already at latest db version 30135 on wordpress-test.dev/
WordPress database upgraded successfully from db version 33056 to 30135 on wordpress-test.dev/foo/
WordPress database upgraded successfully from db version 33056 to 30135 on wordpress-test.dev/bar/
Success: WordPress database upgraded on 3/3 sites
```
See #2171
> Provide more verbosity when updating core database schema

- php/commands/option.php
The query is run through `$wpdb->prepare()` later on
> Remove unnecessary `esc_sql()` from `wp option list --search=`

- templates/install-wp-tests.sh
While technically `trunk` is different than `nightly`, pragmatically
they're the same, and I'd like to use a built archive instead of SVN
checkout.
Fixes #1860
> Support `$WP_VERSION=trunk` or `$WP_VERSION=nightly` in WP test install

- features/rewrite.feature
- php/commands/rewrite.php
This makes `wp rewrite flush` more consistent with other commands.
> Provide human-friendly output when rewrite rules successfully flush

- features/help.feature
- php/WP_CLI/Runner.php
Permits use of `wp core config --help` when you've downloaded WordPress. 
Bug introduced in #1877
> Let `help` run early when WP is detected, but not installed

- templates/plugin-gruntfile.mustache
- templates/plugin.mustache
This PR updates the main plugin file to pass WPCS standards using the "WordPress" standard.
* Add `@package` tag
* Use `/** */` block comment
* Also fixes two whitespace inconsistencies in the scaffolded Gruntfile.
> Scaffolded plugin header should follow WPCS Docs standards

- php/commands/scaffold.php
- templates/child_theme_functions.mustache
A parent theme can include dashes, which aren't safe for a function.
Also passes `slug` to the template, so the ID for the child theme
stylesheet is populated.
Fixes #2195
> Use safe version of parent theme slug for child enequeue function

- php/commands/cache.php
When using a persistent object cache with Multisite, flushing is
typically a global operation.
> Clarify documentation for `wp cache flush`

- features/super-admin.feature
- php/commands/super-admin.php
I noticed "plugin activate" doesn't try to activate plugins that are already active but rather outputs a warning. I changed "super-admin add" to do the same thing when trying to add a super-admin who is already a super-admin. I also updated the success message output so it only outputs if something actually changed (if update_site_option() returns true).
> Super admin dupe warning

- php/WP_CLI/Loggers/Base.php
- tests/test-logging.php
Added `in_color` property to `Base`.
To support unit testing on the loggers, I also created `getRunner` as a protected function. This can be overloaded in the test-logging unit test where `WP_CLI` isn't available.
Fixes #2209
> 2209: Added in_color property to base logger; added relevant unit tests

- php/utils.php
If `open_basedir` is in effect, PHP will throw a notice when
`is_readable()` is used on an unreadable directory. We _could_ have some
more complicated check to see if the path being checked is within
`open_basedir` defined paths, but checking the return value of
`is_readable()` is sufficient for our needs.
Fixes #1332
> Suppress notices when using `is_readable()`

- features/search-replace.feature
- php/commands/search-replace.php
This more closely maps to expected behavior.
However, if `--no-recurse-objects` is provided, respect that flag too.
Fixes #1719
> Recurse objects by default when replacing inside of serialized data

- php/commands/import.php
The former gives us more control over verbosity.
See #1159
> In `wp import`, use `WP_CLI::log()` instead of `WP_CLI::line()`

- features/core.feature
- php/commands/core.php
Because of how core executes `populate_network()`, this option is
erroneously set to an empty value when WP-CLI installs multisite.
The correct behavior is to disable multisite quotas by default on new
installs. See https://core.trac.wordpress.org/ticket/21513
Fixes #1371
> Ensure `upload_space_check_disabled=>1` when installing multisite

- php/commands/core.php
- php/commands/cron.php
- php/commands/taxonomy.php
- php/commands/user.php
- php/utils-wp.php
- php/utils.php
Tagged WordPress releases include `-src` in `$wp_version`, which
`version_compare()` doesn't like. We need to make sure to strip it to
get an accurate result.
Fixes #2164
> Introduce `wp_version_compare()` for comparing WP versions

- php/commands/search-replace.php
```
Checking: wp_links.link_rss
0 rows affected using SQL (in 0.001s)
Checking: wp_options.option_name
0 rows affected using SQL (in 0.001s)
Checking: wp_options.option_value
0 rows affected using PHP (in 0.009s)
Checking: wp_options.autoload
0 rows affected using SQL (in 0.002s)
```
This can be helpful for better understanding where bottlenecks are
> Indicate execution time when running search/replace with `--verbose`

- php/commands/search-replace.php
If the replacement value is the same as the original value, we don't
need to perform an update
> Prevent unnecessary calls to `$wpdb->update()` when no replacements

- php/WP_CLI/CommandWithUpgrade.php
When requesting a non-existant version of a plugin such as Easy Updates Manager (which has the slug 'stops-core-theme-and-plugin-updates'), the `alter_api_response` function incorrectly reports that the requested version of the _theme_ could not be found.
This happens because that function checks for the substring 'theme' in the URL returned by the WordPress repository API to determine whether the requested resource is a theme or a plugin.
This change makes the substring test stricter, by expecting the URL to contain the string '/theme/' for themes. It also performs a similar check for plugins ('/plugin/'), and if both checks fail, it will produce a more generic response (e.g. Can't find the requested plugin/theme's version...)
> Improve plugin vs. theme detection for the error generated when the requested version of a plugin or theme does not exist

- features/search-replace-export.feature
- features/search-replace.feature
- php/commands/search-replace.php
For instance, to replace instances of "foo" with "bar" without transforming the database:
```
wp search-replace foo bar --export=database.sql
```
Also begins to abstract arguments to class-level variables for easier reuse between methods.
Props @westonruter for much of the original code
Fixes #709
> Use `--export=<file>` to `search-replace` to a saved file

- features/core.feature
- php/commands/core.php
This changes the behavior of `wp core check-upate` to only list one major
update. Users should be updating to the latest major release, not an
intermediate one.
Fixes #1850
> Use `--minor` flag with `wp core update` to update to latest minor

- php/commands/help.php
Doing so gives more control to the end user on how their output will be
presented.
Fixes #2110
> Defer to `$PAGER` environment variable when set

- features/upgradables.feature
- php/WP_CLI/CommandWithUpgrade.php
We can, more or less, safely interpret this `WP_Error` response to mean
no matching plugins or themes.
Fixes #2181
> A more helpful error message when a plugin or theme slug doesn't exist

- php/WP_CLI/Runner.php
- php/wp-settings-cli.php
This helps to reduce the difference between `wp-settings-cli.php` and
`wp-settings.php`. It has no functional differences.
See #2278
> Load `utils-wp.php` right before `wp-settings-cli.php` is called

- .gitignore
- composer.lock
Applications should commit composer.lock to the repository. The ensures that future builds of old tags produce predictable results.  See the [Composer documentation on the composer.lock files](https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file).
**Aside:** Note that libraries typically do not commit composer.lock, as dependency version locking is the responsibility of the application.
> Commit composer.lock to repository.

- php/commands/rewrite.php
Core does some fancy logic to determine whether `index.php` needs to be
prepended to rewrite rules. `got_url_rewrite()` returns true if mod
rewrite is available or `$GLOBALS['is_nginx']` is set. However, php-cli
doesn't easily have access to these values. Instead, let's assume the
developer knows the value they're passing, and that rewrites are
configured for the site.
Fixes #2184
> Don't ever prefix rewrite rules with `index.php`

- php/commands/transient.php
There's a typo in the synopsis for `set`. That typo is causing fatal errors in commands like
`wp transient set "51ecb1f884" "Cache rules everything around me." "2592001"`
Adding in the missing **>** fixes the problem.
> Fix typo in function synopsis

- features/media-regenerate.feature
- php/commands/media.php
This flag is helpful on sites with lots of images where only a small
number of images are missing sizes.
Props @michalkleiner for much of the original code
Originally #1830
> Use `--only-missing` to only regenerate images missing sizes

- features/core-update-db.feature
- php/commands/core.php
This can be helpful for determining whether a backup should be made,
without incurring a backup each time `wp core update-db` is run.
Fixes #2171
> Use `wp core update-db --dry-run` to see if database needs update

- php/WP_CLI/Dispatcher/CompositeCommand.php
- templates/man-params.mustache
See https://github.com/wp-cli/wp-cli/pull/1515#discussion_r21326157
> Remove extra lines before global parameters when calling `wp post --help`

- php/commands/search-replace.php
We'll be using PHP mode in this context anyway
> search-replace: Drop unneeded `REGEXP` when in regex mode

- php/commands/plugin.php
It's different than deactivating + uninstalling.
See #2315
> Clarify behavior of `wp plugin delete`

- features/framework.feature
- php/WP_CLI/Runner.php
They're expected to be global, so we should explicitly make it so.
From #2316
> Magically globalize any new variables defined in wp-config.php

- features/cron.feature
- php/commands/cron.php
Note: `wp cron event run` ignores the scheduled time for the event. If
you need to run a specific event on a specific schedule, you'll need to
replicate said schedule with system cron.
Fixes #2306
> Run multiple cron events, or use `--all` to run all of them

- php/WP_CLI/Dispatcher/Subcommand.php
> Use readline for `--prompt`, which properly supports arrow keys

- .travis.yml
- ci/behat-tags.php
- features/core-check-update.feature
- features/core-update.feature
- features/eval.feature
- features/menu.feature
- features/shell.feature
Skip tests which download versions of WordPress earlier than 4.4, as
they throw error notices in PHP 7.
Fixes #1842
> Officially support PHP 7

- php/commands/search-replace.php
* Expand description to clarify on default behavior.
* Order arguments based on priority.
* Format argument descriptions within 80 character width.
> Clean up search-replace documentation

- features/config.feature
- php/WP_CLI/Runner.php
```
Error: Required file 'missing-file.php' doesn't exist (from project's
wp-cli.yml).
```
```
Error: Required file 'baz.php' doesn't exist (from global config.yml).
```
Fixes #1485
> Specify context for missing required files

- php/commands/core.php
If database errors occur, let the user know with:
```
Error: Installation produced database errors, and may have partially or
completely failed.
```
We should only show a success message when there aren't database errors.
Fixes #1075
> Assume db errors during `wp_install()` to be installation failure

- php/commands/scaffold.php
- templates/plugin.mustache
This makes it possible to expose them with `--prompt`
Fixes #729
> Provide plugin header details at runtime for `wp scaffold plugin`

- features/flags.feature
- php/WP_CLI/Runner.php
Globalize `$path`, used until WP 3.9 for determining subsites in MS
Introduced in #2120
> Fix use of `--url` with multisite in WP < 3.9

- features/core-update.feature
- php/commands/core.php
It updates to the latest major release, which it shouldn't
Introduced in #2256
> Fix `wp core update --minor`

- features/site-empty.feature
- features/site.feature
- php/commands/site.php
> Use `--uploads` with `wp site empty` to delete the uploads dir too

- php/commands/core.php
> Use `--skip-email` to disable email notif on `core install`

- php/commands/user.php
It shouldn't, but in some cases it does. Also prevents email
notification from being sent when a user isn't created.
Fixes #1820
> Indicate error when `wp_insert_user()` returns 0

- php/commands/core.php
While it wouldn't realistically ever be defined in this scope, a PHP
script calling `install()` twice would fatal on the second time. Better
safe than sorry.
> Ensure `wp_new_blog_notification()` isn't defined before we do so

- php/WP_CLI/CoreUpgrader.php
- php/WP_CLI/REPL.php
- php/commands/cli.php
- php/commands/core.php
- php/utils.php
Also warns end user when the temp directory isn't writable.
Fixes #1118
> Introduce `WP_CLI\Utils\get_temp_dir()` for safer temp directories

- features/transient.feature
- php/commands/transient.php
> Use `--network` flag for `wp transient *` to manage site transients

- php/class-wp-cli.php
Switching response to auto lower case allows us to use Y or y as yes
> Switched confirm response to auto lower case

- php/WP_CLI/CoreUpgrader.php
Check update file download response status.
Now, when I try to update version which not already exist like 4.4.1-ja (that is it now), that return 404 and no content, but wp-cli try to unzip null file, and throw `PCLZIP_ERR_BAD_FORMAT (-10) : Unable to find End of Central Dir Record signature`.
It should check is response succeed.
> Check update file response status

- php/commands/user.php
* Only fetch user IDs, to avoid join with user meta table.
* Skip unnecessary `SQL_CALC_FOUND_ROWS`
Fixes #2369
> Improve performance of `wp user list --format=count`

- templates/install-wp-tests.sh
The paths in the remaining of the function are relative to the main directory, so the script shouldn't cd in WP_TESTS_DIR.
> Don't cd in WP_TESTS_DIR before dowloading and setting up wp-tests-config.php

- php/WP_CLI/Runner.php
This enables code injected via `--require` to make modifications at
runtime.
> Add `(before|after)_wp(_config)_load` hooks in WP load process

- php/commands/post.php
When we only want the sum total, we don't need to fetch all data for
each post.
> Faster performance for `wp post list --format=count`

- features/command.feature
- php/WP_CLI/Dispatcher/CompositeCommand.php
- php/WP_CLI/Dispatcher/Subcommand.php
- php/WP_CLI/SynopsisParser.php
- php/class-wp-cli.php
- tests/test-synopsis.php
Permits registration of these command attributes through variable,
instead of PHPDoc. For instance:
```
WP_CLI::add_command( 'foo', 'foo', array(
'shortdesc'   => 'My awesome function command',
'when'        => 'before_wp_load',
'synopsis'    => array(
array(
'type'          => 'positional',
'name'          => 'message',
'description'   => 'An awesome message to display',
'optional'      => false,
),
array(
'type'          => 'assoc',
'name'          => 'apple',
'description'   => 'A type of fruit.',
'optional'      => false,
),
array(
'type'          => 'assoc',
'name'          => 'meal',
'description'   => 'A type of meal.',
'optional'      => true,
),
),
) );
```
See #2374
> Use `shortdesc`, `synopsis`, and `when` with `::add_subcommand()`

- features/command.feature
- php/WP_CLI/Dispatcher/CommandFactory.php
- php/class-wp-cli.php
This permits an instance to be shared between commands, or be
instantiated with additional data.
See #2204
> Persist object when using `WP_CLI::add_command()` with class method

- php/class-wp-cli.php
Data is typically an array. Giving us a flattened array is more helpful
than indicating "Array"
> In `WP_CLI::error_to_string()`, `json_encode()` `WP_Error` data

- features/scaffold.feature
- php/WP_CLI/Dispatcher/Subcommand.php
Some WP-CLI commands call other WP-CLI commands, and can produce erroneous
results when they prompt a second time.
> Only prompt for the first command in the execution thread

- features/core-download.feature
- features/core-update.feature
- php/commands/core.php
Everything in wp-content should be considered user data
cc @gilbitron
Inroduced in #2382
> Don't ever clean up wp-content with `wp core update` or `wp core download`

- templates/man.mustache
Sometimes there may not be a short description available.
> Only display `$shortdesc` in man doc when present.

- features/core-download.feature
- php/commands/core.php
If we're downloading to an empty directory, skip the operation.
Bug introduced in #2382
> Only clean up `wp core download` when WP was already present

- php/commands/theme.php
This can kill other scripts calling the method directly. `return` is
fine for our needs to stop command execution.
Fixes #2411
> Don't `exit` on premature success for `wp theme activate`

- features/term.feature
- php/commands/term.php
Check if taxonomy exists before listing its terms to differentiate between a taxonomy with no terms and a nonexistent taxonomy,
> Check if taxonomy exists before listing its terms

- php/commands/server.php
Ran this on windows:
```
B:\Archpaper>vendor\bin\wp server --port=4900 --path=build
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```
While fixing, ran into a different [bug in PHP](https://bugs.php.net/bug.php?id=60181) (it seems to be windows-specific, but I can't confirm as all my linux php binaries reside in folders without spaces), so I added a workaround for that as well.
This is what I get after applying the fix:
```
B:\Archpaper>vendor\bin\wp server --port=4900 --path=build
PHP 7.0.1 Development Server started at Fri Jan 29 22:46:00 2016
Listening on http://localhost:4900
Document root is B:\Archpaper\build
Press Ctrl-C to quit.
```
> Fix `wp server` when php binary contains spaces

- php/commands/server.php
> Use `\WP_CLI\Utils\is_windows()` instead of dupe abstraction

- features/core-check-update.feature
- features/core-update.feature
- php/commands/core.php
Also bumps WP version in tests for latest release.
From #2382
> Support for cleaning up files when ZIP is provided to `core update`

- features/cron.feature
- php/commands/cron.php
When running multiple events at once, this makes it easier to see which
are taking a long time.
```
salty-wordpress ➜  wordpress-develop.dev  wp cron event run --all
Executed the cron event 'wp_update_plugins' in 0.421s.
Executed the cron event 'wp_update_themes' in 0.287s.
Executed the cron event 'wp_version_check' in 1.315s.
Executed the cron event 'update_network_counts' in 0.004s.
Executed the cron event 'wp_scheduled_auto_draft_delete' in 0.004s.
Success: Executed a total of 5 cron event(s).
```
Fixes #2434
> Add a timer to individual events in `wp cron event run`

- features/media-import.feature
- php/commands/media.php
If no IPTC data is present, use the filename as the attachment title.
Fixes #2416
> Persist IPTC data in `wp media import` when missing title/caption

- features/framework.feature
- php/class-wp-cli.php
For instance:
```
WP_CLI::error( 'This is return code 5.', 5 );
```
Fixes #2386
> Support custom exit codes in `WP_CLI::error()`

- php/WP_CLI/CommandWithUpgrade.php
WP-CLI intends to be precise and atomic; this behavior is neither.
Fixes #2073
> Don't check translation updates when updating themes or plugins

- php/commands/user.php
We have a plugin in application that listens to the Hook wpmu_new_user. Here we noticed that the new user at the time still has no email. The problem was that the parameters are passed in the wrong order on wpmu_create_user.
> Parameter sequence corrected for wp_create_user.

- .gitignore
- composer.json
- composer.lock
- features/bootstrap/FeatureContext.php
- features/package.feature
- php/WP_CLI/ComposerIO.php
- php/WP_CLI/PackageManagerEventSubscriber.php
- php/WP_CLI/Runner.php
- php/commands/package.php
- utils/make-phar.php
Use `wp package browse` to view all available community commands.
Install a specific command with `wp package install
<namespace/package-name>`. List all installed packages with `wp
package list`. Or, uninstall a package with `wp package uninstall`
Packages are installed to their own Composer project in `~/.wp-cli/packages`.
This can be changed by setting a `WP_CLI_PACKAGES_DIR` environment variable.
See #1564
Previously #936
> Introduce `wp package` for managing WP-CLI community commands

- php/commands/core.php
WordPress doesn't follow semver, so `--minor` would take you from WP 4.3
to WP 4.3.3 instead of WP 4.4.2
From https://github.com/wp-cli/wp-cli/issues/2441#issuecomment-179308541
> Explain nuances of `wp core update --minor`

- php/commands/cron.php
`Cron_Event_Command::run_event()` always returns true
See #2445
> Remove dead error handling code in `Cron_Event_Command->run()`

- php/commands/plugin.php
- php/commands/theme.php
> Explain exit codes for `wp (theme|plugin) is-installed`

- features/theme.feature
- php/WP_CLI/CommandWithUpgrade.php
- php/WP_CLI/UpgraderSkin.php
> Add json and csv formats to upgrade output

- composer.json
- composer.lock
- php/WP_CLI/Formatter.php
More often than not, strings are accidentally colorized because they
contain colorization tokens. Developers can still colorize their strings
in advance, and include the colorized strings in their table.
Fixes #2455
> Don't colorize `format=table` by default

- features/core-verify-checksums.feature
- php/commands/core.php
Hi,
I thought it would be nice not to load WordPress in `wp core verify-checksums`.
With this change, you can do:
wp core download
wp core verify-checksums
Before, you had to either specify version with `--version` or install and load WordPress before calling `wp core verify-checksums`.
> Avoid loading WordPress in `wp core verify-checksums`

- features/core-download.feature
- php/commands/core.php
To permit offline use of the download cache, verification only happens
when downloading a new copy of WordPress.
Fixes #1899
> Verify md5 hash when `wp core download`

- features/media-import.feature
- php/commands/media.php
This better mirrors core's behavior.
From #2438
> Default title for `wp media import` images shouldn't include extension

- features/core.feature
- php/commands/core.php
This PR adds two checks to verify if PHP has write permission before attempting to create a directory and extract WordPress file when running `wp core download`.
I've also added two basic tests for `wp core download` but I was unable to find a way to test the two error messages I've added. Any suggestion?
> `wp core download` should check for permission before attempting to create directory and download WP

- features/core-check-update.feature
- features/core-update.feature
- php/commands/core.php
The version check API will give us exact URLs to upgrade packages. We shouldn't, imprecisely, build the download offers on our own.
Fixes #2468
> Use core's version check API for finding updates

- php/config-spec.php
> Note: mu-plugins are still loaded with `--skip-plugins` flag

- templates/.editorconfig
This makes indentation more readable in editors.
> Set default `indent_size=4` when scaffolding `.editorconfig`

- php/export/class-wp-export-query.php
Was getting this:
> Notice: Undefined index: name in `/Users/mark/.composer/vendor/wp-cli/wp-cli/php/export/class-wp-export-query.php` on line `176`
> Avoid PHP Notice about undefined index

- php/wp-settings-cli.php
Introduced in https://core.trac.wordpress.org/changeset/36566/
Build began failing in #2485
> Add compatibility with WP 4.5 by loading `WP_Metadata_Lazyloader`

- features/cli.feature
- php/commands/cli.php
Because `php file.xml` returns exit code `0`, we need to run a command
where only WP-CLI will return the string we expect.
Fixes #2483
> Use more robust failed download checking in `wp cli update`

- php/WP_CLI/PackageManagerEventSubscriber.php
```
PHP Catchable fatal error:  Argument 1 passed to
Composer\DependencyResolver\Rule::getPrettyString() must be an instance
of Composer\DependencyResolver\Pool, none given, called in
/home/vagrant/.wp-cli/php/WP_CLI/PackageManagerEventSubscriber.php on
line 40 and defined in
/home/vagrant/.wp-cli/vendor/composer/composer/src/Composer/DependencyResolver/Rule.php
on line 161
```
See #2482
Related #1564
> Fix fatal error when a dependency needs to be installed

- php/utils.php
> Mark `WP_CLI\Utils\make_progress_bar()` as a public internal API.

- features/help.feature
- php/WP_CLI/Runner.php
While it would be more ideal to run help early _always_ when core isn't
installed, we are unable to easily inspect the database for blog tables.
This change permits `wp help core install` to be run when
`wp-config.php` is created, but the database isn't yet configured.
Previously, the user would see a "Database not created" error.
Fixes #2191
> Run help early for `wp core` commands used when core isn't yet installed

- features/config.feature
- php/WP_CLI/Configurator.php
A `config.yml`, `wp-cli.yml` or `wp-cli.local.yml` configuration file now supports two configuration parameters:
```
_:
merge: true
inherit: <file>.yml
```
`merge` will merge any argument definition, fixing #2069.
`inherit` supports inheriting an arbitrary YAML file, fixing #1063
> Support config deep merging and inheritance

- features/bootstrap/FeatureContext.php
This is much easier than provisioning a Behat YML config and having to
use that.
> When running tests inside of a package, autoload composer.json files

- features/command.feature
- php/WP_CLI/Dispatcher/CommandFactory.php
It should use the instantiated object, not try to instantiate it again.
From #2373
> Fix registering instantiated object with `__invoke()` method

- php/commands/package.php
> Sort package lists alphabetically; provide breathing room between author names

- features/help.feature
- php/WP_CLI/Dispatcher/CompositeCommand.php
- templates/man-params.mustache
Also ensures GLOBAL PARAMETERS are added to commands with synopsis passed as `$args`
Previously:
> Fix formatting of GLOBAL PARAMETERS when command has subcommands

- features/bootstrap/FeatureContext.php
Some shells format output differently. We can easily accommodate minor
formatting changes, though.
See #2111
> Accommodate spaces in `ps -o ppid,pid,command` output

- php/commands/search-replace.php
Otherwise, the `*` is markdownified.
> Fix formatting of search-replace wildcard example

- php/WP_CLI/ComposerIO.php
- php/commands/package.php
* Update `WP_CLI\ComposerIO` to write error messages too.
* Display return code when Composer installer returns one.
See #1564
> Make `wp package install` more verbose

- php/commands/search-replace.php
Quotes are more friendly and understandable to end users.
From https://twitter.com/wpcli/status/706906502892654592
> Quote example in `wp search-replace` instead of escaping

- features/search-replace.feature
- php/commands/search-replace.php
The where clause was constructed without regard to handling multiple
column keys nor quoting character values.
The example table that the previous technique doesn't work with is
wp_wp_super_edit_options which has a primary key on id and name.
Adding single quotes around integer values has no negative effect.
CREATE TABLE "wp_wp_super_edit_options" (
"id" bigint(20) NOT NULL AUTO_INCREMENT,
"name" varchar(60) NOT NULL,
"value" text NOT NULL,
PRIMARY KEY ("id","name"),
UNIQUE KEY "name" ("name")
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8
> Handle multi-column keys in search and replace

- php/commands/cli.php
If there are no major, minor, or patch updates available, let's assume
the user is running a nightly build for the latest release. If they're
running a nightly build for the latest release, we can compare their
current hash to the latest nightly build hash. When they differ, we can
assume the latest nightly build is more recent than the local copy.
See #1011
> Support nightly builds with `wp cli check-update`

- features/package-install.feature
- php/commands/package.php
Apparently this causes Composer to skip 'wp-cli/wp-cli' as a dependency, which is exactly what we want.
Fixes #2493
> Use 'wp-cli/wp-cli' for the Composer project name in our package dir

- php/commands/package.php
If you want to contribute to one, this is an easy way to dive in.
See #1564
> Use `wp package path` to get the path of an installed package

- php/WP_CLI/Runner.php
Auto check update only happens when a user is driving WP-CLI, not a
script. `WP_CLI_AUTO_CHECK_UPDATE_DAYS` environment variable can be used
to change the number of days between checks (defaults to 1).
`WP_CLI_DISABLE_AUTO_CHECK_UPDATE` can be used to disable the update
check entirely.
Fixes #1011
> Nag user when there's an update to WP-CLI available

- php/utils.php
The composer-vendor-dir can be defined in the config section of the composer.json.
Unfortunately the utils.php looks up the vendor dir at the wrong place
so the autoloader can never be reached.
This commit fixes the flaw in ::get_vendor_paths().
> Bugfix: Vendor-dir is defined in the config-section

- templates/post_type.mustache
- templates/taxonomy.mustache
These are pretty well-established now.
Fixes #2158
> Add WP REST API registration args to `scaffold (post-type|taxonomy)`

- composer.json
- composer.lock
* Permit composer/semver >= 1.0 for greater flexibility. Fixes #2553
* Update to composer/semver 1.3.0
* Update to mustache/mustache 2.10.0
* Update to symphony/config 2.7.10
* Update to symphony/console 2.7.10
* Update to symfony/dependency-injection 2.7.10
* Update to symfony/event-dispatcher 2.7.10
* Update to symfony/filesystem 2.7.10
* Update to symfony/finder 2.7.10
* Update to symfony/process 2.7.10
* Update to symfony/translation 2.7.10
* Update to symfony/yaml 2.7.10
> Update Composer dependencies for v0.23.0

- features/package.feature
- php/WP_CLI/Runner.php
If a user installs a bad package, we want them to be able to back out of it.
See https://github.com/wp-cli/wp-cli/issues/2548#issuecomment-194870695
See #1564
> Run `wp package` commands before any packages are loaded

- features/command.feature
- php/WP_CLI/Dispatcher/Subcommand.php
- php/WP_CLI/DocParser.php
- php/class-wp-cli.php
- tests/test-doc-parser.php
`default` fills the value when it isn't set. `options` validates the
filled value against an enum of values.
YAML for the win:
```
--volume=<number>
: Sets the volume.
---
default: 10
---
```
Fixes #1293
Fixes #1294
> Support registering `default` and `options` for positional/assoc args

- php/class-wp-cli.php
Doing so prevents wonky formatting when `description` isn't set.
Bug introduced in #2512
> Only register `description` for a command when present

- features/package.feature
- php/WP_CLI/Runner.php
- php/config-spec.php
A similar idea to `--skip-plugins`, if a package has gone awry, permit
normal usage of WP-CLI.
See #1564
> Use `--skip-packages` to skip loading installed packages

- php/WP_CLI/CommandWithUpgrade.php
- php/commands/plugin.php
There didn't appear to be a way to add the page parameter, and some searches are too large
to pull down the full answer set.
Now it is possible to write queries like:
wp plugin search <SOMETHING> --page=2
> Added support for page parameter.

- features/plugin-search.feature
- php/WP_CLI/CommandWithUpgrade.php
- php/commands/plugin.php
They need to be supplied in the first place, and passed in a
non-standard format.
Fixes #2568
> Properly add `wp plugin search` fields to plugins_api() request

- php/WP_CLI/CommandWithUpgrade.php
Fixes error notices when we're rendering the special case `parent`
status.
See https://github.com/wp-cli/wp-cli/pull/2034#issuecomment-198430899
> Add `parent` as a potential status in `wp theme status`

- templates/test-sample.php
Ideally, that `@package` would have the `{{plugin_slug}}`, but I realise this isn't passed through to this template yet.
> Add documentation to test-sample.php

- php/class-wp-cli.php
This is much better than rolling our own equivalent logic
> Use `is_callable()` in `WP_CLI:add_command()`

- php/export/class-wp-export-query.php
2ad7b8e21fa introduced a PHP notice because `$this->filters['skip_comments']` is checked, but it won't exist if the flag isn't set.
> Squash `wp export` notice about `skip_comments`

- features/comment-generate.feature
- features/post-generate.feature
- features/term-generate.feature
- features/term.feature
- features/user-generate.feature
- features/user.feature
- php/commands/comment.php
- php/commands/post.php
- php/commands/term.php
- php/commands/user.php
More helpful than a progress bar for chaining commands together:
```
wp user generate --format=ids | xargs -0 -d ' ' -I % wp user meta add %
foo bar
```
Fixes #2224
> Use `--format=ids` with `wp (*) generate` output generated ids

- features/command.feature
- php/WP_CLI/Dispatcher/CompositeCommand.php
- php/WP_CLI/Dispatcher/RootCommand.php
- php/WP_CLI/Runner.php
This permits a subcommand to be de-registered from its parent.
Also modifies the bootstrap process to always register commands, instead
of lazyloading them based on command name. Packages and required
commands are always loaded, so we should follow similar behavior with
core commands.
> Introduce `CompositeCommand->remove_subcommand()`

- features/bootstrap/FeatureContext.php
When Behat has been globally installed, our project autoload isn't
always called.
> Ensure vendor libraries are available

- features/plugin.feature
- features/scaffold.feature
- templates/plugin-packages.mustache
- templates/plugin.mustache
Currently if you scaffold a child theme and a plugin, the theme uses `0.1.0` for the version number, while the plugin uses `0.1-alpha`, which is itself different than the version used in the plugin's `package.json` (`0.0.0`). The plugin headers are also formatted differently than the child theme headers. This pull request normalizes the version numbers and header formatting and updates related functional tests.
> Normalize plugin / theme version numbers and header formatting

- features/media-regenerate.feature
- php/commands/media.php
Also considers image needing regeneration if `sizes` is empty (which means its missing all sizes).
Fixes #2608
> Consider image sizes missing when `sizes` doesn't have registered sizes

- features/command.feature
- php/WP_CLI/Dispatcher/Subcommand.php
- php/class-wp-cli.php
This appears to be an oversight from
6ae19150fe3263b5b19e1237c58b92f73d9eab15 that no one has noticed since.
Keep calling the parent too, for backwards compat purposes.
> Run `before_invoke` and `after_invoke` callbacks on subcommands

- features/config.feature
- features/package.feature
- php/WP_CLI/Loggers/Base.php
- php/WP_CLI/Runner.php
- php/class-wp-cli.php
- php/config-spec.php
When `--debug` is used as a flag, the group is included in the prefix:
```
salty-wordpress ➜  wordpress-develop.dev  wp option get home --debug
Debug (bootstrap): Using default global config: /home/vagrant/.wp-cli/config.yml (0.051s)
Debug (bootstrap): Using project config: /srv/www/wordpress-develop.dev/wp-cli.yml (0.054s)
Debug (bootstrap): Loading packages from: /home/vagrant/.wp-cli/packages/vendor/autoload.php (0.287s)
Debug (bootstrap): Required file from config: /srv/www/wp-hook-command/command.php (0.428s)
Debug (bootstrap): ABSPATH defined: /srv/www/wordpress-develop.dev/src/
(0.428s)
Debug (bootstrap): Begin WordPress load (0.433s)
Debug (bootstrap): wp-config.php path: /srv/www/wordpress-develop.dev/wp-config.php (0.436s)
Debug (bootstrap): Loaded WordPress (1.307s)
Debug: No …
```
> Use `--debug=<group>` to limit debug output to a particular group

- php/class-wp-cli.php
This prevents the comment from being rendered as HTML on the website.
> Use backticks when mentioning hooks

- php/WP_CLI/REPL.php
- php/commands/shell.php
Resolves https://github.com/wp-cli/wp-cli/pull/2601#discussion_r59474161
@danielbachhuber: This adds newlines to output when needed, rather than every time the prompt is printed.
I've also taken a cue from other REPL implementations and added a `=> ` before the `var_dump` for expression returns to differentiate expression return values from output that occurs during expressions.
examples:
```
wp> echo "foo";
foo
wp> date ( 'ymd' );
=> string(6) "160414"
wp> echo date( 'ymd' );
160414
wp> print_r( [1,2,3,4] );
Array
(
[0] => 1
[1] => 2
[2] => 3
[3] => 4
)
=> bool(true)
wp> print_r( [1,2,3,4], 1 );
=> string(62) "Array
(
[0] => 1
[1] => 2
[2] => 3
[3] => 4
)
"
wp>
```
Same as above but on 0.23.0 release:
```
wp> echo "foo";
foowp> date ( 'ymd' );
string(6) "160414"
wp> echo date( 'ymd' ); …
```
> Refactor adding newline to shell prompt

- composer.json
- composer.lock
```
- Removing seld/cli-prompt (1.0.1)
- Installing seld/cli-prompt (1.0.2)
```
> Bump composer.json to use Composer 1.0.0

- php/WP_CLI/CommandWithTranslation.php
> Catch `WP_Error` from `translations_api()`

- composer.json
- composer.lock
While WP-CLI may work with earlier versions, this is the minimum version
we can support because 5.3.29 is the version available in Travis.
Fixes #2669
> Increase minimum supported version to PHP 5.3.29

- features/rewrite.feature
- php/class-wp-cli.php
Use of this method has a reasonable expectation that the launched process will mirror the existing process as closely as possible. Including the global WP-CLI config is necessary for mirroring the existing process.
Fixes #1981
> Persist global WP-CLI config when using WP_CLI::launch_self()

- features/plugin.feature
- php/commands/plugin.php
When the `--all` flag is provided, we should only try to activate
plugins that aren't active, and deactivate plugins that are active.
Fixes #2652
> Don't erroneously try to (de)activate plugins with `--all` flag

- php/WP_CLI/Runner.php
Some plugins make use of this constant to conditionally load code, which
is a valid use case we should do our best to accommodate.
Fixes #2679
> Define `DOING_CRON` before WordPress is loaded

- php/commands/user.php
The function isn't available on a normal WordPress.
Fixes #2680
> Only attempt to use `add_user_to_blog()` on multisite

- .travis.yml
- ci/prepare.sh
- ci/test.sh
- features/bootstrap/FeatureContext.php
- utils/make-phar.php
Broken since 326c3bb2b86ea2639c38d1585fc09dc8d1c06d35, because you can't set an environment variable from a shell script.
I don't know at what point we started producing a broken build, but the latest stable release is confirmed working.
> Genuinely run test suite against built Phar file; including missing dependencies

- utils/make-phar.php
Without it, `wp package list` and `wp package browse` can fatal. I'm not sure how long this has been broken in the Phar build.
> Include pem file that is occasionally needed by Composer

- features/scaffold.feature
- php/commands/scaffold.php
- templates/plugin-svnignore.mustache
For authors intending to distribute to WordPress.org, this is a helpful
starter template of exclusions.
> Include a `.svnignore` when scaffolding a new plugin

- features/user-meta.feature
- php/commands/user.php
All methods on this class need to replace a provided username / email
address with the user id, which this method wasn't doing.
> Fix listing user meta associated with a given username

- features/comment.feature
- php/commands/comment.php
Change the output of `wp comment delete` from:
`Success: Deleted comment {COMMENT_ID}.`
To:
`Success: Trashed comment {COMMENT_ID}.`
To differentiate it from the output of `wp comment delete --force` and to make it clear that `wp comment delete` trashes the comment.
Originally #2521
> Differentiate output when moving comments to trash from output when deleting comments

- php/commands/core.php
This behavior changed in the last release
> Clarify that `wp core verify-checksums` doesn't actually load WP

- features/plugin.feature
- php/WP_CLI/CommandWithUpgrade.php
If a user supplies an empty slug, its likely a mistake. WP-CLI shouldn't
proceeed to install the first result from WordPress.org
Fixes #2708
> Ignore ambigious empty plugin and theme slugs when installing

- php/WP_CLI/DocParser.php
- tests/test-doc-parser.php
When an example is included at the beginning of the command, we need to make sure we don't match on example usage.
From #2587
> Fix greedy parsing of command args, part two

- features/comment.feature
- php/commands/comment.php
Resolve issue of taking only first digit from Comment ID in `comment` command.
Fixes #2710
> issue of taking only first digit from Comment ID

- php/commands/post-type.php
In the example `object-type` parameter is changed to `capability_type`
Fixes #2733
> fix incorrect parameter in post-type list command doc

- features/search-replace.feature
- php/commands/search-replace.php
Display success message in dry run in search-replace. Fix #2739
> Display success message in dry run in search-replace

- features/command.feature
- php/WP_CLI/Dispatcher/Subcommand.php
I should've written these tests cases originally. Because I didn't, the functionality has been broken since it was originally introduced in #2556
> Ensure `default` and `options` are used when supplied as arg args

- features/scaffold.feature
- php/commands/scaffold.php
- templates/plugin-readme.mustache
* Set latest version number to plugin's `readme.txt` and `.travis.yml`.
* Update minimum WP version in `.travis.yml` to 3.7 (WP-CLI's minimum require).
* `Stable tag` in `readme.txt` should has same value with `Version` in `templates/plugin.mustache`.
Thanks!
> get wp version when scaffolding plugin

- php/wp-settings-cli.php
> Conditionally require `WP_HTTP_Requests_Response` for WP 4.6 compat

- php/WP_CLI/Runner.php
- php/config-spec.php
It's been broken since 7a1499e0a3683f9d51dc18d73d8b087685a9e318
(v0.13.0)
Fixes #2749
> Remove `--config=<config>` as a runtime argument

- features/cli-info.feature
- php/commands/cli.php
This is more consistent with the other parameters displayed
> Only display packages directory path when it exists

- features/theme.feature
- php/commands/theme.php
New behavior:
```
salty-wordpress ➜  wordpress-develop.dev  wp theme status myth
Error: Stylesheet is missing.
```
Previous behavior:
```
salty-wordpress ➜  wordpress-develop.dev  wp theme status myth
Theme myth details:
Name: myth
Status: Inactive
Version:
Author:
```
See #2790
> Display error if theme directory exists but is erred; permit force install

- README.md
Probably easiest to see this in action on my fork: https://github.com/NateWr/wp-cli/tree/i2760_readme_update
Should tick all the boxes in #2760 except for installation requirements (see https://github.com/wp-cli/wp-cli/issues/2760#issuecomment-220031625).
Happy to go in a different direction with anything you don't like the look of.
> #2760 readme update

- php/commands/term.php
The example command is missing the required `<taxonomy>` parameter.
> Add a missing parameter to the example command for `wp term generate`.

- features/skip-themes.feature
- php/WP_CLI/Runner.php
- php/wp-settings-cli.php
Introduces `Runner->add_wp_hook()` and `Runner->remove_wp_hook()` for
adding actions and filters before `add_filter()` is defined.
To ensure child themes can be skipped from loading, the `stylesheet`
value is always checked.
Filter is added late on `setup_theme` hook to noop TEMPLATEPATH and
`STYLESHEETPATH`, and then removed early on `after_setup_theme` to
ensure use of `get_template_directory()` still works as expected. Unfortunately,
the downside is that the constants are defined incorrectly in this request,
but hopefully this is an acceptable cost to the value of `--skip-themes`.
See #2278
> Move `--skip-themes` feature to a filter, instead of wp-settings hack

- php/utils-wp.php
We've noticed that the `wp_get_cache_type()` utility method is returning with an empty `$message` due to a difference in the names of the cache bucket objects.
> Adds support for PHP 5.5 Memcache extension

- php/wp-settings-cli.php
It doesn't appear there is an actual reason not to.
Originally #917
See #2278
> Load wp-includes/vars.php in wp-settings-cli.php

- php/WP_CLI/Runner.php
- php/wp-settings-cli.php
Filters are added before the bootstrap process, to noop
`wp_get_active_network_plugins()` and
`wp_get_active_and_valid_plugins()`, and then removed early on
`plugins_loaded` to ensure later use of `get_option( 'active_plugins'
);` works as expected.
Unfortunately, `get_options( 'active_plugins' );` will be inaccurate on
the `muplugins_loaded` hook. Hopefully this will be an acceptable cost
to being able to continue using `--skip-plugins`.
See #2278
> Move `--skip-plugins` feature to a filter, instead of wp-settings hack

- php/WP_CLI/Runner.php
Originally introduced in 58ea052de3090dc5738ef933fde2120ac39fe64e, it
hasn't worked since dc8502de2d5fb39fe2430b4447633a171628adbb. The
original issue this hack solved should just be addressed in the plugin.
See #2278
> Remove `$pagenow` definition in `\WP_CLI\Runner`

- features/db.feature
- php/WP_CLI/Runner.php
- php/utils-wp.php
- php/wp-settings-cli.php
It's not necessary to add the callback as a part of the WP bootstrap
process, given the existing `\WP_CLI\Utils\replace_wp_die_handler()`
erroneously removes a callback that doesn't exist
See #2278
Originally #291
> Hook wp_die handler in \WP_CLI\Runner instead of wp-settings-cli.php

- features/core.feature
- features/framework.feature
- php/WP_CLI/Runner.php
- php/wp-settings-cli.php
* Move `ms_site_not_found` action inside of `WP_CLI\Runner`. From #1909
* Move `wp_redirect` handler to Runner from wp-settings-cli.php. From #521
* Move filters for suppressing multisite installation warnings. From #598
* Skip `ms_site_check` when installing. From #598
See #2278
> Move more filters into `WP_CLI\Runner` instead of wp-settings-cli.php

- features/aliases.feature
- php/WP_CLI/Configurator.php
- php/WP_CLI/Runner.php
Aliases are a way of defining a shorthand reference to a WordPress install.
One or more aliases can be defined in `config.yml` or `wp-cli.yml`:
```
@wpdev:
path: /srv/www/wordpress-develop.dev/src
```
An alias is called as the first argument to the `wp` executable:
```
salty-wordpress ➜  .wp-cli  wp @wpdev option get home
http://wordpress-develop.dev
```
The matching alias will overload the global parameters it defines. When an alias is used, any passed arguments will be treated as local parameters:
```
salty-wordpress ➜  .wp-cli  wp @wpdev option get home --path=/srv/www/wordpress-develop.dev/src
Error: Parameter errors:
unknown --path parameter
```
This last implementation detail provides a path forward for solving #1222 without breaking backwards compat.
See #2039
> Treat `@[A-Za-z0-9-_]+` defined in yml config as an alias

- php/WP_CLI/Runner.php
This more closely mirrors WordPress' behavior, allowing the rest of
`wp-settings.php` to operate under the expected user context.
See #2970
> Set current user on `init` early, instead of after wp-settings.php load

- php/WP_CLI/UpgraderSkin.php
`Plugin_Installer_Skin` and `Theme_Installer_Skin` both use a public
`$api` class variable. We can safely define this too to prevent the
error notice.
Fixes #2971
> Fix PHP notice when installing a child theme

- features/site.feature
- php/WP_CLI/Runner.php
When using WP-CLI without the `--user=<user>` argument, the expectation
is that you can perform any operation, and those operations aren't run
as any user. Even when the `--user=<user>` argument is provided, there's
a reasonable assumption the CLI operation isn't meant to run into a
capability check.
Fixes #2970
> Always permit CLI operations against sites, regardless of status

- php/WP_CLI/Runner.php
The current alias isn't meant to be passed through to the remote server.
See #2754, #2039
> Ignore the current alias when handling `--ssh`

- php/WP_CLI/Runner.php
```
$ wp --ssh=foo option get home
Error: Cannot connect over SSH using provided configuration.
```
Unfortunately, it doesn't seem possible to capture the SSH error itself.
`-o LogLevel=ERROR` still includes the "Connection closed" message.
Fixes #2765
> Provide more verbosity when `--ssh` fails

- features/theme.feature
- php/commands/theme.php
This makes `wp theme activate` behave more consistently with `wp plugin
activate`
Originally #2920
> Use `WP_CLI::warning()` when a theme is already active

- php/WP_CLI/Runner.php
- php/wp-settings-cli.php
Even though this will never be called, this ensures
`wp-settings-cli.php` is in closer parity to `wp-settings.php`
See #2278
> Restore `advanced-cache.php` to `wp-settings-cli.php`

- php/WP_CLI/Runner.php
- php/wp-settings-cli.php
Doing so mitigates our need to include it in a forked
wp-settings-cli.php. There is minimal risk in performing the AYS check
later in the bootstrap process.
See #2278
> Move the APC cache check to `muplugins_loaded`

- php/WP_CLI/Runner.php
- php/wp-settings-cli.php
We can use the new `bypass_debug_mode` filter to hook in our existing
`WP_CLI\Utils\wp_debug_mode()` call, and make sure it just runs once
See #2278
> Restore `wp_debug_mode()` call in `wp-settings-cli.php`

- features/core-config.feature
- php/WP_CLI/Runner.php
- php/wp-settings-cli.php
If `wp_not_installed()` identifies that WordPress isn't installed, it
will call `nocache_headers()` before trying to redirect. Hijacking this
particular filter lets WP-CLI exit with its own message before the
redirect is called, and avoid having to maintain a forked
`wp-settings-cli.php`
See #2278
> Abuse the `nocache_headers` filter to run our `Utils\wp_not_installed()`

- php/WP_CLI/Runner.php
e.g. `wp --ssh=v` or `wp --ssh=prod`
See #2754
> Support only a host being provided to `--ssh=<ssh>`

- php/wp-settings-cli.php
This will prevent error notices when using WP-CLI against <WP 4.6
See https://github.com/wp-cli/wp-cli/issues/2278#issuecomment-226634504
> Restore `defined( 'WP_INSTALLING' )` check in legacy wp-settings-cli.php

- php/WP_CLI/Runner.php
- php/utils-wp.php
- php/wp-settings-cli.php
In doing so, we're causing wpdb to be loaded slightly earlier in the
bootstrap process.
See #2278
> Perform dead db check earlier, by loading wpdb ourselves

- php/WP_CLI/Runner.php
- php/utils-wp.php
- php/wp-settings-cli.php
Maintaining a fork isn't a ton of fun.
Fixes #2278
> Use `wp-settings.php` instead of `wp-settings-cli.php` for >=WP4.6

- features/scaffold.feature
- templates/plugin-distignore.mustache
- templates/plugin-gitignore.mustache
This file is only ever meant for local development.
> Ignore `wp-cli.local.yml` in plugin scaffold `.gitignore`

- features/core-config.feature
- features/core.feature
- php/WP_CLI/Runner.php
- php/commands/core.php
Wrap wp-config.php file name with quotes in command messages.
> Wrap wp-config.php file name with quotes in command messages

- features/aliases.feature
- php/WP_CLI/Configurator.php
- php/WP_CLI/Runner.php
Given a `wp-cli.local.yml`:
```
@both:
- @prod
- @dev
@prod:
ssh: rc~/webapps/production
@dev:
ssh: v/srv/www/runcommand.dev
```
One can:
```
$ wp @both rewrite flush
Success: Rewrite rules flushed.
Success: Rewrite rules flushed.
```
See #2039
> First pass at alias groups

- php/commands/cron.php
Related https://github.com/wp-cli/wp-cli/issues/2837
> Improve default format in docs for cron commands

- features/menu.feature
- php/commands/menu.php
Fixes #3074 
---
Command: `wp menu list --format=ids`
If the format was ids, the whole menu array with wp_terms object got passed to the display_items() method. However the formatter could not convert the wp_terms object to a string.
Checked before passing the whole menu object array to the display_items method, if the format is ids. 
If yes, grabbed out the term_ids and passed only an array of ids to the display_items() method. 
---
Don't really know whats best practice here. You could also implode the `$ids` array directly, without passing it to display_items(). I checked other commands that have the `--format=ids` option, but they are a bit inconsistent. On some the ids get directly imploded and echo'ed out, on some they are passed to display_items(). But I think passing them to …
> Fix exception in menu list command if the format is ids #3074

- features/widget-reset.feature
- php/commands/widget.php
Initially at https://github.com/wp-cli/wp-cli/issues/3063, reset was supposed to be kept under sidebar. But after https://github.com/wp-cli/wp-cli/pull/3071 reset feature is kept under widget command. 
Fixes #3063
> Introduce reset subcommand for widget

- README.md
- features/plugin.feature
When deactivating a plugin via `wp plugin deactivate <plugin>`, the plugin doesn't get added to the "Recently Active" list.
Fixes #3069
> Recently active plugins list is not populated

- README.md
Related:
https://github.com/wp-cli/wp-cli.github.com/pull/163
> fix missing param in example

- php/wp-settings-cli.php
Includes class-wp-network-query.php and class-wp-post-type.php files
conditionally.
Fixes PHP Fatal error where `WP_Post_Type()` class cannot be found when executing `create_initial_post_types()`.
> Update cli settings to include new files from WP 4.6 beta.

- php/commands/menu.php
Menu locations doesn't have ids, so they can't be outputted
Fixes #3083
> Remove unsupported ids output of menu locations #3083

- composer.json
- composer.lock
Also moves php-cli-tools to `dev-master`, see #3095
```
- Removing wp-cli/php-cli-tools (v0.11.1)
- Installing wp-cli/php-cli-tools (dev-master 10cfa5b)
Cloning 10cfa5bd978889c8050cd48d70d179d775c31827
- Removing symfony/yaml (v2.8.7)
- Installing symfony/yaml (v2.8.8)
- Removing symfony/filesystem (v2.8.7)
- Installing symfony/filesystem (v2.8.8)
- Removing symfony/config (v2.8.7)
- Installing symfony/config (v2.8.8)
- Removing symfony/dependency-injection (v2.8.7)
- Installing symfony/dependency-injection (v2.8.8)
- Removing symfony/event-dispatcher (v2.8.7)
- Installing symfony/event-dispatcher (v2.8.8)
Downloading: …
```
> Update Composer dependencies to latest

- features/menu.feature
- php/commands/menu.php
As mentioned in #3083 reverted changed made in #3092 
Now the location itself gets outputted when you run `wp menu location list --format=ids`
> Fix error output on menu location list with format ids #3083

- php/WP_CLI/Runner.php
> Use `proc_open()` instead of `passthru()` to persist TTY mode

- features/cron.feature
- php/WP_CLI/Runner.php
`ALTERNATE_WP_CRON` tries to redirect, which we can't handle.
Fixes #3104
> Don't trigger cron when ALTERNATE_WP_CRON is defined

- php/commands/site.php
The value on the site object is created on the fly, not stored in a
database column.
Fixes #1939
> Note that 'url' isn't an available filter for `wp site list`

- features/flags.feature
- php/WP_CLI/Configurator.php
- tests/test-configurator.php
Consider a command like:
```
wp widget add rss sidebar-1 1 --url="http://wp-cli.org/feed/"
```
Historically, the `--url=<url>` parameter has been treated like a global
runtime argument, which has meant a command can't easily use it as its
own. Now, using the `WP_CLI_STRICT_ARGS_MODE` will tell WP-CLI to treat
any arguments before the command as global, and after the command as
local.
For instance:
```
WP_CLI_STRICT_ARGS_MODE=1 wp --url=wp.dev/site2 widget add rss sidebar-1 1
--url="http://wp-cli.org/feed/"
```
In this example, `--url=wp.dev/site2` is the global argument, setting
WP-CLI to run against 'site2' on a WP multisite install.
`--url="http://wp-cli.org/feed/"` is the local argument, setting the RSS
feed widget with the proper URL.
I've thought long and hard about making a breaking …
> Introduce `WP_CLI_STRICT_ARGS_MODE` for dealing with arg ambiguity

- features/flags.feature
- php/WP_CLI/Runner.php
- php/config-spec.php
We don't register new global parameters often, but this one is needed
for RESTful WP-CLI.
Fixes #3107
> Register `--http=<url>` global parameter

- features/core-download.feature
- php/commands/core.php
Fixes #3113 
- Modifies Core_Command::get_download_url() to interpret 'trunk' and 'nightly' versions
- Core_Command::get_download_url() now conforms to WordPress coding standards
- Adds support for downloading and extracting .zip files as nightly builds are own available in zip format.
- wp core download --version=trunk is only supported if ZipArchive is present.
> Support 'trunk' and 'nightly' version arguments for wp core download.

- features/search-replace.feature
- php/commands/search-replace.php
As per the discussion on issue #3140 - This pull request adds a `--include-columns=<columns>` flag to the `search-replace` command.
> Add --include-columns flag to search-replace command

- php/commands/cache.php
Related https://github.com/wp-cli/wp-cli/issues/2769
> Add examples for cache commands

- templates/install-wp-tests.sh
This PR always add a forward slash in the end to `$WP_CORE_DIR` used in  `ABSPATH` value substitution (in *wp-tests-config.php* file).
In effect by running a command like (overriding default `$WP_CORE_DIR` value):
```bash
WP_TESTS_DIR=/my/path/wordpress-tests-lib WP_CORE_DIR=/my/path/wordpress bash bin/install-wp-tests.sh wordpress_test root ''
```
the generated *wp-tests-config.php* file will contain a line like:
```php
define( 'ABSPATH', '/my/path/wordpress' );
```
without slash in the end. This causes all test units will fail with a message like:
```
PHP Fatal error:  require(): Failed opening required '/my/path/wordpresswp-includes/load.php' (include_path='.') in /my/path/wordpress/wp-settings.php on line 21
```
PS: If we are boring about double final slash we could add a statement …
> Add forward slash in the end to $WP_CORE_DIR in install-wp-tests.sh

- php/WP_CLI/Configurator.php
- php/WP_CLI/Runner.php
This lets us pass the current alias through over SSH. I wish there was a
better way to do this, but I think this is the best we have. I suppose
it will let users with lots of WordPress installs to define aliases
dynamically, instead of needing to write a file.
Fixes #3160
> Permit defining aliases at runtime

- features/scaffold.feature
- php/commands/scaffold.php
- templates/install-wp-tests.sh
- templates/plugin-gitlab.mustache
1. Adds file .gitlab-ci.yml for Gitlab CI configurations
2. Adds new option to `install-wp-tests.sh` to skip creating a database as Gitlab does not require creating a database. The variable `SKIP_DB_CREATE` defaults to `false` until set true when calling the file.
1. Tests passing for Gitlab here - [Gitlab tests](https://gitlab.com/Nikchavan/test-wp-plugin/builds/2411349#down-build-trace)
2. Travis tests are unaffected after the changes to `install-wp-tests-sh` - [Github tests](https://travis-ci.org/Nikschavan/test-wp-plugin/builds/145178414)
See #2199
> add --ci=gitlab for wp scaffold plugin-tests

- php/WP_CLI/CommandWithTranslation.php
cf. https://github.com/wp-cli/wp-cli/issues/2670#issuecomment-233898650
> missing global namespace separator in CommandWithTranslation.php

- php/WP_CLI/Runner.php
This approach was a bit hacky. Instead, a path provided as a part of
`--ssh=<host>` means the command should be ultimately executed from that
directory.
> Don't overload `--path` when path is provided in `--ssh`

- composer.json
- composer.lock
```
- Updating wp-cli/php-cli-tools (dev-master 10cfa5b => v0.11.1)
Checking out 5311a4b99103c0505db015a334be4952654d6e21
- Removing justinrainbow/json-schema (1.6.1)
- Installing justinrainbow/json-schema (2.0.5)
- Removing composer/ca-bundle (1.0.2)
- Installing composer/ca-bundle (1.0.3)
- Removing composer/composer (1.1.3)
- Installing composer/composer (1.2.0)
```
See #3095
> Restore php-cli-tools to v0.11.1; update other dependencies

- php/commands/cli.php
`## EXAMPLES` is missing in the doc of `cli cmd-dump`. So detail in this page is not as expected. http://wp-cli.org/commands/cli/cmd-dump/
> Add missing heading in doc of cli cmd-dump

- features/site.feature
- php/WP_CLI/Runner.php
> Fix backwards compat shim to only affect `wp site create

- features/core-version.feature
- php/commands/core.php
- templates/versions.mustache
> Display default core language in "wp core version --extra".

- features/media-import.feature
- php/commands/media.php
Related #3228 
* Improve example containing xargs
* In success message, wrap file name with `'`
* Update test to reflect the new change
> Doc improvement media import

- php/config-spec.php
I am not sure that is my pull-request better or not. 
But I feel we should improve help for `--ssh`.
```
$ wp help
...
--ssh=<user>[:<pass>]@<host>[:<port>]<path>
Perform operation against a remote server over SSH.
```
> Improve help of ssh

- features/option.feature
- php/commands/option.php
YAML interprets `yes` and `no` to be boolean values, which breaks the
default value for the underlying command. Instead, we need to make sure
these options are quoted. No default value is necessary because null is
an acceptable default value.
See #3209
> Fix behavior of autoload parameter for `wp option (add|update)` (v0.24.1)

- features/option.feature
- php/commands/option.php
YAML interprets `yes` and `no` to be boolean values, which breaks the
default value for the underlying command. Instead, we need to make sure
these options are quoted. No default value is necessary because null is
an acceptable default value.
See #3209
> Fix behavior of autoload parameter for `wp option (add|update)` (v0.25.0)

- features/skip-plugins.feature
- php/WP_CLI/Runner.php
Using `--skip-plugins=<slug>` should only disable that specific plugin,
not all network-activated plugins.
Also makes the tests a bit more comprehensive.
Reported in #3216
> Fix `--skip-plugins` for network-activated plugins (v0.25.0)

- features/skip-plugins.feature
- php/WP_CLI/Runner.php
Using `--skip-plugins=<slug>` should only disable that specific plugin,
not all network-activated plugins.
Also makes the tests a bit more comprehensive.
Reported in #3216
> Fix `--skip-plugins` for network-activated plugins (v0.24.1)

- features/import.feature
- php/commands/import.php
Doing so communicates the total count is of the current file, not all
files.
Fixes #2834
> Indicate current file in WXR import progress indicator

- features/core.feature
- php/commands/core.php
Multisite constants are injected based on a token. When the token can't
be found, we should let the end user know, instead of erroneously
inserting at the end of wp-config.php
Fixes #1703
Fixes #2517
> Warn when multisite constants can't be inserted into wp-config

- features/core-verify-checksums.feature
- php/commands/core.php
Core's `wp-admin/` and `wp-includes/` directories are immediately after
ABSPATH. Don't flag files inside of `wp-admin/` and `wp-includes/`
directories in plugins.
Fixes #3214
> When checking for additional files, only check core directories

- features/core-download.feature
- php/commands/core.php
Fixes #3282.
I know this is something you can easily patch yourselves, but I wanted to submit the PR in case that helps. Let me know if there's something I need to adjust before you can (maybe) merge this 😸.
> Preserve case for --version argument in core download (when it makes sense)

- php/commands/user.php
not an "ID for the object" in the docblock
> `wp user meta list` needs a user ID

- features/package-install.feature
- php/commands/package.php
Right now, older installs of WP-CLI error when trying to install a new package due to the package index url not being updated from http to https.  This fails when composer goes to query the package index over http, since `secure_http` is being set to true (I believe this is also the default now).  Some users may not know how to correct this manually, and they shouldn't really have to.
This PR performs a simple check when preparing to install a package.  If the current package index isn't found in the composer config file, then it will refresh the definition for the package index repository.
fixes #3275
> Sync package composer repository on install

- features/plugin-install.feature
- php/WP_CLI/CommandWithUpgrade.php
Ideally, we'd perform this transformation in the original unzip -> move
process. However, it's not easily possible to hook into it.
Fixes #2994
> Remove branch names from directories created for Github-based ZIPs

- ci/test.sh
Doing so ensures any undefined steps will fail the build, instead of
permitting it to pass
> Run Behat in strict mode

- features/bootstrap/support.php
- features/extra/no-mail.php
- features/steps/then.php
- features/steps/when.php
- features/user.feature
- php/commands/user.php
Email notifications should only be sent when `--send-email` is provided.
Fixes #3182
> Prevent email notifications when users are created

- features/core-update-db.feature
- php/commands/core.php
Updates messaging to ensure the message reflects whether or not
`--dry-run` has been provided.
Fixes #3345
> Ensure `wp core update-db --network --dry-run` is actually dry

- composer.json
- composer.lock
WordPress trunk is dependent on features that haven't yet been formally
released.
Broken build is #3357
See #3315
> Hack in `rmccue/requests` at latest to address a breaking build

- php/utils.php
This line causes a fatal as it tries to resolve the class as `WP_CLI\Utils\WP_CLI`.
> Correct reference of WP_CLI to use global namespace

- features/plugin-install.feature
> Add a testcase that `wp plugin install` fails with invalid proxy deets

- features/skip-themes.feature
- php/class-wp-cli.php
This gracefully lets WP-CLI use the tentative `WP_Hook` implementation
in WP 4.7. Even if `WP_Hook` gets pulled, it's better to use
`add_filter()` if it's available.
Fixes #3382
> If `add_filter()` is already available, use it in `WP_CLI::add_hook()`

- php/WP_CLI/CommandWithTranslation.php
When ran the command `wp core language update` I got the following error :
```
PHP Strict standards:  Only variables should be passed by reference in .../wp-cli/wp-cli/php/WP_CLI/CommandWithTranslation.php on line 169
PHP Stack trace:
PHP   1. {main}() .../wp-cli/wp-cli/php/boot-fs.php:0
PHP   2. include() .../wp-cli/wp-cli/php/boot-fs.php:17
PHP   3. WP_CLI\Runner->start() .../wp-cli/wp-cli/php/wp-cli.php:21
PHP   4. WP_CLI\Runner->_run_command() .../wp-cli/wp-cli/php/WP_CLI/Runner.php:906
PHP   5. WP_CLI\Runner->run_command() .../wp-cli/wp-cli/php/WP_CLI/Runner.php:319
PHP   6. WP_CLI\Dispatcher\Subcommand->invoke() .../wp-cli/wp-cli/php/WP_CLI/Runner.php:312
PHP   7. call_user_func:{.../wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php:372}() …
```
> Fix strict standard error about variable reference

- features/bootstrap/FeatureContext.php
Normally, WP-CLI pays attention to `WP_VERSION` as a part of the setup
process. This makes it easier for developers running the test suite
locally to use `WP_VERSION` too:
```
WP_VERSION=trunk behat features/skip-themes.feature
```
See #3382
> Permit running test suite with `WP_VERSION` env variable

- features/core-install.feature
- php/commands/core.php
* If the `user_login` already exists, then the new email address and
password are ignored and the existing user is reused.
* If the `user_login` doesn't exist, then a new user is created with the
provided email address and password.
Fixes #1009
> Add testcase and docs for installing core with shared user tables

- features/site-option.feature
- php/commands/site-option.php
As it turns out, site options don't support autoload, so there's less of
an opportunity for a common abstraction.
Fixes #1628
> Introduce `Site_Option_Command` for managing site options

- ci/prepare.sh
- features/bootstrap/FeatureContext.php
Regression from #3383
Before merging, verify the appropriate WP version is being used in each test run.
> Fix Exception in test suite when no `WP_VERSION` is provided

- php/WP_CLI/CommandWithTranslation.php
This makes `wp core language update` more useful to those with installed
language packs.
Fixes #2021
> Permit updating language packs even when `en_US` is set as locale

- php/commands/site.php
Builds an array of files and directories to be removed, then removes
them. This ensures `RecursiveIteratorIterator` internal index isn't
messed up as we remove files.
> Ensure the entire uploads directory is empty

- README.md
See https://github.com/wp-cli/wp-cli.github.com/pull/218
> Use a direct download link for bash completion

- features/media-regenerate.feature
- php/commands/media.php
Adds a `$current/$count` prefix to `wp media regenerate`'s progress logs.
> Add a simple progress indicator to `wp media regenerate`

- features/site.feature
- php/commands/site.php
This ensures that the correct site URL is returned when the `wpmu_new_blog` action is used to change site details.
Fixes #3415.
> Use `get_blog_details()` for the site URL when creating a new site

- features/bootstrap/FeatureContext.php
From https://github.com/wp-cli/wp-cli/pull/3377
> Ensure `ProcessRun` is loaded as a part of the test suite bootstrap

- php/commands/media.php
* Remove unnecessary `_` prefix from private methods
* Remove default argument values, because values are always passed
> Cleanup `Media_Command` methods

- php/WP_CLI/PackageManagerEventSubscriber.php
Sample output:
```
Installing package markri/wp-sec (dev-master)
Updating /home/nilambar/.wp-cli/packages/composer.json to require the package...
Using Composer to install the package...
---
Resolving dependencies through SAT
Dependency resolution completed in 0.002 seconds
Analyzed 474 packages to resolve dependencies
Analyzed 233 rules to resolve dependencies
- Installing guzzlehttp/promises (1.2.0)
- Warning: guzzlehttp/guzzle 6.2.x-dev requires guzzlehttp/promises ^1.0 -> satisfiable by guzzlehttp/promises[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.1.0, 1.2.0, 1.0.x-dev].
- Installing psr/http-message (dev-master f6561bf)
- Installing guzzlehttp/psr7 (dev-master 64862e8)
- Installing guzzlehttp/guzzle (dev-master a0d7517) …
```
> Change installing message in composer dependency

- features/cli.feature
From 9e480000ad068cd1c64f3927adabeb3687ed6209
> Drop erroneous `@github-api` label on this scenario

- features/cli.feature
- php/commands/cli.php
Skips the update check, so this both lets you roll back from `--nightly`
or reinstall an existing stable copy.
Updates docs too, which were completely incorrect.
Fixes #2942, #3260
> Use `--stable` to install or reinstall the latest stable version

- ci/behat-tags.php
- php/commands/cli.php
Reverts wp-cli/wp-cli#3428
Proxy is intermittently returning 403 and failing builds, and I don't know why.
See #3426
> Revert "Proxy Github API requests through `https://github-api.wp-cli.org`"

- features/framework.feature
- php/WP_CLI/Runner.php
- php/utils-wp.php
WordPress conveniently calls `nocache_headers()` inside of `dead_db()`,
which means we can swoop in and display the database error ourselves.
`enable_wp_debug_mode_checks` is too early, because `wp_die()` isn't yet
defined for `$wpdb` to call.
Fixes #3433
> Handle `dead_db()` error on `nocache_headers` filter

- features/aliases.feature
- php/WP_CLI/Configurator.php
- php/WP_CLI/Runner.php
When an alias is used, it should completely override user, url, path, ssh, and http.
Fixes #3444
> Don't persist `url:` in `wp-cli.yml` when alias is used

- php/WP_CLI/Runner.php
> Fix uncaught exception when `wp_mail()` is used `SERVER_NAME`

- features/db-query.feature
> Add testcase to assert `wp db query` runs before WP loads

- features/option-list.feature
- php/commands/option.php
Or, if you want to list transients, use `wp option list --transients`
Fixes #3448
> Use `--no-transients` to ignore transients when listing options

- features/plugin-install.feature
- php/WP_CLI/CommandWithUpgrade.php
If the plugin is already installed, then we should error and require the
`--force` parameter to be used.
From #3314
> Fix behavior of installing Github-based projects when already installed

- php/class-wp-cli.php
> Warn when `WP_CLI::launch()` ends up with `return_code=-1`

- features/db.feature
- features/framework.feature
- php/utils-wp.php
This gives the end user more detail when a database connection fails,
instead of a cryptic message.
Fixes #3188
> Provide more verbosity in `wp_die()` handler

- features/core-download.feature
- php/commands/core.php
> Ensure `wp core download --version=latest` produces versioned cache key

- features/framework.feature
- php/class-wp-cli.php
> Support passing arguments to `WP_CLI::do_hook()`

- features/aliases.feature
- php/WP_CLI/Runner.php
This is helpful information for the end user. If the execution output is
being passed to another system, the log can be disabled with `--quiet`
Fixes #3192
> Log the current alias when executing an alias group

- features/scaffold.feature
- php/commands/scaffold.php
- templates/phpcs.ruleset.xml
- templates/plugin-circle.mustache
- templates/plugin-travis.mustache
Installation for use in CI is essentially:
```
export PATH="$HOME/.composer/vendor/bin:$PATH"
composer global require wp-coding-standards/wpcs
phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
```
Fixes #310
> Add WordPress Coding Standards to newly-scaffolded plugins

- php/commands/media.php
After adding progress indicator from https://github.com/wp-cli/wp-cli/pull/3407 examples needs to be updated. Related https://github.com/wp-cli/wp-cli/issues/3475
> Update examples for media regenerate

- features/scaffold.feature
- php/commands/scaffold.php
Doing so avoids a second step of scaffolding plugin tests with a specific
provider.
> Support `--ci=<provider>` when directly scaffolding a plugin

- features/command.feature
- php/WP_CLI/Dispatcher/Subcommand.php
If the positional is optional, we shouldn't enforce the value to be one
of the defined options. Not passing a value is acceptable for optional
arguments.
> Only check `options` for a positional argument when a value is present

- features/media-regenerate.feature
TwentySeventeen now includes a 100x100 image size, which breaks our
tests for a custom image size.
> Update media regenerate tests to use 125x125 image size

- features/package-install.feature
- php/commands/package.php
`wp package list` will display all local packages now, not just those in
the package index
Related #2532, #2565
> Support installing a WP-CLI package based on a Git URL

- features/package-install.feature
- php/commands/package.php
For packages not listed in the package index:
```
wp package install path-to/command-directory
```
Fixes #2565
> Support installing a WP-CLI package at a local path

- features/package-install.feature
- php/WP_CLI/Extractor.php
- php/commands/core.php
- php/commands/package.php
```
$ wp package install
https://github.com/wp-cli/google-sitemap-generator-cli/archive/master.zip
$ wp package install google-sitemap-generator-cli.zip
```
Archives are extracted to `<packages-dir>/local/<package-name>`, and
installed as a path repository.
Fixes #2532
> Support for installing packages from zip archives

- features/cli-bash-completion.feature
- php/WP_CLI/Completions.php
Like following.
Thanks!
```
$ wp help 
cache            eval             network          role             super-admin 
cap              eval-file        option           scaffold         taxonomy 
cli              export           package          search-replace   term 
comment          help             plugin           server           theme 
core             import           post             shell            transient 
cron             media            post-type        sidebar          user 
db               menu             rewrite          site             widget 
```
> enables bash completion on `wp help`

- features/cli-bash-completion.feature
- features/flags.feature
- php/WP_CLI/Completions.php
When I run following
```
$ wp core[tab]
```
It should complement like following.
```
$ wp core[space]
```
And when I run following.
```
$ wp core[space][tab][tab]
```
It should complement like following.
```
$ wp core[space]
check-update        install             multisite-convert   update-db 
config              is-installed        multisite-install   verify-checksums 
download            language            update              version 
```
Thanks!
> improve bash completion

- utils/wp-cli-updatedeb.sh
Linitian will complain as this deb is a cross-release package.
`E: php-wpcli: php-script-but-no-phpX-cli-dep usr/bin/wp`
> Fix PHP-CLi dependency

- features/core-update-db.feature
- php/WP_CLI/Runner.php
Core's `wp-admin/upgrade.php` sets this constant, so we should too.
> Ensure `WP_INSTALLING` is set for `wp core update-db`

- php/commands/scaffold.php
Add `phpcs.ruleset.xml` to the `wp help scaffold plugin` and `wp help scaffold plugin-tests`.
> add `phpcs.ruleset.xml` to the help

- features/aliases.feature
- php/commands/cli.php
It's annoying to accidentally type this and get an error.
> Add `wp cli aliases` alias

- features/package-install.feature
- php/commands/package.php
> Use supplied version in package composer.json, instead of "dev-master"

- php/commands/post.php
When deleting revisions (e.g. `wp post delete $(wp post list --post_type='revision' --format=ids)`), the success message reads `Success: Trashed post {$post_id}`, which is incorrect.
> wp post delete revisions success message

- features/core.feature
- php/WP_CLI/Dispatcher/Subcommand.php
- php/commands/core.php
- php/config-spec.php
For instance:
```
wp core config --dbname=testing --dbuser=wp --prompt=dbpass <
password.txt
```
This approach lets users avoid exposing secure data in bash history.
Fixes #129
> Use `--prompt=<assoc>` to prompt for specific associative args

- templates/plugin-travis.mustache
Reverts wp-cli/wp-cli#3529
See https://github.com/travis-ci/travis-ci/issues/6842#issuecomment-259307424
> Revert "Use `dist: trusty` on Travis"

- features/core-install.feature
- php/commands/core.php
This more closely mirrors WordPress' behavior of generating a default
password for the admin user.
Fixes #3534
> Default to a randomly generated password for `--admin_password=<pass>`

- templates/install-wp-tests.sh
PHP Notice occurred in trunk. ( for WordPress 4.7 )
> Notice: /tmp/wordpress-tests-lib/includes/../data/themedir1 is not readable in /tmp/wordpress/wp-includes/theme.php on line 471
So, checkout all phpunit suite.
> Checkout data directory in install-wp-tests.sh

- php/commands/core.php
#3535 was recently done to allow for a default password to be generated using `wp core install`.  However, it does not appear to correctly install the generated password in the system, as the admin user is unable to log in after the install has completed using the randomly generated password.
I did some digging, and the problem is that in https://github.com/wp-cli/wp-cli/blob/master/php/commands/core.php#L673 the `extract` occurs with a blank value, and the subsequent Admin Password is set to the `$assoc_args` array...which has already had its values extracted.  So the blank value already in `$assoc_args['admin_password']` which is now set to `$admin_password` gets passed into `wp_install()` on line 699, instead of the randomly generated password..
The fix is to simply move the block up …
> Automatic Password generation on Install does not work

- php/commands/server.php
It seems that since #3330 `wp server` no longer loads a system installed `php.ini` (in my case `/etc/php.ini` on macOS Sierra running system PHP 5.6.25). This patch tweaks the command to use use whatever `php.ini` is set at runtime if the user has not specified one via `--config=` or `wp-cli.yml`.
> Use default php.ini when `wp server` is run without `--config=`

- php/WP_CLI/CoreUpgrader.php
Prevents a fatal error if `$package` is empty.
> In CoreUpgrader use global namespace for WP_Error

- features/comment.feature
- features/term.feature
- features/user.feature
- php/WP_CLI/Runner.php
- php/commands/comment.php
- php/commands/term.php
- php/commands/user.php
Also adds support for `wp user list --field=url`
Fixes #2070
> Deprecate `wp (term|comment) url` in favor of `wp (term|comment) list`

- php/WP_CLI/CoreUpgrader.php
- php/WP_CLI/LanguagePackUpgrader.php
See https://github.com/wp-cli/wp-cli/pull/3595#issuecomment-262598544
* Adds missing DocBlock for `download_package()`
* Adds missing brackets
* Whitespace cleanup
* Removes the declaration of a second `$temp` variable. This was introduced in https://github.com/wp-cli/wp-cli/commit/5fbcb26b8b1cca7aa29a1ac8b163b80aa9d96b2c.
> Code styling for WP_CLI\CoreUpgrader and WP_CLI\LanguagePackUpgrader

- php/WP_CLI/UpgraderSkin.php
This fixes displaying entities like `&#160;` in CLI context.
I've left the `str_replace( '&#8230;', '...',` part as is because `...` is more visible than `…` IMO.
> Use `html_entity_decode()` for decoding entities in upgrader strings

- php/WP_CLI/CommandWithMeta.php
I noticed a misspelling when using `wp network meta add`. This PR fixes it.
> Fix typo in \WP_CLI\CommandWithMeta docblocks.

- features/package-install.feature
- php/commands/package.php
This one little trick lets Composer handle WP-CLI version constraints
defined in a package's `composer.json`
Fixes #2675
> Add WP-CLI version to package manager's `composer.json`

- features/user-session.feature
- php/commands/user-session.php
Add examples for user session class.
@danielbachhuber When `destroy --all` is used, success message is like this:
`Destroyed all sessions. 0 remaining.`
I feel `0 remaining.` is redundant here as `all` is already mentioned in the earlier sentence. Thoughts?
> Add examples for user session commands

- features/core-update-db.feature
- features/rewrite.feature
- features/runcommand.feature
- php/WP_CLI/ExitException.php
- php/WP_CLI/Loggers/Execution.php
- php/class-wp-cli.php
- php/commands/cli.php
- php/commands/core.php
- php/commands/export.php
- php/commands/option.php
- php/commands/plugin.php
- php/commands/rewrite.php
- php/commands/site-option.php
- php/commands/theme.php
- php/utils.php
- tests/test-utils.php
> Introduce `WP_CLI::runcommand()`, the best way to run WP-CLI commands

- php/commands/search-replace.php
Otherwise, the base site's options table won't be matched.
> Ensure all options tables are matched in examples

- php/commands/option.php
I have also removed `## OPTIONS` from main class doc, as --format parameter is kept in each subcommands also.
> Doc improvements in option commands

- features/runcommand.feature
- php/WP_CLI/Runner.php
- php/class-wp-cli.php
Doing so increases simularity between launching a new process and
reusing an existing process.
Fixes #3620
> Apply backwards compat conversions when using the same process

- php/class-wp-cli.php
See https://wp-cli.org/docs/internal-api/wp-cli-runcommand/#notes
> Add a blank line before the list in DocBlock of `WP_CLI::runcommand()`

- composer.lock
```
- Removing symfony/yaml (v2.8.13)
- Installing symfony/yaml (v2.8.14)
- Removing symfony/filesystem (v2.8.13)
- Installing symfony/filesystem (v2.8.14)
Loading from cache
- Removing symfony/config (v2.8.13)
- Installing symfony/config (v2.8.14)
- Removing symfony/debug (v2.8.13)
- Installing symfony/debug (v2.8.14)
- Removing symfony/dependency-injection (v2.8.13)
- Installing symfony/dependency-injection (v2.8.14)
- Removing symfony/event-dispatcher (v2.8.13)
- Installing symfony/event-dispatcher (v2.8.14)
Loading from cache
- Removing symfony/polyfill-mbstring (v1.2.0)
- Installing symfony/polyfill-mbstring …
```
> Update Composer dependencies 12/5/2016

- features/core-update.feature
- php/WP_CLI/CoreUpgrader.php
- php/commands/core.php
Don't ever cache it, however.
Fixes #3643
> Support `--version=(nightly|trunk)` for `wp core update`

- features/config.feature
- php/WP_CLI/Dispatcher/Subcommand.php
The passed positionals should take precedent over defaults defined in
`wp-cli.yml`
> Fix merge behavior when positionals passed and also defined in `wp-cli.yml`

- php/commands/site.php
Props to @nathanielks for pointing this out to me—seems like it would be good to have the `site__in` param in the documentation for the `wp site list` command.
> Add documentation for hidden 'wp site list' param.

- features/scaffold-plugin-tests.feature
- features/scaffold-theme-tests.feature
- features/scaffold.feature
- php/commands/scaffold.php
Test files will be generated under the `wp-content/themes` when I made a mistake and ran a command like following.
```
$ cd wp-content/themes/twentyseventeen/
$ wp scaffold theme-tests .
Success: Created test files.
```
Then:
```
wp-content/themes
├── .travis.yml
├── bin
├── index.php
├── phpcs.ruleset.xml
├── phpunit.xml.dist
├── tests
├── twentyfifteen
├── twentyseventeen
```
Slug of the plugin/theme should be validated.
> add validation for slug of the plugin/theme

- php/class-wp-cli.php
The `PATH` can contain the path to a MySQL binary, which is important
for connecting to the correct database.
Fixes #3681
> Persist `PATH` when launching a child process

- features/site-create.feature
- php/commands/site.php
This ensures path is respected when `$base` global isn't '/'
Fixes #3673
> Replicate core logic for creating `$newdomain` and `$path`

- features/theme-install.feature
- php/WP_CLI/UpgraderSkin.php
It's a bit of a hack to put this in the upgrader feedback skin, but
there isn't a clear action to hook into.
Fixes #3674
> Ensure automatic parent theme installation uses http cacher

- features/framework.feature
- php/WP_CLI/Runner.php
The previous implementation would only assign the value to the global
variable, when the current context also needs to be considered global.
Fixes #3694
> When globalizing `wp-config.php` vars, ensure local scope is globalized

- php/commands/server.php
The default internal server docroot must be the path directory set as global parameter or in the configuration file.
> Set the path global parameter as docroot in server command

- php/WP_CLI/Configurator.php
I want to use hostname in aliases like following.
```
@example.com:
ssh: user@example.com/var/www/html
@example.jp:
ssh: user@example.jp/var/www/html
```
> Allow dot in aliases

- features/core-config.feature
- php/commands/core.php
To overwrites existing wp-config.php.
```
$ wp core config --dbname=testing --dbuser=wp --force
```
> Add `--force` option to `core config`

- php/WP_CLI/SearchReplacer.php
- tests/test-search-replace.php
When two arrays contain the same value, we want both to be replaced.
Fixes #3656
> Only skip replace when array is a reference to an existing array

- php/WP_CLI/Runner.php
WordPress 4.7 attempts to log a user in after installing. Included in
this was a change to `wp_cookie_constants()` such that it uses
`wp_guess_url()` to set the default `COOKIEHASH`, instead of an empty
string. Because CLI doesn't use cookies, we can prevent this notice by
setting `COOKIEHASH` earlier.
Fixes #3710
> Prevent error notice from `wp_guess_url()` when core isn't installed

- php/WP_CLI/SearchReplacer.php
I think this is a cleaner fix for #3656.  The cycle detection when replacing inside an object graph was almost correct before #3708.  The only issue was that `$visited_data` was passed by reference, but it should really be passed by value.
`$visited_data` is the current path into the object tree, and we are inside a cycle if the current element is the same as any of its ancestors.  This "path" should be reset when going inside a different branch of the tree, rather than having its elements accumulate over the entire replace operation.
Note: this relies on the fact that by default, PHP passes arrays by value rather than by reference, which I [did not know](http://stackoverflow.com/a/2030924) and did not expect.
> Simpler fix for search-replace reference vs value issues

- features/cache.feature
- php/commands/cache.php
WordPress' object cache treats an empty cache group as 'default'. WP-CLI
should make this behavior more explicit.
Fixes #3699
> Explicitly set default cache group as 'default'

- php/class-wp-cli.php
This fixes #3729. proc_open will inherit the parent environment if you
pass NULL for the environment parameter
(http://php.net/manual/en/function.proc-open.php). I've verified that
this works properly by testing this fix against my wp-config that
contained environment variables.
> Fix runcommand's proc_open to inherit parent environment

- php/commands/search-replace.php
This fixes #3732.
I've removed the statement in the documentation that search-replace skips the 'guid' column by default because it doesn't.
I've checked the functional tests - they are in line with the code. No changes to tests are required. The code and tests both include `guid` columns by default.  The documentation change brings the documentation in line with the code and tests.
I've done a search through the whole of the WP-CLI code for the string 'guid' - as far as I can tell nothing else needs to be modified.
As part of the original issue I also searched `php/commands/search-replace.php` for usages of `skip-columns` and I don't believe any other changes are necessary.
My only remaining question is: are the online docs at wp-cli.org, and the build-in help auto-generated? I suspect …
> Remove statement in docs that search-replace skips 'guid' column

- php/commands/site-option.php
> Remove unused/undefined autoload variables in site option command

- features/core-language.feature
- php/WP_CLI/CommandWithTranslation.php
This is needed for WordPress to report the correct language download
file.
Fixes #3747
> Pass `$wp_version` through to `translations_api()`

- php/WP_CLI/CommandWithUpgrade.php
Because `null` doesn't give us any data to display, let's assume the
error was already reported by the upgrader skin.
Fixes #3761
> Treat null result from `install_from_repo()` as an error

- php/commands/db.php
Doing so helps to mitigate database files from being web-accessible at
predictable URLs.
Fixes #3759
> Append a random hash to generated `.sql` file

- php/commands/media.php
WordPress 4.7 includes support for PDF image thumbnails, so we should
regenerate them too.
Fixes #3751
> Support 'application/pdf' for WordPress 4.7+

- features/db-export.feature
- features/db-import.feature
- php/commands/db.php
`wp import` should continue to attempt to import `{DB_NAME}.sql` when no
other value is provided
Bug introduced in #3765
> Only append random hash to `wp export` file

- features/plugin-install.feature
- php/WP_CLI/CommandWithUpgrade.php
Also fixes incorrect use of `WP_Error`
Fixes #3775
> Don't attempt to rename ZIPs uploaded to GitHub's releases page

- features/db-import.feature
- php/WP_CLI/Runner.php
This will enable `wp help db import` to be run when WordPress has been
downloaded, a `wp-config.php` has been created, but WordPress hasn't yet
been installed.
> Run help for `wp db *` set of commands at same point as command

- features/media-import.feature
- php/commands/media.php
- Addresses #3721
- This has 3 related parts, each isolated in their own commit
- Does not (yet) include any tests
1. When a local file is not found, continue to the next file (if there is one) instead of breaking - this matches similar behavior of other errors that allow the command to keep going and try with the following images.
1. Checks the return value of `download_url()` to see if it is a `WP_Error` - this is another thing that bit me when that function returned an error and `wp-cli` didn't really make it clear why the command failed.
1. With the `--porcelain` flag, make sure we return a non-zero exit code if there are any errors.
> Improve media import error handling

- README.md
This avoids partial insecure warning on https://wp-cli.org/ .
I've updated all the outbound links to HTTPS as well after verify all the sites has a working HTTPS version (the only exception is `http://drush.ws/` which I replace it with an URL to GitHub).
> HTTPS everywhere on README.md

- ci/prepare.sh
Uses the snippet from the Travis CI Docs found here:
[https://docs.travis-ci.com/user/languages/php#Disabling-preinstalled-PHP-extensions](https://docs.travis-ci.com/user/languages/php#Disabling-preinstalled-PHP-extensions)
Fixes #3812
> Remove XDebug from PHP runtime within Travis CI environment.

- features/media-regenerate.feature
- php/commands/media.php
This is a fix suggested for issue #3817, passing down the `$fullsizepath` from `process_regeneration()`.
The behat test requires a test PDF, "minimal-us-letter.pdf", to be uploaded, which I've uploaded to core trac [minimal-us-letter.pdf](https://core.trac.wordpress.org/raw-attachment/ticket/39875/minimal-us-letter.pdf), and temporarily uses "localhost" instead of "wp-cli.org" to run.
> Issues 3817 Existing PDF previews not deleted on media regenerate.

- features/db-import.feature
- php/commands/db.php
Hi again,
this pull requests includes a fix for issue #3820.
By default, calling `wp db import` will disable auto-commit and (unique and foreign) key checks, and hence speed up the import (for larger dumps). When using `STDIN`, this is not easily possible (but also not necessary).
In order to somehow _force_ the old behavior, I introduced a new flag `skip-optimization`.
First tests with a (very simple!) database dump showed this is effective.
In case you want to test this yourself, the [dump is here](https://github.com/wp-cli/wp-cli/files/793126/data.sql.gz). It includes only a single table, `data`, with a single column that is used as primary key, and 50,000 rows.
I ran **10 imports** each with the new and with the forced old behavior.
Skipping the optimization resulted in times …
> Improve DB import. #3820

- features/plugin-install.feature
- php/WP_CLI/CommandWithUpgrade.php
In regards to https://github.com/wp-cli/wp-cli/pull/3821
Without adding any additional flag, expected behavior of installing from a raw github source url should be exactly the same as installing from a source url on the releases page. This change reflects that.
> dont attempt to rename ZIPs being installed from raw github sources

- php/WP_CLI/REPL.php
> Fix typo in `$prompt` private property.
