wp-cli/wp-cli

features/search-replace.feature, php/commands/search-replace.php
=> Rename `--all-tables` to `--all-tables-with-prefix` for clarity

features/scaffold.feature, php/commands/scaffold.php
=> Add `--sassify` option to `wp scaffold _s`

features/scaffold.feature, php/commands/scaffold.php, templates/post_type.mustache
=> Rename `--icon` argument to `--dashicon` for clarity

php/commands/db.php
=> Use `mysql` with `--no-auto-rehash` for perf boost

php/export/class-wp-export-wxr-formatter.php
=> Wrap comment meta values in CDATA on export

composer.json
See https://github.com/wp-cli/php-cli-tools/releases/tag/v0.10.4
=> Update php-cli-tools to v0.10.4

php/export/class-wp-export-wxr-formatter.php
=> Update export of authors

features/core.feature, php/WP_CLI/CommandWithTranslation.php, php/WP_CLI/CommandWithUpgrade.php
=> Add `wp core language update` command and Behat tests

features/scaffold.feature, php/commands/scaffold.php
=> Add scaffold theme enable network

features/scaffold.feature, php/commands/scaffold.php
mu-plugins is one use case, and plugins within themes is another
See #1083
=> Scaffold plugin and plugin tests to arbitrary directory

php/commands/post.php
=> Document how to delete all posts in the trash

features/post.feature, php/commands/post.php
=> Fix language when deleting a trashed post

php/WP_CLI/Dispatcher/Subcommand.php
=> Add `after_invoke` hook for any post-execution tasks

features/scaffold.feature, php/commands/scaffold.php, templates/plugin-gruntfile.mustache, templates/plugin-packages.mustache
=> Add default Gruntfile to plugin scaffold with two helpful tasks

features/site.feature, php/commands/site.php
=> Support filtering by site value in `wp site list`

features/core.feature, php/commands/core.php
=> Helpful error message when user provides invalid version or locale

features/cron.feature, php/commands/cron.php
=> Fix broken conditional for `<next-run>` argument

features/site.feature, php/commands/site.php
=> Rename `wp site not-spam` to `wp site unspam`

features/user.feature, php/commands/user.php
=> On multisite, run user creation through validation rules

templates/plugin-packages.mustache
`npm install` fails on the name
=> Use plugin slug in plugin's packages.json

templates/plugin-gruntfile.mustache
It's copy-paste leftovers
See #1748
=> Don't require remapify in default plugin Gruntfile

utils/wp-cli-updatedeb.sh
=> With the new VERSION file version string detection is only possible

php/utils.php
=> Support `Requests` installed to parent project in `http_request()`

php/commands/plugin.php
=> Document one-liner for listing all plugins in a network

features/flags.feature, php/wp-settings-cli.php
=> Exit with a message when --url parameter is used with a inexistent site url

php/commands/cli.php
=> Remove redundant `@subcommand` tag

utils/wp-completion.bash
=> Simple hack to fix bash completion

features/core.feature
=> Update core tests to reflect new minor WP version

features/roles.feature, php/commands/role.php
=> Create a new role from another role with `--clone=<role>`

php/commands/plugin.php
=> Document how to delete inactive plugins

php/WP_CLI/CommandWithMeta.php
The docs for `get()` were missing and there was a typo in `delete()`.
=> Update documentation for CommandWithMeta

features/cli.feature, php/commands/cli.php, utils/make-phar.php
=> Introduce `wp cli update --nightly` for updating to nightly release

composer.json
=> Lock php-cli-tools to v0.10.5

features/upgradables.feature, php/WP_CLI/CommandWithUpgrade.php
=> Use proper key for theme update table

features/config.feature, php/WP_CLI/Runner.php
=> Ignore commented `define('DOMAIN_CURRENT_SITE')` statements in wp-config

features/comment.feature, php/commands/comment.php
=> Introduce `wp comment recount` for recalculating `comment_count`

php/class-wp-cli.php
See https://wordpress.slack.com/archives/cli/p1441220169000129
=> Clarify expected behavior for `WP_CLI::run_command()`

features/scaffold.feature, php/commands/scaffold.php
=> Clarify it's an invalid plugin slug; `--dir` is checked elsewhere

features/core.feature, php/class-wp-cli.php, php/commands/core.php
=> Use `wp core update-db --network` to upgrade databases across network

features/framework.feature, php/wp-settings-cli.php
=> Ensure wp-includes/session.php is loaded in bootstrap

features/upgradables.feature, php/WP_CLI/CommandWithUpgrade.php
=> Use proper key for theme update table (for v0.20.1)

features/command.feature, php/WP_CLI/Runner.php
=> Let user know when invalid subcommand has a valid parent command

php/WP_CLI/Runner.php, php/commands/post.php
=> Deprecate `wp post url` in favor of `wp post list --field=url`

features/core.feature
=> Add test case for custom base path for multisite

php/utils.php
=> Sniff out the custom vendor path if we're a part of a Composer project

php/WP_CLI/CommandWithDBObject.php, php/commands/post.php
=> Use `--defer-term-counting` to recalculate term count in batch for perf

features/option.feature, php/commands/option.php
=> `--autoload=(yes|no)` support for `update option`

php/class-wp-cli.php, php/commands/cli.php
=> Exhaust all possible options when finding PHP binary

php/commands/help.php
=> Paginate help output on Windows using `more`

php/commands/core.php
and don't report success if any file isn't copied to current directory
=> When extracting code files, check if file is writable before try to copy

php/wp-settings-cli.php
https://core.trac.wordpress.org/changeset/34851 added WPINC/embed-functions.php
This'll work for the build svn repo. Develop will need a version bump.
=> Include new WP file (embed-functions.php)

templates/install-wp-tests.sh
=> Use proper tests checkout for WP_VERSION=latest

features/user.feature
This part of the codebase is pretty mature. We don't really need to
worry about this breaking.
=> Remove test because it fails sporadically

.travis.yml, php/WP_CLI/SynopsisParser.php
=> Add support for PHP 7

templates/install-wp-tests.sh
=> Use tagged versions of the WordPress develop test suite (v0.20.0)

php/wp-settings-cli.php
=> Ensure oEmbed controller is loaded in bootstrap

.travis.yml, ci/prepare.sh
It'll be helpful to see what our compatibility is like
See #1842
=> Test PHP 7 and 5.6 against WordPress trunk

features/taxonomy.feature, php/commands/taxonomy.php
=> Add `wp taxonomy list` command

php/WP_CLI/Iterators/Table.php
=> Use `esc_sql()` and `$wpdb->prepare()` instead of deprecated method

.travis.yml, features/comment.feature, features/rewrite.feature, features/term.feature, features/user.feature, php/commands/media.php, php/commands/term.php
We need to make sure WP-CLI is fully-compatible with WP 4.4
Related #2150
=> Don't allow failures against WordPress trunk

.travis.yml, ci/prepare.sh, features/comment.feature, features/rewrite.feature, features/term.feature, features/user.feature, php/commands/media.php, php/commands/term.php, php/wp-settings-cli.php
=> Compatibility fixes for WordPress 4.4 (release-0-20-3)

php/WP_CLI/CommandWithUpgrade.php
=> Allow remote plugin files without `.zip` in filename

templates/install-package-tests.sh
Otherwise, we'll just download the redirect
=> Make sure we download redirected version of nightly

php/utils-wp.php, php/wp-settings-cli.php
=> Include more files in `wp-settings-cli.php` in prep for WP 4.4 (v0.20.4)

features/search-replace.feature, php/commands/search-replace.php
=> Properly escape quotes in SQL search and replace

features/search-replace.feature, php/commands/search-replace.php
=> Support wildcards / globs in table names with `wp search-replace`

php/commands/cache.php, php/commands/search-replace.php, php/utils-wp.php
=> Let users know to flush their persistent object cache after s/r

features/search-replace.feature, php/commands/search-replace.php
Let's help save developers from themselves.
Fixes #2067
=> Bail early on search-replace when terms are the same

features/media.feature, php/commands/media.php
If only a single image was regenerated, the message will be:
> An error occurred with image regeneration.
If multiple images were regenerated, the message will be:
> An error occurred regenerating one or more images.
Fixes #1540
=> Provide a more helpful message when image regeneration fails

php/commands/core.php
=> Globalize `$wp_version` in a couple places we need it as a global

composer.json
There's something broken in v2.8.0
=> Lock symfony to v2.7.x

features/db-table.feature, features/search-replace.feature, php/commands/db.php, php/commands/search-replace.php, php/utils-wp.php
Abstracts table name getting to `WP_CLI\Utils\wp_get_table_names()`
Fixes #1225
=> Add wildcard tables, `--all-tables-with-prefix`, and `--format=csv` support to `wp db tables`

features/scaffold.feature, php/commands/scaffold.php, templates/.travis.mustache
Fixes #423
Hey guys. Hope you don't mind me picking this up and having a go. Over at [Delicious Brains](https://deliciousbrains.com/) we each have a "contrib" day once a month and I'm considering contributing to WP-CLI when I can (because I love it and use it all the time).
=> Parse plugin readme.txt to find WP versions to test for plugin-tests scaffold

features/menu.feature, php/commands/menu.php
=> Properly update menu sub-item parent when parent is deleted

.travis.yml, php/WP_CLI/CommandWithUpgrade.php, php/WP_CLI/Runner.php, php/wp-settings-cli.php
=> Increase minimum supported WP version to 3.7.11

features/post-meta.feature, php/WP_CLI/CommandWithMeta.php
=> Delete all post or user meta with `--all` flag

php/commands/post.php
=> Document CSV values for `wp post list --post__in=<ids>`

features/scaffold.feature, php/commands/scaffold.php, templates/plugin-gitignore.mustache
=> Add .gitignore to plugin scaffold

features/export.feature, php/commands/export.php
=> Support custom export filename formats with `--filename_format=`

php/commands/search-replace.php
On large datasets, running `LIKE` twice per 1000 rows is far less
efficient than running `LIKE` once to get keys for all rows to operate
on, and `SELECT` to get the corresponding values for each row.
On small datasets, this change will have a negligible impact.
For a post meta table of ~3.5 million rows with 75610 affected
records, this change improves execution time from 734.926s to 225.509s
Fixes #2244
=> Don't use table iterator when running search / replace with PHP

.travis.yml
This reverts commit c1edf396ceef8f68a89abea17c2cd4f821234356.
=> Revert "Permit failures on trunk"

features/post-meta.feature, php/WP_CLI/Formatter.php
=> Properly check for null values on objects

features/media-import.feature, php/commands/media.php
=> Use host instead of scheme to determine whether a file is remote or local

php/commands/widget.php
=> Fix widget list command example

composer.json, composer.lock
* Don't unnecessarily clobber `%` characters passed through colorize https://github.com/wp-cli/php-cli-tools/pull/91
=> Switch php-cli-tools to `dev-master`

features/site.feature, features/steps/given.php
=> Support for testing multisite with subdomains

ci/behat-tags.php, features/scaffold.feature, php/commands/scaffold.php, utils/make-phar.php
=> Include ci/behat-tags.php in `scaffold package-tests`

features/plugin-update.feature, php/commands/plugin.php
=> Updating plugin with invalid version shouldn't delete the plugin

php/commands/export.php
=> Document how users can export a random subset of their content

composer.lock
See https://github.com/wp-cli/php-cli-tools/pull/93
Fixes #1736
=> php-cli-tools: a more impossible placeholder pattern

composer.json, composer.lock
=> Lock `php-cli-tools` to 0.11.0

features/command.feature, php/WP_CLI/Dispatcher/CommandFactory.php, php/class-wp-cli.php
=> Register an arbitrary function, closure, or method as a command

templates/.travis.package.yml
* Disable noisy email notifications by default.
* Prevent duplicate builds on pull requests.
* Use two space indentation instead of four.
=> Improve .travis.yml for package tests

.travis.yml, ci/prepare.sh
=> Introduce a dedicated job for testing Git clone installation

features/export.feature, php/export/class-wp-export-query.php
=> Respect `--skip_comments` flag for `wp export`

php/commands/cron.php
Props @fjarrett
From https://github.com/wp-cli/wp-cli/issues/2306#issuecomment-178186118
=> Add example of how to run all due cron events

features/term-meta.feature, php/commands/term.php
=> Manage term meta with `wp term meta`

features/bootstrap/support.php, features/formatter.feature, features/steps/then.php, php/WP_CLI/Formatter.php, php/class-wp-cli.php, php/commands/comment.php, php/commands/core.php, php/commands/cron.php, php/commands/menu.php, php/commands/package.php, php/commands/plugin.php, php/commands/post-type.php, php/commands/post.php, php/commands/rewrite.php, php/commands/role.php, php/commands/sidebar.php, php/commands/site.php, php/commands/taxonomy.php, php/commands/term.php, php/commands/theme.php, php/commands/user.php, php/commands/widget.php
=> Support `--format=yaml` when displaying structured data

php/class-wp-cli.php, php/utils.php
=> First pass at better documentation of public APIs

php/WP_CLI/Runner.php
=> Add debug output for package loading

.editorconfig
=> Make PHP look leaner on GitHub

php/class-wp-cli.php, php/utils.php
=> Annotate public internal APIs with categories

php/utils.php
=> Add an inline code example for `Utils\format_items()`

php/class-wp-cli.php
=> Mark `WP_CLI::add_command()` as public; improve docs

features/command.feature, php/WP_CLI/Dispatcher/CompositeCommand.php, php/class-wp-cli.php
=> Register `$longdesc` from supplied arguments

php/class-wp-cli.php
=> Add `WP_CLI::add_hook()` and `WP_CLI::do_hook()` to internal API

php/class-wp-cli.php, php/utils.php
=> Internal APIs: WP_CLI::get_php_binary(), Utils\http_request(), WP_CLI::confirm()

features/cli-info.feature, php/WP_CLI/Runner.php, php/commands/cli.php
=> Add package directory path to `wp cli info`

php/commands/package.php
This will make it easier for users to become contributors.
See #1564
=> Prefer Git (and other VCS) when installing packages

php/commands/package.php
=> `wp package browse` should list all available versions

php/commands/package.php
=> Clean up `wp package` PHPDoc; support `--format=ids`

composer.json, composer.lock
=> Lock php-cli-tools to v0.11.1

templates/bootstrap.mustache
File and functions should be documented.
=> Add documentation to bootstrap template

php/commands/search-replace.php
See https://github.com/wp-cli/wp-cli/issues/2575#issuecomment-198931973
=> Clarify the `wp_blogs` table also needs to be replaced on MS

php/WP_CLI/Runner.php, php/class-wp-cli.php
See
https://github.com/wp-cli/scaffold-package-command/commit/7dc321c864893e5d2afda17471cd2a664a2968b5
=> Mark `WP_CLI::run_command()` public; clarify `::launch_self()`

php/WP_CLI/REPL.php, php/commands/shell.php
=> Add newline to wp shell's prompt

php/commands/package.php
=> Fix DateTime fatal when getting composer

README.md
=> Link to the documentation portal from the readme

php/commands/db.php
=> Expand upon `wp db *` docs; explicitly mark methods as public

features/term-recount.feature, php/commands/comment.php, php/commands/term.php
=> Add `term recount` command

php/commands/term.php
=> Clean up docs for `wp term recount`

php/WP_CLI/DocParser.php, tests/test-doc-parser.php
=> Fix greedy parsing of arg/param args

composer.lock
```
- Removing symfony/yaml (v2.8.3)
- Installing symfony/yaml (v2.8.4)
- Removing symfony/filesystem (v2.8.3)
- Installing symfony/filesystem (v2.8.4)
- Removing symfony/config (v2.8.3)
- Installing symfony/config (v2.8.4)
- Removing symfony/dependency-injection (v2.8.3)
- Installing symfony/dependency-injection (v2.8.4)
- Removing symfony/event-dispatcher (v2.8.3)
- Installing symfony/event-dispatcher (v2.8.4)
- Removing symfony/translation (v2.8.3)
- Installing symfony/translation (v2.8.4)
- Removing symfony/process (v2.8.3)
- Installing symfony/process (v2.8.4) …
```
=> Update Composer dependencies to their latest

php/commands/site.php
Doing so requires a bit of custom code.
=> Mention that custom database tables won't be emptied

features/cron.feature, php/commands/cron.php
=> Use `--due-now` to run all cron events due or overdue

features/cron.feature, php/commands/cron.php
=> Add field filtering in cron event list command

features/command.feature, php/WP_CLI/Dispatcher/Subcommand.php
=> Ensure `before_invoke` and `after_invoke` are called on top-level commands too

.travis.yml, composer.json, composer.lock, features/core-check-update.feature, php/WP_CLI/ComposerIO.php, php/commands/package.php
=> Use Composer ^1.0.0 (for v0.23.1)

composer.json, composer.lock
=> Use a better next significant release operator; update to Composer 1.0.2

features/core.feature, php/commands/core.php
=> Document how to handle WP in subdirectory; add test to doc behavior

php/commands/media.php
From http://stackoverflow.com/questions/4651437/how-to-set-a-variable-equal-to-the-output-from-a-command-in-bash
=> Document how to import an attachment and assign multiple thumbnails

php/commands/export.php
=> Prevent runaway memory usage by clearing object cache after each file

php/commands/core.php
=> Mention multisite rewrite rules will need to be added manually.

php/commands/package.php
More secure! More better!
Fixes #2585
=> Interact with the Package Index over SSL

features/scaffold.feature, php/commands/scaffold.php, templates/plugin-distignore.mustache
=> Rename to `.distignore` to imply use for generic distibution

php/WP_CLI/Runner.php, php/config-spec.php
=> Use `--ssh=<host>[:<path>]` to run commands on remote servers

php/commands/db.php
#2769
Example of `wp db reset` with the confirmation `--yes`
=> Example: db reset

php/commands/search-replace.php
#2769
**Search/replace production to development url (multisite compatible)**
Example code/script I'm using every day to search-replace from production to locally, regardless of it being a multisite or not.
=> Example: search-replace

php/commands/core.php
=> Example: core update-db

php/commands/core.php
=> Example: core version

php/commands/core.php
=> Example: core verify-checksums

php/commands/cli.php
#2769 add example to cli update command document.
=> Example: cli update

php/commands/cli.php
=> Example: cli version

php/commands/taxonomy.php
=> Example: taxonomy get

php/commands/option.php
=> Example: option get

php/commands/plugin.php
=> Example: plugin list

php/commands/core.php
=> Example: core multisite-convert

php/commands/core.php
=> Example: core multisite-install

php/commands/transient.php
add example for transient delete-all command
=> add example for transient delete-all command

php/commands/transient.php
=> Add example for transient delete-expired

php/commands/transient.php
=> Add example for transient get command

php/commands/transient.php
=> Add example for transient type command

php/commands/transient.php
=> Add example for transient set command

php/commands/transient.php
=> fix doc in transient get command

php/commands/theme.php
=> Example: theme delete

php/commands/theme.php
=> Example: theme get

php/commands/theme.php
=> Example: theme activate

php/commands/theme.php
=> Example: theme search

php/commands/theme.php
=> Example: theme status

php/commands/transient.php
=> Examples for transient main class

php/commands/transient.php
=> Example: transient delete

php/commands/sidebar.php
=> Example: sidebar main class

php/commands/sidebar.php
=> Example: sidebar list

php/commands/rewrite.php
=> Example: rewrite flush

php/commands/rewrite.php
=> Example: rewrite structure

php/commands/rewrite.php
=> Examples for rewrite commands

php/commands/rewrite.php
=> Example: rewrite list

php/commands/role.php
=> Example: role exists

php/commands/role.php
=> Examples for role main class

php/commands/role.php
=> Example: role list

php/commands/role.php
=> Example: role reset

php/commands/role.php
=> Example: role delete

php/commands/role.php
=> Example: role create

php/commands/widget.php
=> Example: widget list

php/commands/widget.php
=> Example: widget add

php/commands/cap.php
=> Example cap main

php/commands/cap.php
=> Example: cap remove

php/commands/widget.php
=> Example: widget update

php/commands/widget.php
=> Examples for Widget main class

php/commands/cap.php
=> Example: cap list

php/commands/widget.php
=> Example: widget move

php/commands/widget.php
=> Example: widget deactivate

php/commands/cap.php
=> Example: cap add

php/commands/widget.php
=> Example: widget delete

php/commands/term.php
=> Example: term generate

php/wp-settings-cli.php
=> Conditionally require `WP_Site_Query` and `WP_Term_Query` for WP 4.6 compat

php/commands/term.php
=> Example: term update

php/commands/media.php
=> Example: media regenerate

php/commands/term.php
=> Example: term list

php/commands/term.php
=> Example: term get

php/commands/term.php
=> Example: term url

php/commands/term.php
=> Example: term recount

php/commands/term.php
=> Example: term meta

php/commands/term.php
=> Example: term create

php/commands/taxonomy.php
=> Example: taxonomy list

php/commands/media.php
=> Example: media import

php/commands/plugin.php
=> Example: plugin status

php/commands/media.php
=> Examples for media main class

php/commands/option.php
=> Example: option delete

php/commands/option.php
=> Example: option add

php/commands/term.php
=> Example: term delete

php/commands/comment.php
=> Example: comment url

php/commands/comment.php
=> Example: comment exists

features/roles.feature, php/commands/cap.php
=> Support `--format=<format>` argument for `wp cap list`

php/commands/comment.php
=> Example: comment status

php/commands/comment.php
=> Example: comment recount

php/commands/comment.php
=> Example: comment count

php/commands/comment.php
=> Example: comment unapprove

php/commands/comment.php
=> Example: comment approve

php/commands/export.php
=> Example: export command

php/commands/comment.php
=> Example: comment untrash

php/commands/comment.php
=> Example: comment delete

php/commands/comment.php
=> Example: comment trash

php/commands/comment.php
=> Example: comment get

php/commands/comment.php
=> Example: comment generate

php/commands/comment.php
=> Example: comment update

php/commands/comment.php
=> Example: comment create

php/commands/comment.php
=> Example: comment spam

php/commands/theme.php
=> Example theme enable

features/scaffold.feature
=> Add more tests for scaffold child-theme

features/term.feature, php/commands/term.php
=> Accept multiple term IDs in term url

php/commands/comment.php
=> Example: comment unspam

php/commands/cli.php
=> Add Example: cli check-update & cli param-dump, #2770

php/commands/menu.php
=> Example: menu create

php/commands/menu.php
=> Examples for menu main class

php/commands/menu.php
=> Example: menu list

php/commands/menu.php
=> Example: menu location remove

php/commands/menu.php
=> Example: menu delete

features/comment.feature, php/commands/comment.php
=> Comment ID issue in comment spam and other subcommands

php/commands/menu.php
=> Example: menu location assign

php/commands/menu.php
=> Example: menu location list

php/commands/term.php
=> Examples for term main class

php/commands/comment.php
=> Examples for comment meta

php/commands/comment.php
=> Examples for comment main

php/commands/comment.php
=> Example: comment list

php/commands/menu.php
=> Add examples for Menu Item main class

php/commands/menu.php
=> Examples for menu location commands

php/commands/db.php
=> Add examples for db commands

php/commands/cron.php
=> Add examples for cron commands

php/WP_CLI/CommandWithTranslation.php
=> Prevent pass by reference PHP notice

php/commands/cron.php
=> Example: cron schedule

php/commands/cli.php
=> Add examples for subcommands of cli

php/commands/cron.php
=> Examples for cron event main command class

php/commands/cron.php
=> Example for main cron command

php/commands/post-type.php
=> Examples for post-type commands

php/commands/option.php
=> Add examples for option commands

php/commands/db.php
=> Add examples for main db class

php/commands/plugin.php
=> Add examples for plugin commands

php/commands/network.php
=> Example: network meta

php/commands/post.php
=> Add examples for post commands

php/commands/site.php
=> Add examples for site commands

php/commands/package.php
=> Add examples for package commands

php/commands/core.php
=> Add examples for core commands

features/skip-plugins.feature
See #2278
Originally from #2663
=> Add more explicit tests for skip-plugins feature

php/commands/core.php
=> Examples for core main class

php/commands/scaffold.php
=> Add examples for scaffold commands

php/wp-settings-cli.php
=> Load plugin.php earlier in wp-settings-cli.php for 4.6 compat.

php/commands/user.php
=> User commands doc improvement

features/super-admin.feature, php/commands/super-admin.php
=> Introduce format parameter for super-admin list command

php/commands/search-replace.php
=> Examples for search-replace command

php/commands/user.php
=> Add examples for User main class

php/commands/comment.php
=> Improve format parameter doc in comment commands

php/commands/term.php
=> Improve format parameter docs in term commands

php/commands/role.php
=> Improve format parameter doc in role command

php/commands/post-type.php
=> Improve format parameter in post-type commands

php/commands/transient.php
=> Improve doc for format parameter in transient command

php/commands/taxonomy.php
=> Improve docs in taxonomy commands

features/user.feature, php/commands/user.php
=> Add format parameter in user list-caps

php/commands/theme.php
=> Improving docs for theme and theme mods commands

php/commands/sidebar.php
=> Default fields improvement in sidebar commands

features/aliases.feature
=> Add explicit test for inheritance behavior

features/cli-info.feature, php/commands/cli.php
=> Improve format parameter doc in cli commands

php/commands/server.php
=> Improve doc in server command

php/WP_CLI/Runner.php
=> Escape ssh arguments to ensure they're quoted; include pretty version

php/commands/shell.php
=> Example: shell command

php/commands/option.php
=> Improve doc in option commands

php/commands/core.php
=> Example: core is-installed

features/comment-recount.feature, php/commands/comment.php
=> Comment: add trailing period in messages

features/cli.feature, php/commands/cli.php
=> CLI: add trailing period in messages

features/theme-mod.feature, php/commands/theme.php
=> Theme: add trailing period to theme commands messages

php/commands/transient.php
=> Transient: add trailing period in command messages

features/cron.feature, php/commands/cron.php
=> Cron: add trailing period in command messages

php/commands/widget.php
=> Improve default doc for widget commands

features/widget.feature, php/commands/widget.php
=> Add trailing period in widget commands messages

composer.lock, utils/make-phar.php
```
- Removing symfony/yaml (v2.7.11)
- Installing symfony/yaml (v2.8.7)
- Removing symfony/filesystem (v2.7.11)
- Installing symfony/filesystem (v2.8.7)
- Removing symfony/config (v2.7.11)
- Installing symfony/config (v2.8.7)
- Removing symfony/dependency-injection (v2.7.11)
- Installing symfony/dependency-injection (v2.8.7)
- Removing symfony/event-dispatcher (v2.7.11)
- Installing symfony/event-dispatcher (v2.8.7)
- Installing symfony/polyfill-mbstring (v1.2.0)
Loading from cache
- Removing symfony/translation (v2.7.11)
- Installing symfony/translation (v2.8.7)
- Installing …
```
=> Update Composer dependencies to latest

php/commands/search-replace.php
=> Search-replace: add missing trailing period in command messages

features/term-recount.feature, php/commands/term.php
=> Term: add missing trailing period in command messages

features/roles.feature, php/commands/role.php
=> Role: add missing trailing period in command messages

php/commands/rewrite.php
=> Improve doc in rewrite commands

php/commands/menu.php
=> Menu: add missing trailing period in command message

php/commands/user.php
=> User: add missing trailing period in command messages

php/WP_CLI/Runner.php
Example:
```
192.168.50.10:2222:/srv/www/wordpress-develop.dev/src
```
See #2754
=> Support for defining port with `--ssh`

php/WP_CLI/Runner.php
See https://github.com/wp-cli/wp-cli/issues/2754#issuecomment-226278013
=> Use a more URL-like format for `--ssh`

features/framework.feature, php/WP_CLI/Runner.php, php/wp-settings-cli.php
=> Restore `wp_maintenance()` to `wp-settings-cli.php` for feature parity

php/commands/option.php
=> Introduce field param in option list

features/db.feature, php/commands/db.php
=> Add porcelain flag in db export

php/commands/media.php
=> Media: add missing trailing period in command messages

features/export.feature, php/commands/export.php
=> Export: add missing trailing period in command messages

php/WP_CLI/Runner.php, php/utils.php, tests/test-utils.php
Includes unit tests for expected behavior
See #2754
=> Introduce `WP_CLI\Utils\parse_ssh_url()` for parsing SSH URLs

php/commands/db.php
=> Improved messages in db commands

php/commands/import.php
=> Add example for import and other doc improvement

features/theme.feature, php/commands/theme.php
=> Fix PHP notice in theme status

php/commands/export.php
=> Doc improvement in export command

php/commands/menu.php
=> Doc improvement in menu commands

features/formatter.feature, php/WP_CLI/Formatter.php
=> Ensure YAML formatter handles objects and `--fields=<fields>` arg

php/commands/plugin.php
=> Improve default format in command doc in plugin file

features/sidebar.feature, php/commands/sidebar.php
=> Add ids for format parameter in sidebar list

features/comment.feature
Mr WordPress is now some wapuu business
=> Fix builds on WordPress trunk

features/site-empty.feature, features/site.feature, php/commands/site.php
=> Improve doc and message in site commands

features/site.feature, php/commands/site.php
=> Allow ids value in format parameter in site list

features/aliases.feature, php/commands/cli.php
=> Introduce `wp cli alias` for listing available aliases

CONTRIBUTING.md, README.md
=> Improve our CONTRIBUTING.md with greater detail

features/scaffold.feature, php/commands/scaffold.php
=> Improving doc and message in scaffold commands

features/aliases.feature, php/WP_CLI/Runner.php
This permits running a WP-CLI command against all registered aliases
See #2039
=> Register a magic `@all` alias

features/post.feature, php/commands/post.php
=> Improving doc in post commands

features/command.feature, php/WP_CLI/Dispatcher/Subcommand.php, php/commands/post.php
Bug introduced in 05ff88bf66c7276fc95cd80f9fa8f85547c55b2f
Fixes #3103
Related #3029
=> Respect wp-cli.yml default values when applying argument defaults

features/config.feature, php/WP_CLI/Dispatcher/Subcommand.php
=> Appropriately handle positional arguments defined in wp-cli.yml

CONTRIBUTING.md
=> #2766 - Improving our documentation section of CONTRIBUTING.md

ci/prepare.sh
=> Use `wp core download --version=trunk` in Travis

php/WP_CLI/Configurator.php
=> Support `--http=<url>` in an alias

php/WP_CLI/Runner.php
=> Permit managing packages and running `wp cli info` over SSH

features/roles.feature, php/commands/role.php
=> Add verbosity to wp role reset

php/commands/scaffold.php
=> Add doc for generated files in scaffold plugin command

php/commands/core.php
=> Improving doc and default value in core commands

features/roles.feature, php/commands/role.php
=> Role reset, custom role not affected verbosity add

README.md
It's better to show than tell.
=> Include example command in README.md

php/commands/network.php, php/commands/post.php, php/commands/term.php
These won't be rendered in the appropriate place.
=> Remove ## OPTIONS from meta classes

features/post.feature, php/commands/post.php
=> Make sure WordPress receives the slashed data it expects

features/term.feature, php/commands/term.php
=> Pass slashed data for term commands

features/user.feature, php/commands/user.php
=> Pass slashed data for creating and updating users

features/comment.feature, php/commands/comment.php
=> Pass slashed data for creating and updating comments

features/site.feature, php/commands/site.php
=> Pass slashed site title in site create command

php/utils.php
=> adds default value to  in Utils\mustache_render

features/media-import.feature, php/commands/media.php
=> Pass slashed data for importing media

features/super-admin.feature, php/commands/super-admin.php
Message improvement Super admin commands. Related https://github.com/wp-cli/wp-cli/issues/2848
=> Super admin message improvement

php/commands/package.php
See https://github.com/wp-cli/wp-cli/issues/2837
=> Doc improvement in package commands

features/cron.feature, php/commands/cron.php
=> Update success message for cron event run

features/search-replace.feature, php/commands/search-replace.php
Related https://github.com/wp-cli/wp-cli/issues/3103
=> Update search replace dry run message

features/widget.feature, php/commands/widget.php
Related https://github.com/wp-cli/wp-cli/issues/3103
=> Show no of widgets in message in widget delete command

php/commands/cli.php
=> Add example for cli completions command

features/cron.feature, php/commands/cron.php
=> Fix issue of not listing duplicate cron events

features/aliases.feature, php/WP_CLI/Runner.php
=> Register informational label for `@all`, instead of listing all aliases

php/WP_CLI/Runner.php, php/class-wp-cli.php
Aka `add_action()` without needing access to `add_action()`.
=> Introduce `WP_CLI::add_wp_hook()`

features/widget.feature, php/commands/widget.php
=> Update success message for widget deactivate

utils/wp-cli-updatedeb.sh
=> Support PHP 7 on Debian-based systems

features/theme-mod.feature, php/commands/theme.php
=> Update success message in theme mod remove

php/commands/cli.php
=> Add example for cli alias

features/menu.feature, php/commands/menu.php
=> Update success message in menu item delete

features/menu.feature, php/commands/menu.php
=> Update success message in menu delete command

php/commands/option.php
=> Improve example in option list

php/commands/post.php
=> Improve doc for post generate command

php/commands/term.php
=> Improve doc for term generate command

php/commands/plugin.php
=> Improve example in plugin list command

README.md
Ref: https://github.com/eddiezane/lunchy/issues/57#issuecomment-121173592
=> Add zsh tab completion info

php/WP_CLI/CommandWithTranslation.php
* `wp core language list`
* `wp core language install`
* `wp core language update`
* `wp core language activate`
* `wp core language uninstall`
See #2769
=> improve doc for `wp core language`

features/theme.feature
=> Fix xargs param in theme status test

php/commands/comment.php
=> Improve doc for comment generate command

php/commands/user.php
=> Improve doc in user generate command

php/commands/db.php
=> Add command description in db import

README.md
=> Syntax highlight for README

composer.lock
```
- Removing mustache/mustache (v2.10.0)
- Installing mustache/mustache (v2.11.1)
- Removing symfony/finder (v2.8.8)
- Installing symfony/finder (v2.8.9)
- Removing symfony/yaml (v2.8.8)
- Installing symfony/yaml (v2.8.9)
- Removing symfony/filesystem (v2.8.8)
- Installing symfony/filesystem (v2.8.9)
- Removing symfony/config (v2.8.8)
- Installing symfony/config (v2.8.9)
- Removing symfony/console (v2.8.8)
- Installing symfony/console (v2.8.9)
- Removing symfony/dependency-injection (v2.8.8)
- Installing symfony/dependency-injection (v2.8.9)
- Removing …
```
=> Update dependencies to latest

php/commands/core.php
=> Catch exceptions thrown by `RecursiveDirectoryIterator`

php/commands/core.php
=> Include adequate vertical spacing around inserted constants

features/command.feature, php/WP_CLI/Dispatcher/CommandFactory.php
=> Properly support registering an instantiated object as a command

features/post-meta.feature, php/WP_CLI/CommandWithMeta.php
=> Passed slashed data in meta

php/commands/db.php
OPTIMIZE_TABLE is really OPTIMIZE TABLE
=> Typo in db optimize and in db repair's comment

php/commands/comment-meta.php, php/commands/comment.php
=> Move `wp comment meta` class into its own file

features/theme.feature, php/commands/theme.php
=> Install parent theme when installing a child theme

php/WP_CLI/Iterators/Table.php, php/commands/search-replace.php
See http://dev.mysql.com/doc/refman/5.7/en/identifiers.html
Fixes #3317
=> Ensure tables are quoted to support all permitted characters

php/commands/server.php
=> Support passing custom `.ini` file when launching the server

features/db-check.feature, features/db.feature, php/commands/db.php
=> Implement `wp db check`

features/db.feature
We were playing with an empty database.
Complements #3332
=> DB Operations tests

features/comment-meta.feature, php/WP_CLI/CommandWithMeta.php
See https://github.com/wp-cli/wp-cli/issues/1745#issuecomment-241582863
=> Add testcase for adding meta with JSON-formatted input

features/db.feature, php/commands/db.php
=> Pass extra arguments through, a la `wp db export`

features/bootstrap/FeatureContext.php, features/package-install.feature
=> Test install of package with dependency; clean up package dir between tests

features/package-install.feature, php/commands/package.php
=> Remove a package's dependencies when the package is removed

php/commands/search-replace.php
=> Fix error notice when `export_insert_size` isn't defined

features/scaffold.feature, templates/plugin-circle.mustache
Circle is using Trusty by default on new projects
=> Use PHP version specific to Trusty

features/help.feature, php/commands/help.php, templates/man.mustache
=> Display alias in man page

php/commands/search-replace.php
=> If SQL regex triggers an error for some reason, fail back to PHP
