wp-cli/wp-cli

features/transient.feature
php/WP_CLI/Runner.php
php/commands/transient.php

Consolidate wp transient delete commands

---

php/commands/package.php

This will permit the package to actually be uninstalled.

Properly assign `$composer_backup` when uninstalling

---

features/roles.feature
php/commands/role.php

Doc improvements in roles commands

Doc improvements in roles commands

---

features/package-install.feature
php/WP_CLI/PackageManagerEventSubscriber.php
php/commands/package.php

Related https://github.com/wp-cli/wp-cli/issues/3417

Update installing message for package install command

---

ci/behat-tags.php
ci/test.sh
php/commands/cli.php

Proxy Github API requests through `https://github-api.wp-cli.org`

---

templates/install-wp-tests.sh

if there is already a database, the script throws an error. Thereupon I inserted a check for existance and drop that database if necessary.

Dropping database if one exists

---

templates/install-wp-tests.sh

Revert "Dropping database if one exists"

---

features/option-list.feature
php/commands/option.php

Fix https://github.com/wp-cli/wp-cli/issues/3453

Introduce parameter in option list to negate search

---

templates/taxonomy.mustache

Those are the values that are defined in the CODEX as well.

updated the labels to match the ones for tags

---

templates/plugin-circle.mustache

See https://circleci.com/docs/build-image-precise/#databases

Use correct default user for MySQL on CircleCI

---

templates/plugin-travis.mustache

Use the latest version of PHPUnit on Travis, depending on PHP version

---

php/commands/media.php

Add more example for media regenerate.
Fix https://github.com/wp-cli/wp-cli/issues/3469

Add more example for media regenerate

---

features/cli-bash-completion.feature
php/WP_CLI/Completions.php

When SSH alias exists, it enables bash completion.

Enables bash completion when ssh alias exists in the command

---

features/core-config.feature
features/db.feature
templates/wp-config.mustache

We don't have to copy ugliness.

Proper coding style for wp-config

---

php/commands/user.php

Include a note specific to deleting users on multisite

---

features/formatter.feature

Add test case for formatting CSV with RTL language

---

features/cli.feature
php/commands/cli.php

Verify release hash when updating

---

php/commands/db.php

Clarify docs in the `wp db *` set of commands

---

php/commands/cli.php

Clarify docs in the `wp cli *` set of commands

---

php/commands/cache.php

Clarify docs in the `wp cache *` set of commands

---

templates/plugin-travis.mustache

Use `dist: trusty` on Travis

---

.travis.yml

Reverts wp-cli/wp-cli#3280
See https://github.com/travis-ci/travis-ci/issues/6842#issuecomment-259307424

Revert "Try Trusty on Travis"

---

features/package-install.feature
features/package-update.feature
php/commands/package.php

Add a basic command to update packages

---

php/commands/rewrite.php

Clarify docs in the `wp rewrite *` set of commands

---

php/commands/option.php

Clarify docs in the `wp option *` set of commands

---

php/commands/comment.php

Clarify docs in the `wp comment *` set of commands

---

php/commands/core.php

Clarify docs in the `wp core *` set of commands

---

php/commands/cron.php

Clarify docs in the `wp cron *` set of commands

---

php/commands/export.php

Clarify docs in the `wp export` command

---

php/commands/eval.php

Drop duplicate header doc

---

php/commands/theme.php

Clarify docs for the `wp theme *` set of commands

---

php/commands/widget.php

Clarify docs for the `wp widget *` set of commands

---

php/WP_CLI/CommandWithTerms.php

Function was added in WP 3.6, and WP 3.7 is WP-CLI's minimum supported
version.

Remove unnecessary `wp_remove_object_terms()` private method

---

php/WP_CLI/CommandWithTerms.php
php/commands/post-term.php
php/commands/user-term.php

Clarify docs on `wp (post|user) term *` set of commands

---

php/commands/shell.php

Clarify docs for `wp shell`

---

php/commands/role.php

Clarify docs for the `wp role *` set of commands

---

php/commands/search-replace.php

Clarify docs in `wp search-replace`

---

php/commands/term.php

Clarify docs for `wp term *` set of commands

---

php/commands/server.php

Clarify docs for `wp server`

---

php/commands/user.php

Update docs for `wp user *` set of commands

---

php/commands/transient.php

Clarify docs for `wp transient *` set of commands

---

php/commands/site.php

Clarify docs in `wp site *` set of commands

---

php/commands/plugin.php

Clarify docs for `wp plugin *` set of commands

---

php/WP_CLI/CommandWithTranslation.php

Clarify docs for `wp core language *` set of commands

---

php/commands/super-admin.php

Clarify docs for `wp super-admin *` set of commands

---

php/commands/post.php

Clarify docs for `wp post *` set of commands

---

php/commands/media.php

Clarify docs for `wp media *` set of commands

---

php/commands/import.php

Clarify docs for `wp import`

---

php/commands/post-type.php
php/commands/taxonomy.php

Clarify docs for `wp (post-type|taxonomy) *` set of commands

---

README.md
php/WP_CLI/Runner.php

Don't require `--allow-root` with `cli update`; clarify docs

---

ci/prepare.sh

Related: https://github.com/wp-cli/wp-cli/pull/3578

add default value to $WP_CLI_BIN_DIR

---

features/super-admin.feature
php/commands/super-admin.php

Use return code 1 when one or more super admins fails to add

---

features/menu-item.feature
php/commands/menu-item.php

Use return code 1 when one or more menu items fails to delete

---

features/menu.feature
php/commands/menu.php

Use return code 1 when one or more menus fails to delete

---

features/term.feature
php/commands/term.php

Use return code 1 when one or more terms fail to delete

---

features/widget-reset.feature
features/widget.feature
php/commands/widget.php

Use return code 1 when management of 1 or more widgets fails

---

features/media-import.feature
features/media-regenerate.feature
features/menu-item.feature
features/menu.feature
features/plugin-activate.feature
features/plugin-deactivate.feature
features/plugin-delete.feature
features/plugin-install.feature
features/plugin-toggle.feature
features/plugin-uninstall.feature
features/plugin.feature
features/term.feature
features/theme-delete.feature
features/theme-install.feature
features/theme.feature
features/upgradables.feature
features/widget.feature
php/WP_CLI/CommandWithUpgrade.php
php/commands/media.php
php/commands/menu-item.php
php/commands/menu.php
php/commands/plugin.php
php/commands/term.php
php/commands/theme.php
php/commands/widget.php
php/utils.php

A helper function for reporting the results of the same operation
against multiple resources.
Fixes #3577 
Fixes #2002
Fixes #427

Introduce `WP_CLI\Utils\report_batch_operation_results()`

---

README.md

Link to Shell Friends in the README

---

features/core-language.feature
php/WP_CLI/CommandWithTranslation.php
php/WP_CLI/LanguagePackUpgrader.php

Cache language packs

---

features/package-update.feature
php/commands/package.php

When listing packages, indicate when one has an update available

---

php/commands/package.php

Display `update_version` instead of `description` for installed packages

---

features/runcommand.feature
php/class-wp-cli.php

Persist runtime arguments when launching a new process

---

php/commands/site-option.php

Emphasizes the difference between "site option" and "option".

Improve docs on the "site option" command. Addresses #3530

---

php/class-wp-cli.php

Fix "PHP Notice:  Undefined variable: key in phar:///home/travis/build/miya0001/wp-themeception/wp-cli-nightly.phar/php/class-wp-cli.php on line 1004"

fix undefined variable

---

php/utils-wp.php

```
$ wp cache type
W3TC apc
```
Fixes #3628

Detect W3 Total Cache object cache

---

features/search-replace.feature
php/WP_CLI/SearchReplacer.php
php/commands/search-replace.php

Support passing modifiers to regex search-replace

---

.travis.yml
features/core-check-update.feature

Update test suite for WordPress 4.7

---

README.md

Update version in `wp --info` example

---

features/core-update-db.feature
php/commands/core.php

Update `wpmu_upgrade_site` for all networks, not just current

---

php/commands/core.php

It took me long minutes to understand.
+adding a line break to improve readability

Point out where core update goes

---

composer.json

https://gemnasium.com/github.com/wp-cli/wp-cli

update composer to 1.2

---

php/commands/plugin.php

Plugin update from a remote zip file example

---

composer.lock

```
- Removing symfony/yaml (v2.8.14)
- Installing symfony/yaml (v2.8.15)
Loading from cache
- Removing symfony/filesystem (v2.8.14)
- Installing symfony/filesystem (v2.8.15)
Loading from cache
- Removing symfony/config (v2.8.14)
- Installing symfony/config (v2.8.15)
- Removing symfony/debug (v2.8.14)
- Installing symfony/debug (v2.8.15)
Loading from cache
- Removing symfony/dependency-injection (v2.8.14)
- Installing symfony/dependency-injection (v2.8.15)
- Removing symfony/event-dispatcher (v2.8.14)
- Installing symfony/event-dispatcher (v2.8.15)
Loading from cache
- Removing symfony/translation (v2.8.14)
- Installing symfony/translation (v2.8.15) …
```

Update Composer dependencies (12/20/16)

---

php/commands/core.php

Mention update lock behavior in core update docs

---

features/plugin-install.feature
php/class-wp-cli.php

Ensure paths aren't backslashed when destination folder already exists

---

composer.lock
php/WP_CLI/PackageManagerEventSubscriber.php

```
- Removing justinrainbow/json-schema (2.0.5)
- Installing justinrainbow/json-schema (4.1.0)
- Removing composer/composer (1.2.4)
- Installing composer/composer (1.3.0)
```

Update Composer dependencies (12/29/16)

---

features/core-verify-checksums.feature
features/core.feature
features/steps/given.php

This is more useful than using `sed`

Introduce a Behat step for replacing a string in a file

---

composer.lock

```
- Removing composer/composer (1.3.0)
- Installing composer/composer (1.3.1)
```

Update Composer dependencies (1/9/2017)

---

php/commands/user.php

Fix the user delete example in the documentation

---

features/scaffold.feature
php/commands/scaffold.php

Added the check as suggested and tested in local dev. Not sure if you want a test or two added? I'm new to testing and not sure what you have set up.
Also, not sure you if you want a more specific error here to help people out?
Fixes #3723

Add check for invalid theme slug in wp scaffold _s

---

templates/plugin-travis.mustache

See #1577 and https://docs.travis-ci.com/user/migrating-from-legacy/

Opt-in to container-based infrastructure for plugin Travis CI template config

---

features/comment-list.feature
features/post.feature
php/WP_CLI/CommandWithDBObject.php
php/commands/comment.php
php/commands/post.php
php/commands/user.php

Use `process_csv_arguments_to_arrays()` to process `__` CSV into arrays

---

templates/plugin-travis.mustache

Support PHP 7.1 and PHPUnit 5.7 when scaffolding `.travis.yml`

---

features/site-option.feature
php/commands/site-option.php

Add `--site_id=<id>` filter to `wp site option list`

---

templates/plugin-gitlab.mustache

update gitlab ci template to run phpcs tests

---

php/commands/search-replace.php

Update docs with search-replace regex example and note.

---

composer.lock

```
- Removing symfony/yaml (v2.8.15)
- Installing symfony/yaml (v2.8.16)
- Removing symfony/filesystem (v2.8.15)
- Installing symfony/filesystem (v2.8.16)
- Removing symfony/config (v2.8.15)
- Installing symfony/config (v2.8.16)
- Removing symfony/debug (v2.8.15)
- Installing symfony/debug (v2.8.16)
- Removing symfony/dependency-injection (v2.8.15)
- Installing symfony/dependency-injection (v2.8.16)
- Removing symfony/event-dispatcher (v2.8.15)
- Installing symfony/event-dispatcher (v2.8.16)
- Removing symfony/translation (v2.8.15)
- Installing symfony/translation (v2.8.16) …
```

Update Composer dependencies (1/30/2017)

---

features/db-tables.feature
php/utils-wp.php

Escape prefix when listing all tables with prefix

---

features/plugin.feature
php/WP_CLI/CommandWithUpgrade.php

Display correct error when plugin update fails to update plugins

---

composer.json
composer.lock

```
- Removing symfony/finder (v2.8.16)
- Installing symfony/finder (v2.8.17)
Loading from cache
- Removing symfony/yaml (v2.8.16)
- Installing symfony/yaml (v2.8.17)
- Removing symfony/filesystem (v2.8.16)
- Installing symfony/filesystem (v2.8.17)
Loading from cache
- Removing symfony/config (v2.8.16)
- Installing symfony/config (v2.8.17)
- Removing symfony/debug (v2.8.16)
- Installing symfony/debug (v2.8.17)
- Removing symfony/console (v2.8.16)
- Installing symfony/console (v2.8.17)
- Removing symfony/dependency-injection (v2.8.16)
- Installing symfony/dependency-injection (v2.8.17)
- Removing …
```

Update Composer dependencies (2/15/2017)

---

features/bootstrap/FeatureContext.php
features/steps/given.php
features/steps/then.php

Issue3832: behat: save verb with regex wrong, missing version checks, needs remote dbhost support

---

php/WP_CLI/PackageManagerEventSubscriber.php

The `Event` class is not used in that file.

Remove unneeded `Composer\EventDispatcher\Event` import.

---

LICENSE

Adapt license header so GitHub picks it up

---

composer.lock

```
- Removing mustangostang/spyc (0.6.1)
- Installing mustangostang/spyc (0.6.2)
- Removing phpunit/php-timer (1.0.8)
- Installing phpunit/php-timer (1.0.9)
```

Update Composer dependencies (2/27/2017)

---

php/WP_CLI/CommandWithUpgrade.php
php/WP_CLI/Extractor.php
php/WP_CLI/Runner.php
php/commands/media.php
php/commands/plugin.php
php/commands/scaffold.php
php/utils.php

Introduce `WP_CLI\Utils\basename()` for locale-independent basename()

---

composer.json
composer.lock

Note: This commit includes additional changes because Composer has changed the timestamp format for the lock file.
Fixes #3842

Require roave security advisories

---

composer.lock

```
Package operations: 0 installs, 14 updates, 0 removals
- Updating symfony/yaml (v2.8.17 => v2.8.18): Loading from cache
- Updating symfony/filesystem (v2.8.17 => v2.8.18): Loading from cache
- Updating symfony/config (v2.8.17 => v2.8.18): Loading from cache
- Updating symfony/debug (v2.8.17 => v2.8.18): Loading from cache
- Updating symfony/dependency-injection (v2.8.17 => v2.8.18): Loading from cache
- Updating symfony/event-dispatcher (v2.8.17 => v2.8.18): Loading from cache
- Updating symfony/translation (v2.8.17 => v2.8.18): Loading from cache
- Updating symfony/process (v2.8.17 => v2.8.18): Loading from cache
- Updating symfony/finder (v2.8.17 => v2.8.18): Loading from cache
- …
```

Update Composer dependencies (3/10/2017)

---

features/rewrite.feature
php/commands/rewrite.php

Warn user when managing rewrite rules while skipping plugins/themes

---

ci/test.sh

Run the fastest testsuite first.

---

composer.lock

```
Package operations: 0 installs, 4 updates, 0 removals
- Updating wp-cli/server-command (v1.0.0 => v1.0.1):  Checking out 7d65b76420
- Updating seld/cli-prompt (1.0.2 => 1.0.3): Downloading (100%)
- Updating justinrainbow/json-schema (5.1.0 => 5.2.0): Downloading (100%)
```

Update Composer dependencies (2017-03-30)

---

php/utils.php
tests/test-utils.php

In `assoc_args_to_str`, support an array of `--require=<file>`

---

composer.lock

```
Package operations: 0 installs, 3 updates, 0 removals
- Updating wp-cli/scaffold-command (v1.0.0 => v1.0.1):  Checking out 9307ef7077
- Updating wp-cli/media-command (v1.0.0 => v1.0.1):  Checking out e175cdd673
- Updating wp-cli/extension-command (v1.0.0 => v1.0.1):  Checking out 0337a1ec7f
```

Update Composer dependencies (2017-04-19)

---

features/cli.feature

Make test platform agnostic by removing all spaces.

---

composer.lock

```
- Updating wp-cli/scaffold-command (v1.0.1 => v1.0.2):  Checking out 482f2bf2d1
```

Update Composer dependencies (2017-04-28)

---

php/class-wp-cli.php

Make sure that arguments passed to hooks are stored and always passed to the callbacks.

---

features/bootstrap/FeatureContext.php

See https://github.com/wp-cli/db-command/issues/10

Use `/usr/bin/env mysql` instead of `mysql`

---

composer.lock
features/runcommand.feature

```
Package operations: 0 installs, 12 updates, 0 removals
- Updating symfony/filesystem (v2.8.19 => v2.8.20):  Checking out dc40154e26
- Updating symfony/debug (v2.8.19 => v2.8.20):  Checking out 344f50ce82
- Updating symfony/process (v2.8.19 => v2.8.20):  Checking out aff35fb3de
- Updating symfony/yaml (v2.8.19 => v2.8.20):	 Checking out 93ccdde79f
- Updating symfony/translation (v2.8.19 => v2.8.20):	Checking out 32b7c0bffc
- Updating symfony/finder (v2.8.19 => v2.8.20):  Checking out 16d55394b3
- Updating symfony/event-dispatcher (v2.8.19 => v2.8.20):  Checking out 7fc8e2b411
- Updating symfony/dependency-injection (v2.8.19 => v2.8.20):	 Checking out e1c722dfe4
- Updating …
```

Update Composer dependencies (2017-05-03)

---

.github/ISSUE_TEMPLATE

Update `.github/ISSUE_TEMPLATE` to mention sub projects

---

php/boot-fs.php
php/wp-cli.php

Set `WP_CLI_VENDOR_DIR` for both Composer and Phar installs

---

php/WP_CLI/Dispatcher/CommandExecutionLog.php
php/WP_CLI/Dispatcher/CommandFactory.php
php/WP_CLI/Dispatcher/Subcommand.php
php/class-wp-cli.php

This data will help us better understand our users and how they make use of WP-CLI
See #3886

Generate and send anon usage data

---

composer.lock

```
- Updating wp-cli/config-command (v1.0.0 => v1.1.0):	Checking out cf7da88a8c
```

Update Composer dependencies (2017-05-10)

---

composer.json
composer.lock

Fixes #3304, #3635, #3305, #3609
Fixes #3941

Enable Symfony 3.0 components

---

composer.lock

Update Composer dependencies (2017-05-15)

---

composer.lock

```
- Updating justinrainbow/json-schema (5.2.0 => 5.2.1):  Checking out 429be236f2
```

Update Composer dependencies (2017-05-17)

---

composer.lock

```
- Updating composer/composer (1.4.1 => 1.4.2):  Checking out 489e09ee6c
```

Update Composer dependencies (2017-05-19)

---

php/WP_CLI/Bootstrap/DefineProtectedCommands.php

See https://github.com/wp-cli/package-command/issues/10

Add `package *` commands to the list of protected commands.

---

composer.lock

Update Composer dependencies (2017-05-26)

---

features/bootstrap/FeatureContext.php
features/steps/then.php

Issue https://github.com/wp-cli/core-command/issues/4
Port features stuff from https://github.com/wp-cli/core-command/pull/15

Add {WP_VERSION-version-latest} variables.

---

features/aliases.feature
php/WP_CLI/Runner.php
php/utils.php

Provide a suggestion when an invalid alias is provided

---

composer.lock

```
Package operations: 0 installs, 32 updates, 0 removals
- Updating symfony/filesystem (v2.8.20 => v2.8.21):  Checking out 19c11158da
- Updating symfony/debug (v2.8.20 => v2.8.21):  Checking out 344f50ce82
- Updating symfony/process (v2.8.20 => v2.8.21):  Checking out d54232f568
- Updating wp-cli/cron-command (v1.0.0 => v1.0.1):  Checking out 1cf8564c0c
- Updating symfony/yaml (v2.8.20 => v2.8.21):	 Checking out 93ccdde79f
- Updating symfony/translation (v2.8.20 => v2.8.21):	Checking out 32b7c0bffc
- Updating symfony/finder (v2.8.20 => v2.8.21):  Checking out b058a6f0cb
- Updating symfony/event-dispatcher (v2.8.20 => v2.8.21):  Checking out 7fc8e2b411
- Updating …
```

Update Composer dependencies (2017-05-30)

---

features/command.feature
php/WP_CLI/Bootstrap/RegisterDeferredCommands.php
php/WP_CLI/Runner.php
php/class-wp-cli.php

Register deferred commands immediately before finding command to run

---

php/utils.php
tests/test-utils.php

Add WP_CLI\Utils::force_env_on_nix_systems() and use in run_mysq_command().

---

composer.json
composer.lock

See https://github.com/wp-cli/wp-cli/pull/4140#issuecomment-306930718

Remove `pyrech/composer-changelogs` as a dependency

---

composer.lock

```
- Updating symfony/filesystem (v2.8.21 => v2.8.22):  Checking out 19c11158da
- Updating symfony/debug (v2.8.21 => v2.8.22):  Checking out 8470d77011
- Updating symfony/process (v2.8.21 => v2.8.22):  Checking out d54232f568
- Updating symfony/yaml (v2.8.21 => v2.8.22):	 Checking out 4c29dec8d4
- Updating symfony/translation (v2.8.21 => v2.8.22):	Checking out 14db4cc117
- Updating symfony/finder (v2.8.21 => v2.8.22):  Checking out 4f4e848110
- Updating symfony/event-dispatcher (v2.8.21 => v2.8.22):  Checking out 1377400fd6
- Updating symfony/dependency-injection (v2.8.21 => v2.8.22):	 Checking out b4a4b8f6ae
- Updating symfony/console (v2.8.21 => v2.8.22): …
```

Update Composer dependencies (2017-06-09)

---

composer.lock

```
- Updating wp-cli/extension-command (v1.1.0 => v1.1.1):  Checking out 8489bc23aa
- Updating symfony/polyfill-mbstring (v1.3.0 => v1.4.0):  Checking out f29dca382a
```

Update Composer dependencies (2017-06-12)

---

composer.lock

```
- Updating seld/jsonlint (1.6.0 => 1.6.1):  Checking out 50d63f2858
- Updating wp-cli/media-command (v1.0.2 => v1.0.3):  Checking out dfa3b80a8d
```

Update Composer dependencies (2017-06-19)

---

composer.lock

```
- Updating wp-cli/php-cli-tools (v0.11.2 => v0.11.3):	 Checking out 09075e5a5b
- Updating wp-cli/config-command (v1.1.1 => v1.1.2):	Checking out 3d812504a4
```

Update Composer dependencies (2017-06-21)

---

README.md

* Minor formatting and edit changes.
* Use new make.wordpress.org and developer.wordpress.org URLs

One last round of edits to the README

---

composer.lock

Update Composer dependencies (2017-06-23)

---

composer.lock

```
- Updating wp-cli/search-replace-command (v1.0.1 => v1.0.2):	Checking out bb99b41e3b
- Updating wp-cli/entity-command (v1.0.2 => v1.0.3):	Checking out 5f92520106
```

Update Composer dependencies (2017-06-30)

---

utils/contrib-list.php

It'll be around for a while, and there are ongoing changes

Calculate contributors to the website too

---

composer.lock

```
- Updating symfony/filesystem (v2.8.22 => v2.8.23):  Checking out b8c9c18eac
- Updating symfony/debug (v2.8.22 => v2.8.23):  Checking out 8470d77011
- Updating symfony/process (v2.8.22 => v2.8.23):  Checking out 57e52a0a6a
- Updating symfony/yaml (v2.8.22 => v2.8.23):	 Checking out 4c29dec8d4
- Updating symfony/translation (v2.8.22 => v2.8.23):	Checking out a89af885b8
- Updating symfony/finder (v2.8.22 => v2.8.23):  Checking out 4f4e848110
- Updating symfony/event-dispatcher (v2.8.22 => v2.8.23):  Checking out 1377400fd6
- Updating symfony/dependency-injection (v2.8.22 => v2.8.23):	 Checking out 66d2e25226
- Updating symfony/console (v2.8.22 => v2.8.23): …
```

Update Composer dependencies (2017-07-05)

---

php/WP_CLI/Formatter.php

Fix output in json format in case of error while encoding

---

php/commands/src/CLI_Command.php

Fix http_request() args in CLI_Command::get_updates().

---

composer.lock

```
- Updating symfony/debug (v2.8.23 => v2.8.24):  Checking out 8470d77011
- Updating symfony/filesystem (v2.8.23 => v2.8.24):  Checking out b8c9c18eac
- Updating symfony/process (v2.8.23 => v2.8.24):  Checking out 57e52a0a6a
- Updating wp-cli/config-command (v1.1.2 => v1.1.3):	Checking out 8c043f9312
- Updating symfony/yaml (v2.8.23 => v2.8.24):	 Checking out 4c29dec8d4
- Updating symfony/translation (v2.8.23 => v2.8.24):	Checking out a89af885b8
- Updating symfony/finder (v2.8.23 => v2.8.24):  Checking out 4f4e848110
- Updating symfony/event-dispatcher (v2.8.23 => v2.8.24):  Checking out 1377400fd6
- Updating symfony/dependency-injection (v2.8.23 => …
```

Update Composer dependencies (2017-07-07)

---

features/config.feature
features/flags.feature
features/framework.feature
php/WP_CLI/Runner.php

Covers each permutation of the configuration scenario.
Fixes #4134
Fixes #4015

Display a more helpful error message when site cannot be found

---

composer.lock

```
- Updating mustache/mustache (v2.11.1 => v2.12.0):  Checking out fe8fe72e9d
```

Update Composer dependencies (2017-07-12)

---

composer.lock

Update Composer dependencies (2017-07-14)

---

utils/wp-cli-rpm.spec
utils/wp-cli-updaterpm.sh

1. Download the binary
1. Replace version placeholder in spec file
1. Create man page
1. Build the package
1. Run linter
I am not sure it is very rpm-ish.

Experimental RPM packaging

---

utils/wp-cli-updaterpm.sh

- Add failover to alternative RPM check if rpmlint doesn't exist.
- Snag the RPM name that is written so we aren't looking at all RPMs in the noarch dir.

Update wp-cli-updaterpm.sh to support failover RPM check method.

---

composer.lock

```
- Updating wp-cli/autoload-splitter (v0.1.3 => v0.1.4): Downloading (100%)
```

Update Composer dependencies (2017-07-31)

---

composer.json
composer.lock
features/bootstrap.feature
features/bootstrap/FeatureContext.php
features/steps/given.php
features/steps/then.php

Related to https://github.com/wp-cli/wp-cli/pull/4139 and https://github.com/wp-cli/autoload-splitter/pull/6

 New test : Composer stack with both WordPress and wp-cli as dependencies and a custom vendor directory

---

php/WP_CLI/SynopsisParser.php
tests/test-synopsis.php

See https://wordpress.slack.com/archives/C02RP4T41/p1501767957536331
Related #4159

Support numbers in command argument definition

---

composer.lock

```
- Updating wp-cli/php-cli-tools (v0.11.5 => v0.11.6):	 Checking out d2a4e2eca9
```

Update Composer dependencies (2017-08-04)

---

composer.lock

```
Package operations: 0 installs, 22 updates, 0 removals
- Updating wp-cli/cache-command (v1.0.1 => v1.0.2): Downloading (100%)
- Updating wp-cli/checksum-command (v1.0.1 => v1.0.2): Downloading (100%)
- Updating wp-cli/config-command (v1.1.3 => v1.1.4):	Checking out ca83ade8fb
- Updating wp-cli/core-command (v1.0.1 => v1.0.2): Downloading (100%)
- Updating wp-cli/cron-command (v1.0.1 => v1.0.2):  Checking out 92114b695a
- Updating wp-cli/widget-command (v1.0.1 => v1.0.2): Downloading (100%)
- Updating wp-cli/super-admin-command (v1.0.1 => v1.0.2):  Checking out b650836d13
- Updating composer/composer (1.4.2 => 1.4.3):  Checking out 62c17fdf79
- Updating wp-cli/shell-command (v1.0.1 => v1.0.2):  Checking out …
```

Update Composer dependencies (2017-08-07)

---

composer.lock

```
- Updating composer/composer (1.4.3 => 1.5.0):  Checking out 6f3310c762
```

Update Composer dependencies (2017-08-09)

---

utils/wp-cli-updatedeb.sh

Necessary for #4276
@danielbachhuber Please merge it.

Made deb script Travis compatible

---

composer.lock

```
- Updating composer/composer (1.5.0 => 1.5.1):  Checking out d60a1ff0cb
```

Update Composer dependencies (2017-08-11)

---

features/command.feature
features/flags.feature
features/help.feature
php/WP_CLI/Runner.php
php/commands/help.php
php/utils-wp.php

See https://github.com/wp-cli/wp-cli/pull/4291#issuecomment-322402505
Originally #4265

Revert #4266 and #4285 because of additional bugs

---

php/WP_CLI/Iterators/Transform.php

Corrected "Aplies" to "Applies"

GH#4306 Corrected spelling

---

composer.lock

```
- Updating symfony/polyfill-mbstring (v1.4.0 => v1.5.0):  Checking out 7c8fae0ac1
```

Update Composer dependencies (2017-08-18)

---

composer.lock

```
- Updating wp-cli/scaffold-command (v1.0.5 => v1.0.6):  Checking out decd726496
```

Update Composer dependencies (2017-08-23)

---

php/WP_CLI/Dispatcher/Subcommand.php

Avoid PHP notice for --prompt edge cases

---

composer.lock

```
- Updating wp-cli/server-command (v1.0.5 => v1.0.6):	Checking out ce93df07c3
```

Update Composer dependencies (2017-09-08)

---

php/WP_CLI/Extractor.php

CS: Fix case for `array` keyword

---

php/WP_CLI/Bootstrap/DefineProtectedCommands.php

Corrected Spelling

---

composer.lock

```
- Updating composer/ca-bundle (1.0.7 => 1.0.8):  Checking out 9dd73a0395
- Updating composer/composer (1.5.1 => 1.5.2):  Checking out c639623fa2
```

Update Composer dependencies (2017-09-13)

---

php/utils.php
tests/test-utils.php

Issue https://github.com/wp-cli/wp-cli/issues/4353
Adds `glob_brace()` utils function that simulates a `glob()` with the `GLOB_BRACE` flag set, for compatibility with Linuxes (Alpine) uslng the `musl` libc library.

Add glob_brace utils function for Alpine Linux compat, issue 4353

---

php/commands/help.php
php/commands/src/CLI_Command.php
phpcs.xml.dist

See #4058.
This PR, and all of the following CS-related PRs, all rely on the "Remove exclusions..." commit.

CS for php/commands/*

---

php/WP_CLI/Bootstrap/DefineProtectedCommands.php
phpcs.xml.dist

CS for php/WP_CLI/Bootstrap/*

---

php/WP_CLI/Iterators/CSV.php
php/WP_CLI/Iterators/Query.php
php/WP_CLI/Iterators/Table.php
phpcs.xml.dist

CS for php/WP_CLI/Iterators/*

---

php/WP_CLI/Loggers/Execution.php
php/WP_CLI/Loggers/Regular.php
phpcs.xml.dist

CS for php/WP_CLI/Loggers/*

---

php/WP_CLI/Dispatcher/CommandFactory.php
php/WP_CLI/Dispatcher/CompositeCommand.php
php/WP_CLI/Dispatcher/RootCommand.php
php/WP_CLI/Dispatcher/Subcommand.php
phpcs.xml.dist

CS for php/WP_CLI/Dispatcher/*

---

php/WP_CLI/Extractor.php
php/WP_CLI/FileCache.php
php/WP_CLI/Formatter.php
php/WP_CLI/PackageManagerEventSubscriber.php
php/WP_CLI/Process.php
phpcs.xml.dist

CS for php/WP_CLI/* (Part I)

---

php/WP_CLI/Completions.php
php/WP_CLI/ComposerIO.php
php/WP_CLI/Configurator.php
php/WP_CLI/DocParser.php
phpcs.xml.dist

CS for php/WP_CLI/* (Part II)

---

php/WP_CLI/Runner.php
php/WP_CLI/SynopsisParser.php
phpcs.xml.dist

CS for php/WP_CLI/* (Part III)

---

php/WP_CLI/SynopsisValidator.php
php/WP_CLI/UpgraderSkin.php
php/WP_CLI/WpHttpCacheManager.php
phpcs.xml.dist

CS for php/WP_CLI/* (Part IV)

---

php/boot-fs.php
php/boot-phar.php
php/class-wp-cli.php
phpcs.xml.dist

CS for php/* (Part I)

---

php/utils-wp.php
php/utils.php
php/wp-settings-cli.php
phpcs.xml.dist

CS for php/* (Part II)

---

php/utils.php
phpcs.xml.dist

Revert "Revert "PHPCS: Remove exclusions that can be fixed""

---

features/bootstrap.feature
features/bootstrap/FeatureContext.php
features/steps/given.php

Serve `RUN_DIR` by default with "Given a PHP built-in web server"

---

php/config-spec.php

Mention use of `vagrant` in config spec

---

php/utils.php

Ignore call to restricted function because WP isn't loaded yet

---

php/WP_CLI/FileCache.php
php/WP_CLI/Runner.php
php/commands/src/CLI_Command.php
php/utils-wp.php
php/utils.php
php/wp-settings-cli.php

Avoid suppressing errors to conform to PHPCS

---

php/WP_CLI/Completions.php
php/WP_CLI/Configurator.php
php/WP_CLI/Dispatcher/Subcommand.php
php/WP_CLI/FileCache.php
php/WP_CLI/Iterators/Query.php
php/WP_CLI/Runner.php
php/utils.php

Yoda conditions, you must

---

composer.lock
features/command.feature

```
Package operations: 0 installs, 18 updates, 0 removals
- Updating wp-cli/cache-command (v1.0.2 => v1.0.3): Downloading (100%)
- Updating wp-cli/checksum-command (v1.0.2 => v1.0.3): Downloading (100%)
- Updating wp-cli/config-command (v1.1.4 => v1.1.5):	Checking out 681797a7fe
- Updating wp-cli/cron-command (v1.0.2 => v1.0.3):  Checking out 89e31e9f94
- Updating wp-cli/widget-command (v1.0.2 => v1.0.3): Downloading (100%)
- Updating wp-cli/super-admin-command (v1.0.2 => v1.0.3):  Checking out 9fcd13adfb
- Updating wp-cli/shell-command (v1.0.2 => v1.0.3):  Checking out 10968244ec
- Updating wp-cli/server-command (v1.0.6 => v1.0.7):	Checking out 9f6a4daede
- Updating wp-cli/search-replace-command (v1.0.3 => …
```

Update Composer dependencies (2017-10-02)

---

composer.json
composer.lock

```
Package operations: 0 installs, 6 updates, 0 removals
- Updating wp-cli/core-command (v1.0.2 => v1.0.3): Downloading (100%)
- Updating wp-cli/php-cli-tools (v0.11.6 => v0.11.7):	 Checking out 14b8a086b6
- Updating justinrainbow/json-schema (5.2.1 => 5.2.2):  Checking out b80053b620
- Updating wp-cli/scaffold-command (v1.0.7 => v1.0.8):  Checking out 2483ee1a06
- Updating wp-cli/package-command (v1.0.4 => v1.0.5):	 Checking out 49f394ecc5
- Updating wp-cli/export-command (v1.0.2 => v1.0.3):	Checking out fe66d39f64
```

Update Composer dependencies (2017-10-03)

---

.travis.yml
php/class-wp-cli.php
phpcs.xml.dist

Unpin WPCS from 0.12.0 in Travis; apply a couple more PHPCS rules

---

php/WP_CLI/WpHttpCacheManager.php

Only one placeholder, but two arguments provided.

Fix sprintf() argument count mismatch

---

php/utils.php

Type casting can be up to 6 times faster, apparently.

Use type casting

---

composer.lock

```
- Updating symfony/debug (v2.8.27 => v2.8.28):  Checking out eaaec993ca
- Updating symfony/filesystem (v2.8.27 => v2.8.28):  Checking out 5e3af878f1
- Updating symfony/process (v2.8.27 => v2.8.28):  Checking out 26c9fb02bf
- Updating symfony/yaml (v2.8.27 => v2.8.28):	 Checking out 842fb6df22
- Updating symfony/translation (v2.8.27 => v2.8.28):	Checking out 1248f84f70
- Updating symfony/finder (v2.8.27 => v2.8.28):  Checking out a945724b20
- Updating symfony/event-dispatcher (v2.8.27 => v2.8.28):  Checking out 7fe0892325
- Updating symfony/dependency-injection (v2.8.27 => v2.8.28):	 Checking out 2562562610
- Updating symfony/console (v2.8.27 => v2.8.28): …
```

Update Composer dependencies (2017-10-06)

---

php/WP_CLI/Runner.php
php/class-wp-cli.php
php/commands/src/CLI_Command.php
php/utils-wp.php
php/utils.php

Improves readability.
A couple of instances not changed, as they have variable re-use i.e. $a = some_func( $a ) as the non-default path.

Unhide default value from else branch

---

php/WP_CLI/Runner.php

Will help to unify code style. Does not give any performance gain.

Avoid unnecessary double quotes

---

php/WP_CLI/Runner.php

Pre-increment can perform better than post-increment.

Use increment operation

---

php/WP_CLI/Bootstrap/IncludeBundledAutoloader.php
php/WP_CLI/Bootstrap/IncludeFallbackAutoloader.php
php/WP_CLI/Bootstrap/IncludeFrameworkAutoloader.php
php/WP_CLI/Bootstrap/IncludePackageAutoloader.php
php/WP_CLI/Bootstrap/LoadRequiredCommand.php
php/WP_CLI/Completions.php
php/WP_CLI/Configurator.php
php/WP_CLI/Dispatcher/CommandFactory.php
php/WP_CLI/Dispatcher/CompositeCommand.php
php/WP_CLI/Dispatcher/Subcommand.php
php/WP_CLI/DocParser.php
php/WP_CLI/Runner.php
php/class-wp-cli.php
php/commands/help.php
php/commands/src/CLI_Command.php
php/utils-wp.php
php/utils.php
php/wp-settings-cli.php
phpcs.xml.dist

Avoid variable assignments within statements

---

php/WP_CLI/Bootstrap/IncludeBundledAutoloader.php
php/WP_CLI/Bootstrap/IncludeFallbackAutoloader.php
php/WP_CLI/Bootstrap/IncludeFrameworkAutoloader.php
php/WP_CLI/Bootstrap/IncludePackageAutoloader.php
php/WP_CLI/Bootstrap/LoadRequiredCommand.php
php/WP_CLI/Completions.php
php/WP_CLI/Configurator.php
php/WP_CLI/Dispatcher/CommandFactory.php
php/WP_CLI/Dispatcher/CompositeCommand.php
php/WP_CLI/Dispatcher/Subcommand.php
php/WP_CLI/DocParser.php
php/WP_CLI/Runner.php
php/class-wp-cli.php
php/commands/help.php
php/commands/src/CLI_Command.php
php/utils-wp.php
php/utils.php
php/wp-settings-cli.php
phpcs.xml.dist

Reverts wp-cli/wp-cli#4389
It's an inconsequentially small change that's not worth endlessly debating.
Related #4058

Revert "Avoid variable assignments within statements"

---

composer.json
composer.lock

Fixes #4394
See https://github.com/justinrainbow/json-schema/issues/451

Update JSON-Schema library to v5.2.5

---

features/bootstrap/support.php
features/steps/then.php

Related:
https://github.com/wp-cli/scaffold-package-command/pull/148#issuecomment-335539356

Add context to behat which can check the contents with regexp 

---

composer.lock

```
Package operations: 0 installs, 9 updates, 0 removals
- Updating wp-cli/cache-command (v1.0.3 => v1.0.4): Downloading (100%)
- Updating wp-cli/php-cli-tools (v0.11.7 => v0.11.8):	 Checking out 363c75349f
- Updating wp-cli/search-replace-command (v1.0.4 => v1.1.0):	Checking out 54c5dc365b
- Updating wp-cli/scaffold-command (v1.0.8 => v1.0.9):  Checking out 367f4d1107
- Updating wp-cli/package-command (v1.0.5 => v1.0.6):	 Checking out 435356f834
- Updating wp-cli/media-command (v1.1.0 => v1.1.1):  Checking out 3ad78de69b
- Updating wp-cli/extension-command (v1.1.3 => v1.1.4):  Checking out f1f9110ce2
- Updating wp-cli/entity-command (v1.1.0 => v1.1.1):	Checking out dfedb1e213
- Updating wp-cli/db-command …
```

Update Composer dependencies (2017-10-13)

---

composer.lock

```
Package operations: 0 installs, 6 updates, 0 removals
- Updating wp-cli/core-command (v1.0.3 => v1.0.4): Downloading (100%)
- Updating wp-cli/search-replace-command (v1.1.0 => v1.1.1):	Checking out a823ffaf0f
- Updating wp-cli/scaffold-command (v1.0.9 => v1.0.10):  Checking out 97ab0a2e38
- Updating wp-cli/package-command (v1.0.6 => v1.0.7):	 Checking out d19d506065
- Updating wp-cli/entity-command (v1.1.1 => v1.1.2):	Checking out 10517f0248
- Updating wp-cli/db-command (v1.2.3 => v1.2.4):  Checking out 1379a28df5
```

Update Composer dependencies (2017-10-16)

---

features/prompt.feature
php/WP_CLI/Dispatcher/Subcommand.php

Merge arguments from `--prompt` into existing $args

---

features/bootstrap.feature

More and more hosts are using environment variables to populate
`wp-config.php`, so let's make sure this works as expected with WP-CLI.

Add a test that sets an environment variable to set a constant

---

composer.json

cf. https://github.com/wp-cli/wp-cli.github.com/pull/284

update composer.json description, homepage

---

composer.lock

```
- Updating justinrainbow/json-schema (5.2.5 => 5.2.6):  Checking out d283e11b6e
```

Update Composer dependencies (2017-10-23)

---

features/cli.feature
features/command.feature
php/WP_CLI/Runner.php
php/commands/src/CLI_Command.php

A class `@when` shouldn't overrides individual method `@when`s. 

---

composer.lock

Update Composer dependencies (2017-10-25)

---

composer.lock

Update Composer dependencies (2017-10-27)

---

composer.lock

Update Composer dependencies (2017-10-30)

---

composer.lock

Update Composer dependencies (2017-11-01)

---

ci/behat-tags.php
features/bootstrap/FeatureContext.php
php/class-wp-cli.php

From https://github.com/wp-cli/package-command/pull/47

Only skip `@github-api` tests when `GITHUB_TOKEN` isn't present

---

composer.lock

```
- Updating wp-cli/scaffold-command (v1.0.10 => v1.0.11):  Checking out 66b61e055b
```

Update Composer dependencies (2017-11-02)

---

.github/SUPPORT.md

Add a `.github/SUPPORT.md` file to show support nag

---

composer.json
composer.lock
php/WP_CLI/Runner.php

See https://github.com/wp-cli/db-command/pull/57

Introduce new `after_wp_config_load` early invoke for `wp db *`

---

composer.json
utils/git-pre-commit-hook

Install a `pre-commit` Git hook on `composer install` to sniff codebase

---

.travis.yml
ci/prepare.sh
ci/sniff.sh
ci/test.sh

Use Travis build stages to only run `phpcs` once and first

---

features/command.feature
php/class-wp-cli.php

Support 'longdesc' as command argument when registering a command

---

.travis.yml
ci/deploy.sh

See https://github.com/wp-cli/handbook/pull/168
Fixes #4507

Deploy release branches too

---

composer.lock

```
- Updating symfony/filesystem (v2.8.30 => v2.8.31):  Checking out 10507c5f24
- Updating symfony/config (v2.8.30 => v2.8.31):  Checking out f4f3f1d709
- Updating symfony/debug (v2.8.30 => v2.8.31):  Checking out a0a29e9867
- Updating symfony/console (v2.8.30 => v2.8.31):  Checking out 7cad097cf0
- Updating symfony/dependency-injection (v2.8.30 => v2.8.31):	 Checking out bc84511148
- Updating symfony/event-dispatcher (v2.8.30 => v2.8.31):  Checking out b59aacf238
- Updating symfony/finder (v2.8.30 => v2.8.31):  Checking out efeceae6a0
- Updating symfony/process (v2.8.30 => v2.8.31):  Checking out d25449e031
- Updating …
```

Update Composer dependencies (2017-11-17)

---

composer.lock

```
- Updating wp-cli/core-command (v1.0.4 => v1.0.5): Downloading (100%)
```

Update Composer dependencies (2017-11-20)

---

.travis.yml
features/help.feature

Switch PHP 7.2 test to use `WP_VERSION=latest`

---

composer.lock

```
Package operations: 0 installs, 22 updates, 0 removals
- Updating wp-cli/cache-command (v1.0.4 => v1.0.5): Downloading (100%)
- Updating wp-cli/checksum-command (v1.0.3 => v1.0.4): Downloading (100%)
- Updating wp-cli/config-command (v1.1.5 => v1.1.6):	Checking out 075b04a946
- Updating wp-cli/core-command (v1.0.5 => v1.0.6): Downloading (100%)
- Updating wp-cli/cron-command (v1.0.3 => v1.0.4):  Checking out 6124392353
- Updating wp-cli/widget-command (v1.0.3 => v1.0.4): Downloading (100%)
- Updating wp-cli/super-admin-command (v1.0.3 => v1.0.4):  Checking out 8ad8446a1b
- Updating wp-cli/shell-command (v1.0.3 => v1.0.4):  Checking out a918242695
- Updating wp-cli/server-command …
```

Update Composer dependencies (2017-11-21)

---

composer.lock

```
- Updating wp-cli/super-admin-command (v1.0.4 => v1.0.5):  Checking out 314a3f7b02
```

Update Composer dependencies (2017-11-22)

---

composer.lock

Update Composer dependencies (2017-11-24)

---

composer.lock

```
- Updating phpunit/php-file-iterator (1.4.2 => 1.4.3): Downloading (100%)
```

Update Composer dependencies (2017-11-27)

---

.travis.yml

https://github.com/travis-ci/travis-ci/issues/4579#issuecomment-127972205

Caching the vendor itself looks like a bad idea

---

composer.lock

```
- Updating wp-cli/scaffold-command (v1.0.12 => v1.1.0):  Checking out f174112ae3
- Updating phpunit/php-file-iterator (1.4.3 => 1.4.5): Downloading (100%)
```

Update Composer dependencies (2017-11-28)

---

composer.lock

```
Package operations: 0 installs, 3 updates, 0 removals
- Updating seld/jsonlint (1.6.1 => 1.6.2):  Checking out 7a30649c67
- Updating composer/ca-bundle (1.0.9 => 1.1.0):  Checking out 943b2c4fca
- Updating composer/composer (1.5.2 => 1.5.5):  Checking out aab6229c9a
```

Update Composer dependencies (2017-12-04)

---

features/aliases.feature
features/bootstrap.feature
features/bootstrap/FeatureContext.php
features/cli.feature
features/command.feature
features/config.feature
features/flags.feature
features/framework.feature
features/help.feature
features/hook.feature
features/runcommand.feature
features/skip-plugins.feature
features/skip-themes.feature
features/steps/given.php
features/validation.feature

Use 'Given a WP installation' in Behat tests

---

features/command.feature
php/WP_CLI/Runner.php

Load WP to ensure all registered commands appear in usage

---

features/command.feature

Add more test cases for registering synopsis to command

---

composer.lock

```
- Updating wp-cli/core-command (v1.0.6 => v1.0.7): Downloading (100%)
```

Update Composer dependencies (2017-12-11)

---

composer.lock

Update Composer dependencies (2017-12-13)

---

composer.lock

```
- Updating wp-cli/db-command (v1.3.1 => v1.3.2):  Checking out 162d72acfd
```

Update Composer dependencies (2017-12-15)

---

composer.lock

```
Package operations: 0 installs, 21 updates, 0 removals
- Updating wp-cli/cache-command (v1.0.5 => v1.0.6): Downloading (100%)
- Updating wp-cli/checksum-command (v1.0.4 => v1.0.5): Downloading (100%)
- Updating wp-cli/config-command (v1.1.6 => v1.1.7):	Checking out e0c378457e
- Updating wp-cli/cron-command (v1.0.4 => v1.0.5):  Checking out 9da7e36e8f
- Updating wp-cli/entity-command (v1.1.3 => v1.1.4):	Checking out c3a0c2b478
- Updating wp-cli/widget-command (v1.0.4 => v1.0.5): Downloading (100%)
- Updating wp-cli/super-admin-command (v1.0.5 => v1.0.6):  Checking out 2982d2e651
- Updating wp-cli/shell-command (v1.0.4 => v1.0.5):  Checking out 507603a899
- Updating composer/composer …
```

Update Composer dependencies (2017-12-18)

---

composer.lock

```
- Updating wp-cli/core-command (v1.0.7 => v1.0.8): Downloading (100%)
```

Update Composer dependencies (2017-12-20)

---

composer.lock

Update Composer dependencies (2017-12-27)

---

composer.lock

Update Composer dependencies (2017-12-25)

---

php/utils.php

Allows to set update interval, available in class constructor but not previously accepted by function wrapper.

 Added interval argument to make_progress_bar()

---

php/commands/src/CLI_Command.php

#4599  add os and shell information in `wp cli info`

Add OS & shell information in 'info' command

---

php/commands/src/CLI_Command.php

#4609 update doc block for `cli info` for changes made in #4604

update doc block for cli info

---

.github/ISSUE_TEMPLATE
composer.json

See https://github.com/wp-cli/embed-command/issues/18

Add embed-command as bundled package.

---

php/utils.php

Add some more suggestions for mis-typed arguments

---

php/utils.php
tests/test-utils.php

Make sure '0' edge case is properly handled by is_json()

---

features/command.feature
php/WP_CLI/Configurator.php
php/WP_CLI/Runner.php

See https://github.com/wp-cli/checksum-command/issues/14

Reverse the aliases for checksum verification commands

---

composer.lock

Update `wp-cli/extension-command` v1.1.8 => v1.1.9

Update extension package

---

composer.lock

* Update to `wp-cli/config-command` v1.1.7 => v1.1.8
* Adds dependency `wp-cli/wp-config-transformer` v1.2.0

Update to latest config package

---

utils/update-phar

Phive needs a GPG signature as `.phar.asc` file.
See https://phar.io/howto/sign-and-upload-to-github.html

Support Phive package manager

---

utils/update-phar

Revert "Support Phive package manager"

---

composer.lock

Fixes https://github.com/wp-cli/scaffold-package-command/issues/167

Update wp-cli/package-command to v1.0.12

---

.travis.yml
composer.json
composer.lock
php/boot-fs.php

Require minimum PHP 5.4

---

.travis.yml
composer.json
composer.lock
features/bootstrap.feature
php/boot-fs.php

Revert "Require minimum PHP 5.4"

---

composer.lock

```
Package operations: 0 installs, 12 updates, 0 removals
- Updating symfony/filesystem (v2.8.34 => v2.8.35):  Checking out 125403a59e
- Updating symfony/config (v2.8.34 => v2.8.35):  Checking out 17605ff583
- Updating symfony/debug (v2.8.34 => v2.8.35):  Checking out f693ba8818
- Updating symfony/console (v2.8.34 => v2.8.35):  Checking out a6ff8b2ffa
- Updating symfony/dependency-injection (v2.8.34 => v2.8.35):	 Checking out 3d7cbf34cd
- Updating symfony/event-dispatcher (v2.8.34 => v2.8.35):  Checking out f5d2d7dcc3
- Updating symfony/finder (v2.8.34 => v2.8.35):  Checking out 7099de3ebc
- Updating symfony/process (v2.8.34 => v2.8.35):  Checking out 756f614c50
- Updating …
```

Update Composer dependencies (2018-03-05)

---

composer.lock

```
- Updating symfony/filesystem (v2.8.35 => v2.8.36):  Checking out 125403a59e
- Updating symfony/config (v2.8.35 => v2.8.36):  Checking out 17605ff583
- Updating symfony/debug (v2.8.35 => v2.8.36):  Checking out f693ba8818
- Updating symfony/console (v2.8.35 => v2.8.36):  Checking out a6ff8b2ffa
- Updating symfony/dependency-injection (v2.8.35 => v2.8.36):	 Checking out 3d7cbf34cd
- Updating symfony/event-dispatcher (v2.8.35 => v2.8.36):  Checking out f5d2d7dcc3
- Updating symfony/finder (v2.8.35 => v2.8.36):  Checking out c5c751ccd5
- Updating symfony/process (v2.8.35 => v2.8.36):  Checking out 756f614c50
- Updating …
```

Update Composer dependencies (2018-03-07)

---

composer.lock

Update Composer dependencies (2018-03-14)

---

composer.lock

Update Composer dependencies (2018-03-16)

---

features/utils-wp.feature

Skip wp_blogmeta table for back compat

---

composer.lock

Update Composer dependencies (2018-03-20)

---

composer.lock

Update Composer dependencies (2018-03-23)

---

composer.lock

```
- Updating composer/ca-bundle (1.1.0 => 1.1.1):  Checking out d2c0a83b75
```

Update Composer dependencies (2018-03-30)

---

README.md

Include sublinks in README to popular installation methods

---

composer.lock

Update Composer dependencies (2018-04-02)

---

composer.lock

```
- Updating symfony/filesystem (v2.8.36 => v2.8.37):  Checking out 125403a59e
- Updating symfony/config (v2.8.36 => v2.8.37):  Checking out ecacddeaf7
- Updating symfony/debug (v2.8.36 => v2.8.37):  Checking out ce92aa6388
- Updating symfony/console (v2.8.36 => v2.8.37):  Checking out 390fa4899d
- Updating symfony/dependency-injection (v2.8.36 => v2.8.37):	 Checking out 3d7cbf34cd
- Updating symfony/event-dispatcher (v2.8.36 => v2.8.37):  Checking out f5d2d7dcc3
- Updating symfony/finder (v2.8.36 => v2.8.37):  Checking out 3cf7b50fa4
- Updating symfony/process (v2.8.36 => v2.8.37):  Checking out c2fc900ee5
- Updating …
```

Update Composer dependencies (2018-04-04)

---

composer.lock

```
- Updating symfony/filesystem (v2.8.37 => v2.8.38):  Checking out 125403a59e
- Updating symfony/config (v2.8.37 => v2.8.38):  Checking out ecacddeaf7
- Updating symfony/debug (v2.8.37 => v2.8.38):  Checking out 4486d2be5e
- Updating symfony/console (v2.8.37 => v2.8.38):  Checking out 7f78892d90
- Updating symfony/dependency-injection (v2.8.37 => v2.8.38):	 Checking out 3d7cbf34cd
- Updating symfony/event-dispatcher (v2.8.37 => v2.8.38):  Checking out 9b69aad7d4
- Updating symfony/finder (v2.8.37 => v2.8.38):  Checking out 423746fc18
- Updating symfony/process (v2.8.37 => v2.8.38):  Checking out ee2c91470f
- Updating …
```

Update Composer dependencies (2018-04-09)

---

composer.lock

Update Composer dependencies (2018-04-13)

---

composer.lock

```
- Updating composer/composer (1.6.3 => 1.6.4):  Checking out 86ad51e8a3
```

Update Composer dependencies (2018-04-16)

---

composer.lock

```
Package operations: 0 installs, 14 updates, 0 removals
- Updating symfony/process (v2.8.38 => v2.8.39):  Checking out ee2c91470f
- Updating symfony/finder (v2.8.38 => v2.8.39):  Checking out 423746fc18
- Updating symfony/filesystem (v2.8.38 => v2.8.39):  Checking out 125403a59e
- Updating symfony/polyfill-mbstring (v1.7.0 => v1.8.0):  Checking out 3296adf6a6
- Updating symfony/debug (v2.8.38 => v2.8.39):  Checking out 4486d2be5e
- Updating symfony/console (v2.8.38 => v2.8.39):  Checking out 932d1e4f7f
- Updating composer/composer (1.6.3 => 1.6.4):  Checking out 86ad51e8a3
- Updating symfony/config (v2.8.38 => v2.8.39):  Checking out ecacddeaf7
- Updating symfony/dependency-injection …
```

Update Composer dependencies (2018-05-02)

---

composer.lock

```
- Updating composer/spdx-licenses (1.3.0 => 1.4.0):  Checking out cb17687e9f
- Updating composer/composer (1.6.4 => 1.6.5):  Checking out b184a92419
```

Update Composer dependencies (2018-05-09)

---

composer.lock

Update Composer dependencies (2018-05-14)

---

composer.lock

Switch to fixed package command

---

README.md

See https://docs.gitlab.com/ee/user/project/import/gemnasium.html

Remove Gemnasium badge, as the service was shut down

---

composer.lock

Update Composer dependencies (2018-06-13)

---

composer.lock

```
- Updating symfony/filesystem (v2.8.41 => v2.8.42):  Checking out 0f685c099a
- Updating symfony/config (v2.8.41 => v2.8.42):  Checking out 93bdf96d0e
- Updating symfony/debug (v2.8.41 => v2.8.42):  Checking out a26ddce7fe
- Updating symfony/console (v2.8.41 => v2.8.42):  Checking out e8e59b74ad
- Updating symfony/dependency-injection (v2.8.41 => v2.8.42):	 Checking out 0f42a0827d
- Updating symfony/event-dispatcher (v2.8.41 => v2.8.42):  Checking out 9b69aad7d4
- Updating symfony/finder (v2.8.41 => v2.8.42):  Checking out 995cd7c28a
- Updating symfony/process (v2.8.41 => v2.8.42):  Checking out 542d88b350
- Updating …
```

Update Composer dependencies (2018-06-27)

---

bin/wp

Fixes https://github.com/wp-cli/wp-cli/issues/4834 and https://github.com/wp-cli/wp-cli/issues/4833

Fixing issues in bin/wp

---

ci/prepare.sh

Fixes https://github.com/wp-cli/wp-cli/issues/4838

Additional quoting in ci/prepare.sh

---

ci/deploy.sh
features/skip-themes.feature

Fixes #4837 and https://github.com/wp-cli/wp-cli/issues/4836

Fixing issues in ci/deploy.sh

---

php/commands/src/CLI_Command.php
phpcs.xml.dist

Fall back to full string instead of $mode on PHP < 7

---

composer.lock

```
- Updating wimg/php-compatibility (8.1.0 => 8.2.0): Downloading (100%)
```

Update Composer dependencies (2018-07-18)

---

composer.lock

Update Composer dependencies (2018-07-20)

---

composer.lock

```
- Updating wp-cli/extension-command (dev-master 5609057 => 1.2.1):  Checking out 5609057ff7
```

Update Composer dependencies (2018-07-23)

---

composer.lock

```
- Updating symfony/filesystem (v2.8.42 => v2.8.43):  Checking out 5cfc856c5b
- Updating symfony/config (v2.8.42 => v2.8.43):  Checking out 93bdf96d0e
- Updating symfony/debug (v2.8.42 => v2.8.43):  Checking out a26ddce7fe
- Updating symfony/console (v2.8.42 => v2.8.43):  Checking out 42a0adc7dd
- Updating symfony/dependency-injection (v2.8.42 => v2.8.43):	 Checking out 1143ebbfdc
- Updating symfony/event-dispatcher (v2.8.42 => v2.8.43):  Checking out 9b69aad7d4
- Updating symfony/finder (v2.8.42 => v2.8.43):  Checking out 995cd7c28a
- Updating symfony/process (v2.8.42 => v2.8.43):  Checking out 542d88b350
- Updating …
```

Update Composer dependencies (2018-07-25)

---

features/make-phar.feature

Adapt regular expression to skip wiki links

---

php/commands/src/CLI_Command.php

I believe the condition should be reversed...

Fix PHP version check

---

composer.lock

```
Package operations: 0 installs, 4 updates, 0 removals
- Updating wp-cli/core-command (v1.0.11 => v1.0.12): Downloading (100%)
- Updating wp-cli/db-command (v1.3.4 => v1.3.5):  Checking out c260be59d9
- Updating wp-cli/entity-command (v1.3.0 => v1.3.1):	Checking out 7b00064568
- Updating wp-cli/extension-command (1.2.1 => v1.2.2):  Checking out 18f1036bad
```

Update Composer dependencies (2018-08-01)

---

composer.lock

```
- Updating symfony/filesystem (v2.8.43 => v2.8.44):  Checking out 2d6a4deccd
- Updating symfony/config (v2.8.43 => v2.8.44):  Checking out 06c0be4cdd
- Updating symfony/debug (v2.8.43 => v2.8.44):  Checking out d985c8546d
- Updating symfony/console (v2.8.43 => v2.8.44):  Checking out 0c1fcbb9af
- Updating symfony/dependency-injection (v2.8.43 => v2.8.44):	 Checking out ad2446d39d
- Updating symfony/event-dispatcher (v2.8.43 => v2.8.44):  Checking out 84ae343f39
- Updating symfony/finder (v2.8.43 => v2.8.44):  Checking out f0de0b5191
- Updating symfony/process (v2.8.43 => v2.8.44):  Checking out cc83afdb5a
- Updating …
```

Update Composer dependencies (2018-08-03)

---

php/class-wp-cli.php

Debug `debug()` bug

---

composer.lock

```
Package operations: 0 installs, 3 updates, 0 removals
- Updating composer/xdebug-handler (1.1.0 => 1.2.0): Loading from cache
- Updating composer/composer (1.7.1 => 1.7.2):  Checking out 576aab9b5a
```

Update Composer dependencies (2018-08-20)

---

composer.json
composer.lock
tests/bootstrap.php

Update dependencies and make avoid redefining WP_CLI_ROOT

---

php/utils.php
tests/test-utils.php

Make `pick_fields()` work with numeric headers

---

php/commands/src/CLI_Command.php

Skip releases that lack a downloadable asset

---

composer.lock

```
- Updating wp-cli/wp-cli-tests (v2.0.9 => v2.0.10): Downloading (100%)
```

Update Composer dependencies (2018-08-27)

---

features/help.feature
features/prompt.feature
php/WP_CLI/Dispatcher/Subcommand.php

Check and display help command if requested

---

composer.lock

```
- Updating composer/xdebug-handler (1.2.1 => 1.3.0): Downloading (100%)
```

Update Composer dependencies (2018-09-03)

---

composer.lock
php/WP_CLI/Autoloader.php
php/WP_CLI/Bootstrap/AutoloaderStep.php
php/WP_CLI/Bootstrap/IncludeFallbackAutoloader.php
php/WP_CLI/Bootstrap/IncludeFrameworkAutoloader.php
php/WP_CLI/Bootstrap/RegisterDeferredCommands.php
php/WP_CLI/Bootstrap/RegisterFrameworkCommands.php
php/WP_CLI/Dispatcher/CommandFactory.php
php/WP_CLI/Runner.php
php/WP_CLI/SynopsisValidator.php
php/class-wp-cli.php
php/commands/src/Help_Command.php
php/utils-wp.php
php/utils.php

```
- Updating wp-coding-standards/wpcs (1.0.0 => 1.1.0): Downloading (100%)
```

Update Composer dependencies (2018-09-12)

---

composer.lock

Update Composer dependencies (2018-09-17)

---

php/class-wp-cli.php

Reattach existing subcommands from namespace to replacing command

---

composer.lock

```
Package operations: 0 installs, 3 updates, 0 removals
- Updating wp-cli/core-command (v2.0.0 => v2.0.1): Downloading (100%)
- Updating wp-cli/eval-command (v2.0.0 => v2.0.1):  Checking out 26d3e6f609
- Updating squizlabs/php_codesniffer (3.3.1 => 3.3.2): Downloading (100%)
```

Update Composer dependencies (2018-09-24)

---

composer.lock

```
- Updating symfony/finder (v2.8.45 => v2.8.46):  Checking out 5ebb438d1a
- Updating symfony/debug (v2.8.45 => v2.8.46):  Checking out 4fd77efcd4
- Updating symfony/console (v2.8.45 => v2.8.46):  Checking out aca0dcc0c7
- Updating symfony/process (v2.8.45 => v2.8.46):  Checking out f09e21b7c5
- Updating symfony/filesystem (v2.8.45 => v2.8.46):  Checking out 91f194c5ec
- Updating symfony/config (v2.8.45 => v2.8.46):  Checking out fb3469266d
- Updating symfony/dependency-injection (v2.8.45 => v2.8.46):	 Checking out 84219396d1
- Updating symfony/event-dispatcher (v2.8.45 => v2.8.46):  Checking out 84ae343f39
- Updating …
```

Update Composer dependencies (2018-10-01)

---

composer.lock

```
The "http://packagist.org/p/provider-2014%249bc89e987e0d0c9802cf5a040379ac740ed6d0949e8eac49c6c282702462f569.json" file could not be downloaded: failed to open stream: Connection timed out
http://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
- Updating wp-cli/extension-command (v2.0.1 => v2.0.2):  Checking out aa552f5ec6
PHP CodeSniffer Config installed_paths set to ../../phpcompatibility/php-compatibility/,../../phpcompatibility/phpcompatibility-wp/,../../wp-coding-standards/wpcs/
```

Update Composer dependencies (2018-10-03)

---

composer.lock

Update Composer dependencies (2018-10-08)

---

composer.lock

Update Composer dependencies (2018-10-12)

---

composer.lock

```
PHP CodeSniffer Config installed_paths set to ../../phpcompatibility/php-compatibility/,../../phpcompatibility/phpcompatibility-wp/,../../wp-coding-standards/wpcs/
```

Update Composer dependencies (2018-10-17)

---

.github/move.yml

See https://probot.github.io/apps/move/

Add Probot `move` support

---

php/class-wp-cli.php

Improve `--debug` output for `WP_CLI::add_command`

---

composer.json
composer.lock

Add `ext-zip` as suggested extension

---

composer.json
composer.lock

Extension requirements added:
- `ext-curl` (see #4999)
- `ext-posix`
- `ext-readline`
Fixes #5000

Add extension requirements to `composer.json` file

---

phpcs.xml.dist

Bump PHP version to 5.4+ for PHP Compatibility Checker

---

features/bootstrap.feature
php/bootstrap.php

Fix override test on Composer stack

---

php/class-wp-cli.php
tests/test-utils.php

PHPCS: fix up the code base [5] - yoda conditions

---

php/commands/src/CLI_Command.php
php/commands/src/Help_Command.php
utils/contrib-list.php

* No assignments in conditions.

PHPCS: fix up the code base [8] - assignments in conditions

---

composer.json
composer.lock

Remove `ext-posix` requirement from Composer file

---

php/WP_CLI/Dispatcher/CommandNamespace.php
php/WP_CLI/Dispatcher/CompositeCommand.php

This code snippet will be confusing to a lot of people, so let's make it more explicit what's being done here.

PHPCS: fix up the code base [10] - logic obfuscation

---

features/command.feature
php/WP_CLI/SynopsisParser.php

Properly reorder synopsis passed in via `$args`

---

dependencies.yml

This tells [Dependencies.io](https://www.dependencies.io/) to create new pull requests when our dependencies have updates.

Add `dependencies.yml` file to define auto-updates

---

composer.json
composer.lock

Switch `ext-readline` to 'suggest' instead of a hard requirement

---

php/utils.php

Fixed documented return type for `make_progress_bar()`

---

php/WP_CLI/Dispatcher/CommandFactory.php
php/WP_CLI/Dispatcher/CompositeCommand.php
php/WP_CLI/Extractor.php
php/WP_CLI/Formatter.php
php/WP_CLI/Iterators/Query.php
php/WP_CLI/Loggers/Base.php
php/class-wp-cli.php
php/dispatcher.php
php/utils.php

Addresses issue #5110.
Makes no functional changes, but only changes types to
match the expected behaviour.
After these fixes, the issues list looks [like this][phan_report].
[phan_report]: https://github.com/wp-cli/wp-cli/files/2999571/phan_report.txt

Corrected Type Docs & Usage

---

php/WP_CLI/Dispatcher/Subcommand.php
php/WP_CLI/Runner.php
tests/test-utils.php

Minor touch up of newly introduced code.

CS: clean up after merges

---

php/class-wp-cli.php
php/utils.php

PHPCS: fix up the code base [19] - strict comparisons

---

php/class-wp-cli.php
php/utils.php

Justify the use of `mt_rand()`

---

php/utils-wp.php

Whitelist already escaped SQL for PHPCS

---

php/WP_CLI/Formatter.php
php/WP_CLI/SynopsisValidator.php

Use strict comparisons

---

php/WP_CLI/Bootstrap/BootstrapState.php
php/WP_CLI/Bootstrap/DefineProtectedCommands.php
php/WP_CLI/Bootstrap/IncludePackageAutoloader.php
php/WP_CLI/Bootstrap/LoadRequiredCommand.php

Rename camelCase methods into snake_case

---

php/WP_CLI/ComposerIO.php
php/WP_CLI/UpgraderSkin.php
php/utils-wp.php

Related #5166
Related https://github.com/wp-cli/wp-cli/issues/5179

Replace or justify the usage of the `strip_tags()` function

---

php/utils-wp.php

It is a copy-paste left-over and irrelevant in this context.
Related #5166
Related #5179

Remove code comment

---

php/class-wp-cli.php
php/utils-wp.php
php/utils.php
php/wp-cli.php
php/wp-settings-cli.php

Fix typos and improve readability of inline docs

---

features/aliases.feature
php/commands/cli.php
php/commands/src/CLI_Alias_Command.php
php/commands/src/CLI_Command.php

Add command to manage aliases

---

php/utils-wp.php

Fix last remaining usage of `strip_tags`

---

php/WP_CLI/Process.php
php/class-wp-cli.php

Some ProcessRun was not referenced with namespace.

Fix return types

---

composer.lock

Updating symfony/polyfill-ctype (v1.11.0 => v1.12.0)
Updating symfony/polyfill-mbstring (v1.11.0 => v1.12.0)
Updating composer/spdx-licenses (1.5.1 => 1.5.2)
Updating composer/ca-bundle (1.1.4 => 1.2.3)
Updating composer/composer (1.8.6 => 1.9.0)
Updating wp-cli/wp-config-transformer (v1.2.5 => v1.2.6)

Update Composer dependencies (2019-08-13)

---

php/commands/src/CLI_Alias_Command.php

Example for adding alias is missing '@'

---

php/utils.php

Fix return type of `make_progress_bar()`

---

php/utils.php

When a command uses `Utils\http_request()` when WordPress Core has not been loaded yet, we need to ensure that the autoloader for the Requests library is actually registered before doing the request.
Fixes #5295
This PR also does a bit of clean-up to make the dependencies of the `Utils` class a bit more obvious.

Ensure the autoloader for the Requests library is registered

---

php/utils-wp.php
php/wp-settings-cli.php

This file was not updated in a while, and the latest tests seem to break because of it.

Refresh `wp-settings-cli.php` to reflect changes to Core `wp-settings.php`

---

.travis.yml

Syncs with the other packages to keep them consistent.

Sync Travis

---

php/WP_CLI/Runner.php

Use warning instead of colorize to fix warning output

---

php/utils.php
tests/test-utils.php

Adapt regex in `parse_str_to_argv()`

---

php/WP_CLI/FileCache.php

Fix access to undefined host index

---

.github/ISSUE_TEMPLATE/2-FEATURE_REQUEST.md

Update feature request template from central version

---

php/WP_CLI/Runner.php

Hopefully it will now be provided when needed but not be declared twice.

Change timing of when to polyfill `is_customize_preview()`

---

.github/ISSUE_TEMPLATE/4-REGULAR_RELEASE_CHECKLIST.md
.github/ISSUE_TEMPLATE/5-PATCH_RELEASE_CHECKLIST.md

Update link to Homebrew

---

.github/ISSUE_TEMPLATE/4-REGULAR_RELEASE_CHECKLIST.md
.github/ISSUE_TEMPLATE/5-PATCH_RELEASE_CHECKLIST.md

Add notes regarding the issues that were seen during v2.4.0 release.

Add notes about rpm and deb builds

---

.github/ISSUE_TEMPLATE/3-SUPPORT_REQUEST.md
php/WP_CLI/Inflector.php
php/WP_CLI/Runner.php
php/commands/src/Help_Command.php
php/compat.php
php/utils-wp.php
php/utils.php
php/wp-settings-cli.php

- fix typos and docs standards and URL.

fix typos and docs standards and URL.

---

php/WP_CLI/Runner.php

Issue: https://github.com/wp-cli/ideas/issues/138

Add $wp_config_path param for  get_wp_config_code

---

.github/workflows/code-quality.yml
composer.lock
php/utils.php

Moves the logic from the `eval file` command over to improve `WP_CLI\Utils\replace_path_consts()`.
See #5332

Improve `replace_path_costs()` with logic from eval file command

---

composer.json
php/WP_CLI/Loggers/Execution.php
php/boot-fs.php
php/utils.php

Updated minimum required PHP version too 5.6

---

features/command.feature
php/WP_CLI/Dispatcher/Subcommand.php

Add support for comma-separated flag values

---

php/WP_CLI/WpHttpCacheManager.php

Missing @return tag in function/method PHPDoc comment

---

php/utils.php

Fixed: Wrong param type.

---

features/help.feature
php/WP_CLI/Dispatcher/CompositeCommand.php

Only suppress global parameters if set as true

---

features/bootstrap.feature
features/cli.feature
php/WP_CLI/Bootstrap/LoadEvalCommand.php
php/WP_CLI/Bootstrap/LoadExecCommand.php
php/bootstrap.php
php/config-spec.php

Initial development for new global parameter for executing php code. See #5446.

Add global parameter for executing php

---

composer.lock

Updates `wp-cli/wp-cli-tests` to v2.1.15.

Update Composer dependencies - 2020-10-31

---

composer.json

Add PHP 8 as an allowed PHP version

---

features/bootstrap.feature
php/WP_CLI/Bootstrap/DeclareFallbackFunctions.php
php/bootstrap.php
php/fallback-functions.php

This is needed for some tests.

Allow disabling of `ini_set()`

---

php/WP_CLI/FileCache.php

Harden error message on failed cache directory creation

---

composer.lock

Update Composer dependencies - 2021-05-08

---

README.md

Update the minimal PHP version from 5.4 to 5.6 in the README file

Update min PHP version to 5.6

---

php/utils-wp.php

Apply https://core.trac.wordpress.org/changeset/44453 to wp-cli.
Fixes #5474.

Allow WP_DEBUG_LOG to override the debug.log location.

---

.github/SECURITY.md

Add a `SECURITY.md` file

---

php/class-wp-cli.php

https://github.com/wp-cli/wp-cli/issues/5574

Cache: Changeable cache size.

---

features/cli.feature
features/config.feature
features/context.feature
features/flags.feature
features/hook.feature
php/WP_CLI/Bootstrap/InitializeContexts.php
php/WP_CLI/Bootstrap/LaunchRunner.php
php/WP_CLI/Context.php
php/WP_CLI/Context/Admin.php
php/WP_CLI/Context/Auto.php
php/WP_CLI/Context/Cli.php
php/WP_CLI/Context/Frontend.php
php/WP_CLI/ContextManager.php
php/WP_CLI/Runner.php
php/bootstrap.php
php/class-wp-cli.php
php/config-spec.php

**New global flag: `--context`**
This PR adds a new global parameter `--context=<context>` which allows users to select in which WordPress context WP-CLI is supposed to execute its command(s).
One of the main goals is to allow WP-CLI to run updates on premium plugins and themes without requiring any special setup.
Possible flags with this initial release:
- `cli`: The context which has been the default before introduction of this flag. This is something in-between a frontend and an admin request, to get around some of the quirks of WordPress when running on the console.
- `admin`: A context that simulates running a command as if it would be executed in the administration backend. This is meant to be used to get around issues with plugins that limit functionality behind an `is_admin()` …

Add `--context` flag

---

php/WP_CLI/Completions.php
php/WP_CLI/PackageManagerEventSubscriber.php
php/WP_CLI/UpgraderSkin.php

Added missing doc block on some functions.

Add missing docblocks

---

composer.json

Force the use of Mustache 2.14.1 security fix

---

php/WP_CLI/SynopsisParser.php
tests/test-synopsis.php

Handle optional option values in SynopsisParser::render()

---

features/config.feature
features/flags.feature

Move `WP_CLI_CONFIG_SPEC_FILTER_CALLBACK` test to `flags.feature`

---

php/utils-wp.php

Detection requested by Nexcess.
Object Cache Pro is widely used by Pagely, GoDaddy, Nexcess, Cloudways, Convesio and Rocket.net
Followup to #5436.

Detect Object Cache Pro

---

php/utils.php

Move over documentation improvement from https://github.com/wp-cli/handbook/pull/415.

Improve docs for SHELL_PIPE

---

php/WP_CLI/Completions.php

Fixes https://github.com/wp-cli/wp-cli/issues/5748

Fix autocompletion notice with PHP 8.2

---

features/aliases.feature
php/commands/src/CLI_Alias_Command.php

Hi there,
This PR has been submitted in conjunction with https://github.com/wp-cli/ideas/issues/173.
Please let me know if I need to make any alterations. Thanks!
Saul

Added "wp cli alias is-group" subcommand.

---

php/WP_CLI/Process.php

Given the haphazard nature of `Requests` version permutations, this PR ignores `Requests` deprecation messages in error handling for now if they are the sole output on `STDERR`.
This is done:
- to avoid unnecessary breakage in automated CI/CD pipelines
- to simplify testing within the WP-CLI project
This should only be seen as a temporary fix until we have a better solution for dealing with Requests as a dependency shared between WP Core and WP-CLI.

Ignore Requests deprecations in error handling for now

---

.github/ISSUE_TEMPLATE/4-REGULAR_RELEASE_CHECKLIST.md
.github/ISSUE_TEMPLATE/5-PATCH_RELEASE_CHECKLIST.md

Related https://github.com/wp-cli/wp-cli.github.com/pull/434

Mention updating the homepage in the release process

---

php/WP_CLI/Runner.php

Add `docker compose` command support in SSH command generation

---

.github/ISSUE_TEMPLATE/4-REGULAR_RELEASE_CHECKLIST.md

Based on yesterday's experience

Update release checklist template

---

php/commands/src/CLI_Command.php

Would like to add an example in the documentation showing a real world example of `wp cli has-command`.

Update Docs CLI_Command.php

---

php/class-wp-cli.php
php/compat.php
php/utils.php
php/wp-settings-cli.php

Issue: #5909
I updated inline documentation according to [PHP Documentation Standards -  Inline Comments ](https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/#5-inline-comments)

Update Inline comments

---

php/WP_CLI/Bootstrap/AutoloaderStep.php
php/WP_CLI/Bootstrap/IncludeFallbackAutoloader.php
php/WP_CLI/Dispatcher/Subcommand.php

This pull request improves function comments for enhanced clarity and documentation within the codebase. The updates aim to provide clear explanations of function behaviors and parameters, improving readability and maintainability. Thank you for reviewing this contribution.

Minor docblock improvements

---

php/WP_CLI/Fetchers/Signup.php

* Add `Signup` fetcher class
* We need this for `wp user signup` command
Ref: https://github.com/wp-cli/entity-command/pull/489

Add Signup fetcher

---

features/skip-themes.feature

Fix broken Gutenberg test

---

php/class-wp-cli.php
php/commands/src/CLI_Command.php

Config links were broken. Replaced with new URLs.

Fix broken config links

---

php/WP_CLI/Fetchers/Site.php

Fixes:  https://github.com/wp-cli/wp-cli/issues/6016

Added global documentation

---

php/WP_CLI/Configurator.php
php/WP_CLI/Dispatcher/CommandFactory.php
php/WP_CLI/Dispatcher/CompositeCommand.php
php/WP_CLI/Exception/NonExistentKeyException.php
php/WP_CLI/Extractor.php
php/WP_CLI/Fetchers/Base.php
php/WP_CLI/Fetchers/Signup.php
php/WP_CLI/FileCache.php
php/WP_CLI/Formatter.php
php/WP_CLI/Inflector.php
php/WP_CLI/Process.php
php/WP_CLI/RequestsLibrary.php
php/WP_CLI/Runner.php
php/WP_CLI/SynopsisParser.php
php/WP_CLI/Traverser/RecursiveDataStructureTraverser.php
php/WP_CLI/WpOrgApi.php
php/class-wp-cli.php
php/utils-wp.php
php/utils.php

We can't use PHPStan out of the box right now because of the higher PHP version requirement (see https://github.com/wp-cli/wp-cli-tests/pull/204), so I just ran it manually locally, level by level, fixing bugs along the way.
I went up to level ~5 here.

Code quality improvements powered by PHPStan

---

php/WP_CLI/Runner.php

1. `docker exec` and `docker-compose exec` provide an option to cleanly set the working directory before running a command
=> Use it instead and use `cd <...> ;` command-prefixing in vagrant/ssh cases
2. Using `docker` scheme, `wp post update 1 - <<<foo` didn't worked (issue #4972)
* Because STDOUT being a tty, `-t` is passed with no ability to inhibit this
* Because docker `-i` flag is necessary
=> As such:
* docker `-i` (`--interactive`) is introduced (with sensible autodetection)
* `WP_CLI_DOCKER_NO_TTY` and `WP_CLI_DOCKER_NO_INTERACTIVE` environment variables are introduced to optionally inhibit these respective flags

docker scheme: working-directory and stdin passing

---

php/WP_CLI/Runner.php

Reverts wp-cli/wp-cli#5974 because of test failures

Revert "docker scheme: working-directory and stdin passing"

---

php/commands/src/CLI_Command.php

See https://github.com/wp-cli/wp-cli-bundle/actions/runs/13646191736/job/38146378953?pr=693
Accidentally introduced in #6037
Props @ernilambar

Fix undefined variable issue

---

composer.json

Update `wp-cli/php-cli-tools` dependency

---

php/wp-cli.php

See https://github.com/wp-cli/wp-cli-tests/issues/241

Support multiple files in `WP_CLI_EARLY_REQUIRE`

---

php/commands/src/CLI_Command.php

fixes https://github.com/wp-cli/wp-cli/issues/5107

Update  WP-CLI update message

---

.github/ISSUE_TEMPLATE/4-REGULAR_RELEASE_CHECKLIST.md
.github/ISSUE_TEMPLATE/5-PATCH_RELEASE_CHECKLIST.md

Mainly to cover the new `*.manifest.json` file for PHP version requirements.

Update release issue templates

---

php/utils.php
tests/UtilsTest.php

This PR adds default escaping of CSV output to avoid inadvertent execution of CSV formulas.

Escape CSV output

---

composer.json

Use forked mustache library

---

README.md
composer.json
manifest.json
php/WP_CLI/SynopsisParser.php
php/boot-fs.php
php/class-wp-cli.php
php/commands/src/CLI_Command.php
php/commands/src/Help_Command.php
php/utils.php
phpcs.xml.dist
tests/UtilsTest.php

See https://github.com/wp-cli/wp-cli/issues/6026
Fixes #6087

Require PHP 7.2.24+
