wp-cli/wp-cli

php/WP_CLI/CommandWithUpgrade.php
The `remove_filter()` function only takes 3 arguments.
From the source code:
```
/**
* Removes a function from a specified filter hook.
*
* This function removes a function attached to a specified filter hook. This
* method can be used to remove default functions attached to a specific filter
* hook and possibly replace them with a substitute.
*
* To remove a hook, the $function_to_remove and $priority arguments must match
* when the hook was added. This goes for both filters and actions. No warning
* will be given on removal failure.
*
* @since 1.2.0
*
* @global array $wp_filter         Stores all of the filters
*
* @param string   $tag                The filter hook to which the function to be removed is hooked.
* @param callable $function_to_remove The name of the function which should …
```
=> Tweak `remove_filter()` function call.

php/WP_CLI/PackageManagerEventSubscriber.php
From the Composer source code:
```
/**
* The PRE_PACKAGE_INSTALL event occurs before a package is installed.
*
* The event listener method receives a Composer\Installer\PackageEvent instance.
*
* @deprecated Use Composer\Installer\PackageEvents::PRE_PACKAGE_INSTALL instead.
* @var string
*/
const PRE_PACKAGE_INSTALL = 'pre-package-install';
/**
* The POST_PACKAGE_INSTALL event occurs after a package is installed.
*
* The event listener method receives a Composer\Installer\PackageEvent instance.
*
* @deprecated Use Composer\Installer\PackageEvents::POST_PACKAGE_INSTALL instead.
* @var string
*/
const POST_PACKAGE_INSTALL = 'post-package-install';
```
=> Replace deprecated Composer constants.

composer.json
Add links to source, docs and issues to `composer.json`.
These are programmatically scanned in several places (like packagist.org) to provide direct access to these resources.
=> Add links to source, docs and issues to `composer.json`.

features/core-language.feature, php/WP_CLI/CommandWithTranslation.php
=> Process `--activate` flag on `language install` even if already installed

php/commands/widget.php
=> Actually return `false` when `$widget` is empty

features/bootstrap/FeatureContext.php
When setting several files for autoloading in `composer.json`, code on top of FeatureContext.php generates this wrong WP-CLI global config:
```
require:
- file1.php  - file2.php
```
which, when testing, results in this (hard to debug) error:
```
Required file 'file2.php' doesn't exist (from global config.yml).
```
After correction, the correct config file is generated:
```
require:
- file1.php
- file2.php
```
=> Add missing line break in FeatureContext.php

php/class-wp-cli.php, php/commands/server.php
Per the function comment "Environment values permit specific binaries to be indicated". Currently not possible as PHP_BINARY ***always*** present as defined constant (which can NEVER be overridden unless one uses runkit_extension; dated, not supported)
=> Fix allowing env. values to permit specific binary

features/post-term.feature, php/WP_CLI/CommandWithTerms.php
`wp_set_object_terms()` exhibits ambigious behavior where it will treat
a numeric value as a slug or an id, depending on what it finds in the
database. `--by=id` forces WordPress to explicitly handle the numeric
value as a term id.
Fixes #3716
=> Use `--by=id` to explicitly handle terms as ids

php/utils-wp.php
It's a helpful utility for memory management in long-running scripts.
=> Mark `WP_CLI\Utils\wp_clear_object_cache()` as public

features/scaffold.feature, php/commands/scaffold.php
=> Include `.editorconfig` when scaffolding themes

templates/plugin-distignore.mustache, templates/plugin-gitignore.mustache
SQL dumps shouldn't be committed to repos, nor included in distribution archives.
=> Ignore `*.sql` in scaffolded `.gitignore` and `.distignore`

features/user-import-csv.feature, php/commands/user.php
`wp user import-csv` includes a `--send-email` flag, which gives the
user control over when the email notification is sent. We should always
defer to this flag, which calls `wp_new_user_notification()`
independently.
Fixes #3903
=> Don't send core's email notifications during user import-csv

features/aliases.feature, php/WP_CLI/Configurator.php
From this example:
```
Given a wp-cli.yml file:
"""
path: testdir
@testdir:
path: testdir
"""
```
Both instances of 'path' should be made absolute. However, prior to this
changeset, only 'path' as a default value was made absolute. The 'path'
defined by the `@testdir` alias was relative.
=> Absolutize 'path' defined in an alias

features/scaffold-plugin-tests.feature, features/scaffold-theme-tests.feature, features/scaffold.feature, php/commands/scaffold.php, templates/plugin-circle.mustache, templates/plugin-readme.mustache, templates/plugin-travis.mustache
* Rebuilds `.travis.yml` file:
* Explicitly identify each job in the build matrix
* Run tests against PHP 7.1 and 7.0
* Only run `phpcs` once, instead of with every job
* Run multisite tests on each job
* Tested in https://github.com/wp-cli/sample-plugin/pull/6
* Scaffolds `circle.yml` to run against range of supported WP versions
* Also runs multisite tests for each job
* Tested in https://github.com/wp-cli/sample-plugin/pull/5 and https://github.com/wp-cli/sample-plugin/pull/7
* In default `readme.txt`, uses WP 4.4 as the minimum supported WP version
Fixes #3784
Fixes #3785
=> Variety of improvements to scaffolded `.travis.yml` and `circle.yml`

features/aliases.feature, features/post.feature, features/user-import-csv.feature
Pipe `wc` output through `tr` to delete the indentation, so that the output is consistent across all platforms and the tests all behave in the same way.
Fixes #3925
=> Fix broken tests by removing platform-specific indentation from `wc` output.

features/bootstrap/FeatureContext.php, php/boot-phar.php, php/utils.php, utils/make-phar.php
Used in https://github.com/wp-cli/package-command/pull/2
To verify in the `package-command` project:
```
git clone git@github.com:wp-cli/package-command.git
cd package-command
git checkout 1-phar-access
composer install
behat features/package-install.feature
cd vendor/wp-cli/wp-cli
git checkout phar-build-subproject
cd -
```
Here's the current test that fails: https://travis-ci.org/wp-cli/package-command/jobs/214240701
=> Permit WP-CLI to be built as a phar when dependency of another project

features/cli.feature
I think something changed in the Travis PHP 5.3 environment, and I don't
want to invest the time into tracking it down.
=> Require php-5.6 for failing nightly test

features/bootstrap/FeatureContext.php
Add Composer vendor folder to the include path to potentially load the `wp` binary locally if it was pulled in via Composer, instead of always preferring the global installation if available.
Fixes #3946
=> Add Composer vendor folder to the include path

ci/behat-tags.php
Fixes #3953 
Add processing to "utils/behat-tags.php" for "@require-extension" tags, as mentioned in wp-cli/media-command#4 (comment), to allow behat tests to be skipped if a required PHP extension isn't installed.
=> Add require-extension tag processing to behat-tags.

php/WP_CLI/Dispatcher/CompositeCommand.php, php/WP_CLI/SynopsisValidator.php, php/commands/option.php
patch contains some spelling fixes ( just in comments ) as found by a bot ( http://www.misfix.org, https://github.com/ka7/misspell_fixer ). Any upcoming License changes (e.g. GPL2 to GPL3+) are hereby granted.
=> spelling fixes

features/option.feature, php/commands/option.php
Doing so means our comparison conditional checks the correct value.
Fixes #3967
=> Replicate sanitization WordPress normally performs when fetching

composer.lock
```
- Updating symfony/filesystem (v2.8.18 => v2.8.19):  Checking out 31ab6827a6
- Updating symfony/debug (v2.8.18 => v2.8.19):  Checking out e90099a295
- Updating symfony/process (v2.8.18 => v2.8.19):  Checking out 41336b20b5
- Updating composer/spdx-licenses (1.1.5 => 1.1.6):  Checking out 2603a0d7dd
- Updating symfony/yaml (v2.8.18 => v2.8.19):	 Checking out 286d848916
- Updating symfony/translation (v2.8.18 => v2.8.19):	Checking out 047e97a64d
- Updating symfony/finder (v2.8.18 => v2.8.19):  Checking out 7131327eb9
- Updating symfony/event-dispatcher (v2.8.18 => v2.8.19):  Checking out 88b65f0ac2
- Updating …
```
=> Update Composer dependencies (2017-04-13)

features/flags.feature, php/WP_CLI/Configurator.php, php/utils.php
Sometimes it can be useful to be able to load files with a pattern rather than listing them all out explicitly.
With this PR, you could have something like this in your global config file `~/.wp-cli/config.yml`  for autoloading little one-off commands without any additional configuration:
```yml
require: dropins/*.php
```
It also supports usage with the `--require` flag as well.
This is also backwards compatible because a path that does not use a glob pattern is unaffected.
The utility function added could be useful in other commands as well!
=> Add support for globs in `require`

utils/auto-composer-update.sh
Produces a pull request like #3993
Fixes #3847 
Run on a cron job every Monday, Wednesday and Friday with:
```
5 4 * * 1,3,5 source ~/.bash_profile; WP_CLI_DIR=~/wp-cli bash ~/auto-composer-update.sh > ~/auto-composer-update.log 2>&1
```
=> Add `utils/auto-composer-update.sh` for updating on cron

php/commands/core.php
This matches the default password length for new WP installs.
See also: https://github.com/wp-cli/entity-command/pull/7
=> Generate 18 character password for admin user

utils/make-phar.php
This constant is dynamically set based on installation type.
See https://github.com/wp-cli/package-command/issues/7
=> Use `WP_CLI_VENDOR_DIR` to identify path to templates

php/boot-phar.php, php/utils.php
This function allows to retrieve a path by making sure it is adapted when used within a Phar archive.
This is meant to solve issues like https://github.com/wp-cli/scaffold-command/pull/10
Fixes #3987
=> Add `phar_safe_path()` function.

composer.lock
```
- Updating wp-cli/scaffold-command (v1.0.2 => v1.0.3):  Checking out bc3559120f
```
=> Update Composer dependencies (2017-05-01)

php/class-wp-cli.php
=> Document the possibility to add optional arguments to the `WP_CLI::do_hook()` call.

features/command.feature, php/WP_CLI/Dispatcher/CommandAddition.php, php/class-wp-cli.php
The following hooks have been added:
1. `before_add_command:<command>` - Called before WP_CLI tries to add the
command `<command>` to its known vocabulary.
The callback that is being called by this hook will receive an instance of
a `WP_CLI\Dispatcher\CommandAddition` object, which allows the callback to
control whether WP_CLI should proceed with the addition or not. On
aborting, the callback can provide a reason.
This can be used to let the addition of a command depend on some prior
requirement to be met.
2. `after_add_command:<command>` - Called after the command `<command>` has
been added to the known vocabulary.
This can be used for let the addition of the command depend on other
commands being added first. In this way, the addition of commands can be
rendered independent of loading …
=> Add command hooks mechanism for simple dependency resolution.

php/class-wp-cli.php
This is an experiment to look for a solution for better formatting the generated handbook.
See https://github.com/wp-cli/handbook/issues/32
=> Testing a different structure for array argument docblocks.

php/bootstrap.php
The bootstrap refactoring code did already contain a custom autoloader to get around the fact that the Composer autoloader was not yet active during bootstrap, but ... it did not actually use it.
This fixes that.
See #3850
=> Make use of the provided custom autoloader.

php/boot-fs.php, php/utils.php, tests/bootstrap.php, tests/test-bundled-commands.php
This function loads the Composer classmap we've built through the autoloader splitting functionality, and checks whether a given class is contained within that classmap.
It accepts both a fully qualified class name as a string, as well as an object that should be a subtype of `WP_CLI\Dispatcher\CompositeCommand`.
See #3886
=> Add `WP_CLI\Utils\is_bundled_command( $command )` function.

php/WP_CLI/Dispatcher/CommandExecutionLog.php, php/WP_CLI/Dispatcher/Subcommand.php, php/class-wp-cli.php
Some commands like `shell` are ended with the user killing the process
(meaning the command execution won't ever be logged).
Other commands kill the process early if there's an error.
I'd prefer we capture as much command execution as we can, and not worry
about execution time.
See #3886
=> Log command execution right away, instead of waiting for it to complete

ci/behat-tags.php
The approach of skipping this tag avoids needing a HTTP request to
resolve the latest version, and is functionally equivalent.
Fixes #3956
=> Only apply @require-wp tags when WP_VERSION isn't 'latest' or 'nightly'

composer.lock
```
- Updating wp-cli/extension-command (v1.0.1 => v1.0.2):  Checking out b57212c435
```
=> Update Composer dependencies (2017-05-12)

features/bootstrap/FeatureContext.php
Fixes #4048
From https://github.com/danielbachhuber/host-check-command/pull/13.
There's some grandchild process hanging around on Ubuntu (to do with `wp-cli-router.php`?), so recurse on `terminate_proc()` to remove it.
=> Recurse on terminate_proc.

features/bootstrap/FeatureContext.php
Issue https://github.com/wp-cli/wp-cli/issues/4080
=> Don't throw exception in terminate_proc() if error is ESCRH "No such process".

features/bootstrap/FeatureContext.php
Allow for dynamic values when creating a subdirectory install in a Behat scenario.
E.g. https://github.com/aaemnnosttv/wp-cli-valet-command/blob/5637efca1c1efd8ccc52adc7c01bc4774b0b043b/features/valet-destroy.feature#L5
Added in my command a while ago https://github.com/aaemnnosttv/wp-cli-valet-command/commit/4af4028cb3a16f1e4731ccb16141935284aa8179 but I think it would be useful to have in core as well.
=> Replace variables for subdirectory install path

utils/wp-cli-updatedeb.sh
Plus make it more error prone and readable
@danielbachhuber It came out during building 1.2.0
=> Update license file's name in wp-cli-updatedeb

features/command.feature, php/WP_CLI/Bootstrap/RegisterDeferredCommands.php
For the command additions within (mu-)plugins to work, they need to be
processed after all plugins have actually been loaded.
Fixes #4122
=> Also process deferred command additions on the `'after_wp_load'` hook.

php/class-wp-cli.php
As Composer will use a fixed require for any package files included in the Composer autoloader's `"files"` directive, we need to bail early in the `WP_CLI::add_command()` method so that WP-CLI is not executed from web-requests where it was included in the same `composer.json` file than the WP code itself.
See #4124
=> Bail early on `add_command()`.

ci/test.sh
It's not necessary to scan these files, and adds a huge amount of
unnecessary output to test runs.
=> Ignore vendor directories when running `phpcs`

features/bootstrap/FeatureContext.php, features/help.feature, php/commands/help.php, templates/man-params.mustache
Fixes #4127
Fixes wordwrapping for help, treating subcommand list separately.
Uses Shell::columns() instead of WP_CLI_HELP_WORDWRAP_WIDTH.
Exports TERM in FeatureContext::get_process_env_variables() so that Shell::columns() doesn't throw errors in tests (a separate PR will make Shell:columns() check TERM and work better in Windows).
Adds blank line after root_command in `man-params.mustache` to compensate for its loss with the new wordwrapping in 1.2.0.
Better tests so that this sort of thing is less likely in the future.
=> Fix help wordwrapping (subcommands especially). Use Shell:columns(). Export TERM.

php/WP_CLI/Bootstrap/IncludeFallbackAutoloader.php, php/WP_CLI/Bootstrap/IncludeFrameworkAutoloader.php
These should always the respective targeted autoloader filenames:
- Bundle: `autoload_commands.php`
- Framework: `autoload_framework.php`
- Fallback: `autoload.php`
Props @gitlost
=> Fix autoload file names for `$custom_vendor` condition

features/aliases.feature, features/flags.feature, features/skip-plugins.feature, php/WP_CLI/Runner.php
Issue https://github.com/wp-cli/wp-cli/issues/4146
Saves runtime config to new class var `runtime_config` (rather than local) which is then used in `Runner::run_alias_group()` to pass as args to sub-alias invocations.
Adds new debug message dumping `argv()` to make it easy to test that the args are being passed.
Also unrelatedly makes PHP erroring tests more local-testing friendly by setting any `error_log` to null before calling them so that the errors do actually end up in `behat`'s STDERR.
=> Save runtime config so can pass as args to Runner::run_alias_group() invocation.

php/utils.php, utils/make-phar.php
Issue https://github.com/wp-cli/wp-cli/issues/4168
Removes unneeded slash in "boot-phar.php" path.
Also removes any existing phar before populating - handy when using locally.
Also fixes typo error_log -> error in `Utiils::http_request()`.
=> Fix double slash in boot-phar.php path. 

php/WP_CLI/Runner.php
Prevents situations like this:
Because I've run `sudo wp cli update`, I shouldn't also need to include `--allow-root`.
=> Allow root use of `wp cli info`, in addition to `wp cli update`

php/WP_CLI/Runner.php, php/class-wp-cli.php, php/utils.php, tests/test-utils.php
Related #4091.
Add get_home_dir() function into Utils.
=> Add get home dir

php/commands/src/CLI_Command.php
We currently have 34 releases. If we continue to release 4x per year, it
will take us another 15 years to get to 100
See #4186
=> Fetch as many WP-CLI releases as we can

php/class-wp-cli.php
Make the example better by adding an associative argument parameter to illustrate its usage.
Original PR: https://github.com/wp-cli/handbook/pull/77
=> Better example for WP_CLI::add_command

php/utils.php, tests/test-utils.php
Related to #4180, changes the SSH parser regexp to allow port number to be missing.
=> SSH URL parser regexp changes to allow for null port number

php/WP_CLI/Process.php, php/WP_CLI/ProcessRun.php
This PR primarily adds/corrects inline documentation for the `WP_CLI\Process` and `\WP_CLI\ProcessRun` classes.
These properties should be defined on the classes for better documentation and inspectability.
=> Declare fields for properties of Process and ProcessRun

features/bootstrap/FeatureContext.php
This is something that I added for the `valet` command because I needed to be able to test creation and deletion of databases other than `wp_cli_test`. Rather than granting more permissions, I felt it would be much easier to just use different credentials. I think this could be useful in other situations as well.
In case you're wondering the ` !== false` check on the password var is to allow for an empty password to be set with `WP_CLI_TEST_DBPASS=""`, where the others cannot be empty.
E.g. https://github.com/aaemnnosttv/wp-cli-valet-command/blob/af1ee1123c3d2fa991a5d4a6ba982db14b966397/.travis.yml#L8-L11
=> Behat: Allow test DB user + pass to be set by env vars

php/WP_CLI/DocParser.php, tests/test-doc-parser.php
=> Allowed numbers to subcommand Sanitizing

features/flags.feature, features/skip-plugins.feature
Replaces single quotes with double on "error_log" param.
(Introduced by me  https://github.com/wp-cli/wp-cli/pull/4148)
=> Fix quotes on ini_set( error_log, null ).

features/flags.feature, php/WP_CLI/Runner.php
Fixes #4206 
Prefixes ssh command with `WP_CLI_STRICT_ARGS_MODE=1` if set locally.
=> Pass WP_CLI_STRICT_ARGS_MODE on to ssh if set.

utils/wp-cli-rpm.spec
Hello @murtzsarialtun !
It is not possible to match for example [Red Hat](https://access.redhat.com/sites/default/files/attachments/rpm_building_howto.pdf) and [Fedora Packaging Guidelines](https://fedoraproject.org/wiki/Packaging:Guidelines#Tags_and_Sections), they contradict.
I've chosen Fedora - seem more modern.
`%prep` is a hack that creates sources during the build process, similar to /utils/wp-cli-updatedeb.sh
=> Normalize spec file

features/bootstrap/FeatureContext.php, features/cli-info.feature, features/cli.feature, features/framework.feature, features/steps/given.php
Fixes https://github.com/wp-cli/wp-cli/issues/4210
Adds "Given an empty XXX directory" for use by `cli-info.feature` to clear `PACKAGE_PATH` so it's re-runnable.
Fixes `UPDATE_VERSION` in `cli.feature` to get the correct latest version.
Suppresses PHP notices in `framework.feature` thrown by `wp-db.php`.
(Also needs https://github.com/wp-cli/wp-cli/pull/4208 to remove noise completely.)
=> Make tests runnable locally without errors or noise.

features/cli.feature
Adds test that `wp cli update` when on latest stable returns "WP-CLI is at the latest version." (there's one for `check-update`).
=> Add test that cli update on stable gives at latest version message.

php/WP_CLI/Dispatcher/Subcommand.php, php/WP_CLI/DocParser.php
For issue #4220 
This isn't tested, except in my home environment. The super-critical parts are
php/WP_CLI/Dispatcher/CommandFactory.php
php/WP_CLI/Dispatcher/Subcommand.php:30 `preg_match_all( '/(.+?)\R+:/', $longdesc, $matches );`
php/WP_CLI/DocParser.php:73
This also fixes the wp help command, which screwed up indentation on win systems, regardless of line endings in file.
=> Fixed line endings

.gitattributes, php/WP_CLI/DocParser.php, tests/data/commandfactory-doc_comment-class-win.php, tests/data/commandfactory-doc_comment-function-win.php, tests/test-commandfactory.php
Issue https://github.com/wp-cli/wp-cli/issues/4220 and PR https://github.com/wp-cli/wp-cli/pull/4221.
Uses `str_replace()` instead of `preg_replace()`.
Adds Windows tests to `CommandFactoryTests`, including DOS formatted test files.
=> Use str_replace instead of preg_replace to normalize doc comment EOLs.

features/cli-info.feature, features/runner.feature, php/WP_CLI/FileCache.php, php/WP_CLI/Runner.php, php/class-wp-cli.php, php/utils.php, tests/test-file-cache.php, tests/test-utils.php
As mentioned in https://github.com/wp-cli/core-command/pull/22, adds `Utils\trailingslashit()` from WP core.
Uses it, in particular in `Utils\get_temp_dir()` (its version was wrong) and also couldn't resist simplifying that function so that it saves the slashed version to the static, saving vital microcycles.
=> Add Utils\trailingslashit() and use it.

composer.lock
```
- Updating symfony/debug (v2.8.24 => v2.8.25):  Checking out 8470d77011
- Updating symfony/filesystem (v2.8.24 => v2.8.25):  Checking out 714b103601
- Updating symfony/process (v2.8.24 => v2.8.25):  Checking out 57e52a0a6a
- Updating symfony/yaml (v2.8.24 => v2.8.25):	 Checking out 4c29dec8d4
- Updating symfony/translation (v2.8.24 => v2.8.25):	Checking out a89af885b8
- Updating symfony/finder (v2.8.24 => v2.8.25):  Checking out 4f4e848110
- Updating symfony/event-dispatcher (v2.8.24 => v2.8.25):  Checking out 1377400fd6
- Updating symfony/dependency-injection (v2.8.24 => v2.8.25):	 Checking out db8bdcfc6f
- Updating symfony/console (v2.8.24 => v2.8.25): …
```
=> Update Composer dependencies (2017-07-19)

features/bootstrap/FeatureContext.php, features/cli-info.feature, features/steps/given.php
Adds `remove_dir()` and `copy_dir()` wrappers to make deleting/copying consistent (as threatened in https://github.com/wp-cli/wp-cli/pull/4211#issuecomment-314451799).
Cleans up `SUITE_CACHE_DIR` and `COMPOSER_LOCAL_REPOSITORY` being left behind in `/tmp`, adding statics for `RUN_DIR` and `COMPOSER_LOCAL_REPOSITORY` to more easily keep track.
Makes `COMPOSER_LOCAL_REPOSITORY` persist till end of suite (think this is ok?).
Uses PHP `mkdir()` instead of shelling out.
Extends "Given an empty directory" to allow "non-existent" as well, and uses it in `cli-info.feature`. Also tightens the check so that directory must be in temp dir.
Adds `get_event_file()` to get current feature file and line no. and uses in names of `RUN_DIR` & `SUITE_CACHE_DIR`.
Adds some doc on the various …
=> Add remove_dir() & copy_dir() fo FeatureContext. Cleanup temp dirs. Docs.

php/WP_CLI/Dispatcher/CompositeCommand.php, php/WP_CLI/Extractor.php, php/WP_CLI/Formatter.php, php/WP_CLI/Iterators/Table.php, php/WP_CLI/PackageManagerEventSubscriber.php, php/WP_CLI/Process.php, php/WP_CLI/Runner.php, php/WP_CLI/SynopsisValidator.php, php/WP_CLI/WpHttpCacheManager.php, php/class-wp-cli.php, php/commands/help.php, php/commands/src/CLI_Command.php, php/utils.php, php/wp-settings-cli.php, phpcs.ruleset.xml
Some new sniffs that shipped in WPCS `0.12.0` raise errors on existing code. This PR updates code so that it will pass checks with PHPCS 0.12.0.
It adds one new sniff to the ignore list in `phpcs.ruleset.xml`: `WordPress.WP.CapitalPDangit`. Otherwise, the following line would raise an error, which seems like a spurious objection:
https://github.com/wp-cli/wp-cli/blob/master/php/utils-wp.php#L299
=> Address new sniffs in WPCS 0.12.0

features/flags.feature, features/help.feature, php/WP_CLI/Runner.php, php/commands/src/CLI_Command.php, php/config-spec.php, php/utils.php, tests/test-utils.php
- Introduce a new `<scheme>:` prefix to the connection string provided to `--ssh`. Current accepted values are `docker:`, `docker-compose:`, and `ssh:`. This prefix can be omitted and a default of `ssh:` will be assumed.
- Additionally make the `<user>@` option an explicit value separate from `<host>` so that it can be passed via CLI flag to Docker processes.
- Refactor the `Runner#run_ssh_command` method to respond to different schemes.
- Update existing functional test to accept escaped output. (Debug output of the unescaped command was removed during refactor to simplify the implementation.)
- Add unit tests for updated `parse_ssh_url`.
- Add functional test for `docker:` prefix.
- Remove `--ssh` global flag from 40-column wrap test. The help text for the `--ssh` flag is now an …
=> Adapt --ssh flag to work with Docker and Docker Compose.

composer.json, composer.lock, features/formatter.feature, php/WP_CLI/Formatter.php
Issue https://github.com/wp-cli/php-cli-tools/issues/106
This uses the pre-colorized stuff added in https://github.com/wp-cli/php-cli-tools/pull/111. Adds `ascii_pre_colorized` arg to the various display functions in `Formatter` which eventually gets passed to `show_table()` which just calls `Table::setAsciiPreColorized()` with it. 
So if you have an Ascii table with some pre-colorized columns you can do eg `$table->display_items( $items, array( true, false, true ) )` to indicate that the padding should be adjusted for them.
=> Incorrect table column width calculcations with colorized strings.

php/commands/src/CLI_Command.php
From:
> Manage WP-CLI itself.
To:
> Review current WP-CLI info, check for updates, or see defined aliases.
=> Use a more helpful description for `wp cli *`

composer.json, composer.lock
=> Bump minimum version for the wp-cli/autoload-splitter package.

composer.lock
```
- Updating symfony/debug (v2.8.25 => v2.8.26):  Checking out 236ca98a42
- Updating symfony/filesystem (v2.8.25 => v2.8.26):  Checking out 714b103601
- Updating symfony/process (v2.8.25 => v2.8.26):  Checking out 57e52a0a6a
- Updating wp-cli/php-cli-tools (v0.11.4 => v0.11.5):	 Checking out c5f9c034fd
- Updating symfony/yaml (v2.8.25 => v2.8.26):	 Checking out 4c29dec8d4
- Updating symfony/translation (v2.8.25 => v2.8.26):	Checking out a89af885b8
- Updating symfony/finder (v2.8.25 => v2.8.26):  Checking out 4f4e848110
- Updating symfony/event-dispatcher (v2.8.25 => v2.8.26):  Checking out 1377400fd6
- Updating symfony/dependency-injection (v2.8.25 => …
```
=> Update Composer dependencies (2017-08-02)

.travis.yml
Travis CI : lock wp-coding-standards/wpcs version to 0.11.0
=> Travis CI : lock wp-coding-standards/wpcs version to 0.12.0

php/class-wp-cli.php
From https://github.com/wp-cli/handbook/pull/111
=> Fix typo in method docs

features/help.feature
After the `Shell::columns()` change in `php-cli-tools` https://github.com/wp-cli/php-cli-tools/pull/118 the tests for default wrapping on help will probably fail locally as the `stty` will probably work, so this changes the 2 cases to explicitly set `COLUMNS` to 80.
=> Set COLUMNS=80 on wp help wrapping tests to ensure run locally.

features/bootstrap/FeatureContext.php, php/commands/src/CLI_Command.php
Related https://github.com/wp-cli/wp-cli/pull/4187.
See also https://github.com/wp-cli/wp-cli/blob/master/utils/contrib-list.php#L193
Adds `GITHUB_TOKEN` to `CLI_Command::get_updates()` and passes through in `FeatureContext::get_process_env_variables()` to avoid github request rate limiting - useful in itself and also needed for when `github-api` tests are enabled on Travis.
=> Add GITHUB_TOKEN to CLI_Command::get_updates and get_process_env_variables.

features/help.feature, php/WP_CLI/Runner.php, php/utils-wp.php
PR https://github.com/wp-cli/wp-cli/pull/4266 and issue https://github.com/wp-cli/wp-cli/issues/4265
Adds a `help_wp_die_handler` to try to trap errors during WP load, especially db select fails when have a partial WP install. (See https://github.com/wp-cli/wp-cli/blob/master/features/help.feature#L49).
(It could also be used to get `wp core is-installed` to work in this situation if a check were added to that command to see if WP function `wp_cache_get()` exists before calling `is_blog_installed()` but don't know if it's worth it?)
Removes the special handling for `help config` and `help db`, but expands the special handling for `help core install/multisite-install/verify-checksum/version` to all `help command subcommand`s on "First try at showing man page" as if they exist the help will …
=> Add help_wp_die_handler. Remove special help treatment for config and db (#4266).

features/bootstrap/FeatureContext.php, features/cli-info.feature
Replaces hard-coded `/tmp` with `sys_get_temp_dir()` in setting `HOME` in `FeatureContext::get_process_env_variables()`.
Also replaces hard-coded `/tmp` in `features/cli-info.feature` with `{PACKAGE_PATH}`.
=> Replace /tmp with sys_get_temp_dir() in get_process_env_variables().

features/bootstrap/FeatureContext.php
Caches the WP download in `FeatureContext::cache_wp_files()` to a WP version specific directory if `WP_VERSION` is set.
This is handy for local testing where at the moment you have to delete the `/tmp/wp-cli-test-core-download-cache` first before trying to test different WP versions with eg `WP_VERSION=3.9 vendor/bin/behat`, and then redelete it afterwards.
=> Cache the WP download to a WP_VERSION specific directory.

README.md
=> Link to a public document instead of one that requires auth

features/command.feature, features/flags.feature, features/help.feature, php/WP_CLI/Runner.php, php/commands/help.php, php/utils-wp.php
Issue https://github.com/wp-cli/wp-cli/issues/4265 and PR https://github.com/wp-cli/wp-cli/pull/4291
This is the same PR as the original PRs https://github.com/wp-cli/wp-cli/pull/4266 and https://github.com/wp-cli/wp-cli/pull/4285 but defining `WP_DEBUG` (and `WP_DEBUG_DISPLAY`) instead of `WP_ADMIN` on `help` to get WP to use `wp_die()` so its error message can be trapped. 
It differs from the original try https://github.com/wp-cli/wp-cli/pull/4291/commits/571de94fc8ba3cc2dd0cede69835666c175381ea in that the define is only done when WP's "wp-settings.php" is loaded instead of "wp-settings-cli.php", as the latter checks for a db error immediately after `require_wp_db()` and uses `wp_die()` - added in https://github.com/wp-cli/wp-cli/pull/352 and for the same reason i.e. that `dead_db()` …
=> Give suggestions when exiting early on `wp help`

utils/make-phar.php
Makes phar executable (handy for local running) and doesn't output generated message if `BE_QUIET` set.
=> make-phar.php: chmod executable & no generated msg if BE_QUIET.

features/aliases.feature, features/bootstrap/FeatureContext.php, features/config.feature, features/runcommand.feature
For consideration/discussion.
Adds caching of single-site installs of WP in tests for performance reasons.
The basic algorithm is to save `wp-config.php`, any files/directories added during install, and a `mysqldump` of the database, to an install cache, keyed by options and sub-directory, and then use them to do a WP install rather than calling `wp core install` each time.
It assumes that the only file whose contents change is `wp-config.php`, which is true now and back to WP 3.7.11, but obviously may change. Currently the only other files added are `wp-content/mu-plugins/no-mail.php` and a blank `wp-content/uploads/<year>/<month>/` directory.
Also standardizes the names of sub-directory installs to `foo` and `bar` (instead of the various `testdir`, `subdir`, `core` etc used in …
=> Add caching of WP installs in FeatureContext to speed-up tests.

features/hook.feature, php/class-wp-cli.php
I added `WP_CLI::add_hook( 'before_invoke:<command>', $callback );` to some command.
Then I found the some commands doesn't fire some hooks.
For example, `wp plugin *` fires the `before_invoke` hook, but `wp db *` and `wp core *` don't fire the same hook.
Is it problem that should be solved or we need to improve the documentation?
=> Add more tests to declare explicit behavior of `WP_CLI::add_hook()`

features/bootstrap/FeatureContext.php, php/WP_CLI/Process.php, php/WP_CLI/ProcessRun.php
Adds logging of process run times to `FeatureContext`, useful for detecting slow tests and suggesting where things could be speeded up.
The logging is triggered by setting the `WP_CLI_TEST_LOG_RUN_TIMES` environment variable, which can take a formatted value setting some output options (where to output to, no. of slowest processes to show, no. of slowest scenarios to show).
By default it logs to `error_log` for local testing, and `STDOUT` on Travis.
Adds run time info to `Process` (whose `run()` is changed a bit) and `ProcessRun`.
Also fixes a bug in `FeatureContext::get_event_file()` where it wasn't allowing for Scenario Outlines.
=> Add WP_CLI_TEST_LOG_RUN_TIMES run time stats to FeatureContext.

php/utils.php, tests/test-utils.php
See https://github.com/wp-cli/export-command/pull/13#issuecomment-324689315
Adds url to `Utils\http_request()` error message as it's helpful to know.
Re-tries without verify only if error is due to a local CAcert issue. (See https://curl.haxx.se/libcurl/c/libcurl-errors.html).
Note adds a test re local CAcert issue but it relies on a hack re `Utils\get_vendor_paths()`, creating a `pem` file outside the current project, so it may be best to leave it out.
=> http_request: add url to error msgs, only re-try if local CACert issue.

ci/test.sh, tests/bootstrap.php, tests/phpunit6-compat.php
Related https://github.com/wp-cli/php-cli-tools/pull/118 and https://core.trac.wordpress.org/ticket/39822
Makes unit tests PHPUnit 6 compatible, and runs the default `phpunit` on Travis.
`phpunit6-compat.php` is the same as core's version, without the core-specific `PHPUnit_Util_Test::getTickets()`.
(Have left the `composer.json` phpunit requirement alone, not sure what to do there.)
=> Make unit tests PHPUnit 6 compat.

ci/prepare.sh
See issue https://github.com/wp-cli/scaffold-package-command/issues/142, PR https://github.com/wp-cli/scaffold-command/pull/49 and https://core.trac.wordpress.org/changeset/41177
Checks that xdebug is installed before disabling in `ci/prepare.sh`, otherwise will get error. (Currently the Travis PHP 7.2 beta doesn't install xdebug by default.)
=> Check for xdebug before disabling in ci/prepare.sh.

composer.lock
```
- Updating symfony/debug (v2.8.26 => v2.8.27):  Checking out efc9656dcb
- Updating symfony/filesystem (v2.8.26 => v2.8.27):  Checking out 714b103601
- Updating symfony/process (v2.8.26 => v2.8.27):  Checking out 57e52a0a6a
- Updating symfony/yaml (v2.8.26 => v2.8.27):	 Checking out 4c29dec8d4
- Updating symfony/translation (v2.8.26 => v2.8.27):	Checking out a89af885b8
- Updating symfony/finder (v2.8.26 => v2.8.27):  Checking out 4f4e848110
- Updating symfony/event-dispatcher (v2.8.26 => v2.8.27):  Checking out 1377400fd6
- Updating symfony/dependency-injection (v2.8.26 => v2.8.27):	 Checking out fbeea992f0
- Updating symfony/console (v2.8.26 => v2.8.27): …
```
=> Update Composer dependencies (2017-08-30)

features/prompt.feature, php/WP_CLI/Dispatcher/Subcommand.php
It's unexpected behavior to enter a lowercase 'y' and have the flag passed as a null value
Fixes #4333
=> Support upper- and lowercase 'Y' when prompting a flag

phpcs.xml.dist
Three improvements:
- Add progress indicator flag which makes local running of PHPCS more user-friendly
- Add summary and source reports, which help to identify which files have issues, and which issues occur the most (and includes a count of how many can be auto-fixed with `phpcbf`)
- Organise the `phpcs.xml.dist` so that exclude patterns follow the `file` (what's included).
See #4335
=> Phpcs.xml.dist improvements

php/WP_CLI/Runner.php, php/utils.php, tests/test-utils.php
This adds support for a vagrant scheme, which uses vagrant to define ssh connection parameters via `vagrant ssh`.
This can either be used via a cli arg: `wp --ssh=vagrant:default shell` or via wp-cli.yml as `ssh: vagrant:default`. `default` here being the vagrant machine ID.
I'm not sure where best to document that, let me know if I can help with that.
=> Add support for running commands over inside vagrant ssh

php/utils.php, tests/test-utils.php
Issue https://github.com/wp-cli/wp-cli/issues/4338
Adds utils function `past_tense_verb()` to pastify verbs better for `report_batch_operation_results()`.
=> Add past_tense_verb() utils func for report_batch_operation_results().

features/prompt.feature
Related PR https://github.com/wp-cli/wp-cli/pull/4334
Just checks for "(bool)true" in `features/prompt.feature:3` to allow for running locally with xdebug enabled (which outputs the filename/line number as well on `var_dump()`).
=> Allow for xdebug locally enabled in lowercase prompt test.

composer.json, composer.lock
If this package should be tested against PHPCS + WPCS, then these development dependencies should be available locally, and not rely on a contributor having it available globally, with what might be out of date versions.
WPCS is stable enough to facilitate a version of `dev-develop`, but I've stuck with the latest tag for now, so that new fixes can be applied in a controlled manner.
The DealerDirect Composer plugin allows the automatic registration of code standards that include the `type` of `phpcodesniffer-standard`, and is recommended by WPCS.
Replaces part of #4335.
=> Composer: Add WPCS as a local dev dependency

php/class-wp-cli.php
PHPStorm was complaining about expecting a string as a callable, while any callable actually works.
=> Change type in docs for $callable to callable

php/WP_CLI/Extractor.php
In certain systems, `PharData` fails on invalid archives that `tar` can
successfully handle.
See #4370
=> Fail back to `tar xz` when `PharData` throws an Exception

features/cli.feature, php/commands/src/CLI_Command.php
I've created a recursive function that traverses the array of the dump output by `self::command_to_array( WP_CLI::get_root_command() )`
See #4283
=> Introduce `wp cli has-command` to detect whether a command is registered

php/utils.php
See https://github.com/wp-cli/core-command/issues/35#issuecomment-332932525
=> Introduce new 'halt_on_error' to overload exit

features/command.feature, tests/test-make-phar-strip-comments.php, utils/make-phar-strip-comments.php, utils/make-phar.php
Issue https://github.com/wp-cli/ideas/issues/61
Strips non-essential comments (ie those not in commands) and squeezes whitespace from PHP source in `utils/make-phar.php`, to reduce the size of the WP-CLI phar.
Does this conservatively, keeping line numbers the same so any error reports match and keeping tabs so that the source remains readable if you open it in an editor (if you're into that sort of thing) and keeping at least one space on squeezing whitespace so there's no possibility of triggering one of the (very few) disambiguity requirements PHP has.
Also keeps any copyright/license comments.
=> make-phar: strip non-essential comments and squeeze whitespace.

php/utils.php, tests/test-wp-version-compare.php
=> Add tests around `Utils\wp_version_compare()`; strip '-src' for compare

php/utils.php
Hey folks!
This PR seeks to get the ball rolling on (or resolve) this issue: https://github.com/wp-cli/wp-cli/issues/4379
Per  Alain's leading, I've added in the `$suggestion_map` array and the return check. 
Several items in the array are used across different commands (e.g., `wp post new` and `wp db new` would both return the correct suggestion: `Did you mean 'create'?`
I've label this as a WIP, so happy to make edits or expand this. 
Thanks!
Nate
=> [WIP] add suggestion_map array to php/utils.php

php/WP_CLI/Extractor.php
Method call (`getFileName()`) does not respect case of method [declaration](http://php.net/manual/en/splfileinfo.getfilename.php) (`getFilename()`).
=> Case mismatch in function/method call

php/WP_CLI/Bootstrap/AutoloaderStep.php, php/WP_CLI/Bootstrap/RegisterFrameworkCommands.php
[`WP_CLI::warning()`](https://github.com/wp-cli/wp-cli/blob/7f4c4e4b674a8a993cfb1ff719b9d2dac72a4f7f/php/class-wp-cli.php#L709) only accepts a single parameter.
https://github.com/wp-cli/wp-cli/blob/7f4c4e4b674a8a993cfb1ff719b9d2dac72a4f7f/php/class-wp-cli.php#L709
=> Fix parameters number mismatch declaration

php/WP_CLI/Bootstrap/BootstrapState.php, php/class-wp-cli.php, php/utils.php, phpcs.xml.dist
Only one function, and three methods, were found to be violating the preferred WPCS naming conventions, so these lines have been excluded.
While it does mean that the rest of the function signature line is also excluded from other checks, this seems like less of an issue than excluded the whole check from the rest of the project, which may allow other incorrectly named functions and methods to be accidentally introduced.
Once https://github.com/squizlabs/PHP_CodeSniffer/issues/604 is addressed, these ignores should be able to target just the specific check of the function / method name.
Related: #4058.
=> CS: Unexclude ValidFunctionName checks

php/WP_CLI/Iterators/CSV.php, php/commands/help.php, php/utils.php
From [official documentation](http://php.net/manual/en/function.fopen.php):
"The default translation mode depends on the SAPI and version of PHP that you are using, so you are encouraged to always specify the appropriate flag for portability reasons."
"For portability, it is strongly recommended that you always use the 'b' flag when opening files with fopen()."
=> Use binary-safe fopen

php/commands/src/CLI_Command.php
Non-static methods should not usually be called via `::`, but as a method call on an object / `$this`.
https://github.com/wp-cli/wp-cli/blob/7f4c4e4b674a8a993cfb1ff719b9d2dac72a4f7f/php/commands/src/CLI_Command.php#L30
=> Fix dynamic methods invocation via ::

php/utils.php
No point assigning a value to a variable, and then returning the variable, when we can just return the value.
=> Remove redundant one-time use variable

php/WP_CLI/Completions.php, php/WP_CLI/Configurator.php, php/WP_CLI/Dispatcher/Subcommand.php, php/WP_CLI/Iterators/Query.php, php/WP_CLI/Iterators/Table.php, php/WP_CLI/Loggers/Regular.php, php/WP_CLI/NoOp.php, php/WP_CLI/UpgraderSkin.php, php/commands/help.php, php/commands/src/CLI_Command.php
Of itself, the changes here shouldn't have much impact, but it allows future code to be inspected / checked to ensure that access modifiers are explicitly defined.
It also provides consistency with the (far more) methods that are already explicitly defined as being public.
=> Define missing access modifiers for methods

php/WP_CLI/Autoloader.php
Avoids multiple calls to `str_replace()`, especially as this is within a `foreach` loop.
=> Cascading string replacements can be merged

php/utils.php
From [official documentation](http://php.net/manual/en/function.mt-rand.php):
"The `mt_rand()` function is a drop-in replacement for the older `rand()`. It uses a random number generator with known characteristics using the » Mersenne Twister, which will produce random numbers four times faster than what the average libc `rand()` provides."
=> Use mt_rand() instead of rand()

php/WP_CLI/Runner.php
http://php.net/manual/en/migration70.incompatible.php#migration70.incompatible.variable-handling.global shows that variable variables can no longer be used with the `global` keyword for PHP 7.0 or later. The curly brace syntax can be used to emulate the previous behaviour.
It's a simple change, but this one needs double-checking, please.
=> Avoid global variable variable

features/runcommand.feature, php/WP_CLI/Loggers/Base.php, php/WP_CLI/Loggers/Execution.php, php/WP_CLI/Runner.php, php/class-wp-cli.php, tests/test-logging.php
Related https://github.com/wp-cli/media-command/pull/48#discussion_r142796610
On writing a unit test for adding the `$skips` arg to `Utils\report_batch_operation_results()`, I noticed that `Loggers\Execution` doesn't actually capture STDOUT for `WP_CLI::success()` as the implementation https://github.com/wp-cli/wp-cli/blob/v1.3.0/php/WP_CLI/Loggers/Execution.php#L34 calls `_line()` with the default handle `STDOUT`, rather than the string `'STDOUT'` expected by the overridden `write()`.
And `WP_CLI::runcommand()` on `--no-launch` doesn't use the captured stdout anyway from `Execution` but just does a `ob_start()` and `ob_get_clean()` https://github.com/wp-cli/wp-cli/blob/v1.3.0/php/class-wp-cli.php#L1168 to capture the output buffer, which is used by `echo`, `print` and `printf` but not by …
=> Make Execution logger capture WP::success and optionally output buffer.

phpcs.xml.dist
[This line in WPCS FileNameSniff.php](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/31f18a7168ecff69a738d7fa7687bb56902241ed/WordPress/Sniffs/Files/FileNameSniff.php#L164) shows that setting the `strict_class_file_names` property to `false` means the code that does the `InvalidClassFileName` check is not even run. It's a more efficient way to skip over the fact the class files here are not named per the WP Handbook.
WPCS has it [documented in the wiki](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Customizable-sniff-properties#disregard-class-file-name-rules).
The moved `exclude` could be left where it was, but it made just as much sense to keep the filename-checking tweaks together.
=> CS: Exclude class file name checks more efficiently

php/WP_CLI/Bootstrap/IncludeFrameworkAutoloader.php, php/WP_CLI/Runner.php, php/commands/help.php, php/commands/src/CLI_Command.php, php/utils.php
- [`fputs()`](http://php.net/manual/en/function.fputs.php) is an alias of [`fwrite()`](http://php.net/manual/en/function.fwrite.php).
- [`is_writeable()`](http://php.net/manual/en/function.is-writeable.php) is an alias of [`is_writable()`](http://php.net/manual/en/function.is-writable.php).
=> Avoid using alias functions

php/WP_CLI/AutoloadSplitter.php, tests/test-autoload-splitter.php
Two commits - the first is fine, but the second one may be too strict.
1. Remove leading and trailing .*:
- With no pinning of the pattern to the start or end of a string, the leading and trailing `.*` are redundant.
2. Ensure filename has at least one name before command:
- This tightens the regex to disallow:
- `/wp-cli/-command/`
- `/wp-cli/foo--command/`
- etc.
=> Improve AutoloadSplitter regexes

php/utils.php, tests/test-utils.php
See https://github.com/wp-cli/media-command/pull/48#pullrequestreview-67211889
Adds `$skips` arg to `Utils\report_batch_operation_results()` to report the number of items skipped. Also adds reporting of the number of items that failed.
The default has been to set to null which suppresses the reporting of failed items, for back compat with current behaviour. If temporarily breaking the tests for the commands that test for this (`entity-command`, `extension-command`, `media-command` and `widget-command`) is okay, then the default should be zero instead.
=> Add skips arg to Utils\report_batch_operation_results().

php/WP_CLI/Dispatcher/Subcommand.php, php/WP_CLI/WpHttpCacheManager.php, php/utils.php, php/wp-settings-cli.php
Slightly more opinionated, in that, although WP Core tends to use parentheses for `include`/`require`, it's not actually mentioned in the [Handbook](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/), and they are redundant from a PHP language perspective regardless.
Removing them for `include`/`require` does mean that inspections make it easier to see other instances of redundant parentheses (as per the other files in this PR).
=> Remove unnecessary parentheses

php/WP_CLI/Completions.php, php/WP_CLI/Configurator.php, php/WP_CLI/Dispatcher/Subcommand.php, php/WP_CLI/FileCache.php, php/WP_CLI/Iterators/Query.php, php/WP_CLI/Runner.php, php/WP_CLI/SynopsisParser.php, php/WP_CLI/WpHttpCacheManager.php, php/class-wp-cli.php, php/utils.php
Certain if-else conditions can have their else clause removed without changing the semantic. Generally, this is because the preceding `if` clause returns, continues, breaks, exits or throws.
=> Remove redundant else keyword

.travis.yml, ci/test.sh, composer.json, composer.lock, phpcs.xml.dist
This checks that all code in the project is compatible with PHP 5.3 and later.
The only other issue that was flagged by PHPCompatibility is fixed via #4401, so that should be merged first. Travis tests will likely fail until that is done.
=> CS: Add PHP Compatibility Check for 5.3+

tests/test-make-phar-strip-comments.php, utils/make-phar-strip-comments.php
Fixes https://github.com/wp-cli/scaffold-package-command/issues/149
From #4391
=> Don't strip Behat annotations when building the Phar file

composer.lock
```
- Updating symfony/polyfill-mbstring (v1.5.0 => v1.6.0):  Checking out 2ec8b39c38
```
=> Update Composer dependencies (2017-10-18)

features/help.feature, php/WP_CLI/DocParser.php, tests/test-doc-parser.php
Fixes #4336
It will be like following for now.
```
$ bin/wp help role
NAME
wp role
DESCRIPTION
Manages user roles, including creating new roles and resetting to defaults.
SYNOPSIS
wp role <command>
SUBCOMMANDS
create      Create a new role.
delete      Delete an existing role.
exists      Check if a role exists.
list        List all roles.
reset       Reset any default role to default capabilities.
See references for [Roles and Capabilities][1] and [WP User class][2].
---
[1] https://codex.wordpress.org/Roles_and_Capabilities
[2] https://codex.wordpress.org/Class_Reference/WP_User
EXAMPLES
...
```
=> Improve to display long description which has reference links

php/WP_CLI/FileCache.php, tests/test-file-cache.php
If `wp core download` has an error to make cache directory by some reason, warning is not useful for us.
```
$ wp core download
Warning: mkdir(): Permission denied in phar:///tmp/wp-cli.phar/php/WP_CLI/FileCache.php on line 265
md5 hash verified: 2e8744a702a3d9527782d9135a4c9544
Success: WordPress downloaded.
```
This PR will try to improve this warning like following.
```
$ wp core download
Downloading WordPress 4.8.2 (en_US)...
md5 hash verified: 2e8744a702a3d9527782d9135a4c9544
Warning: You don't have permission to make directory at "/Users/miyauchi/.wp-cli/cache/core".
Success: WordPress downloaded.
```
=> show warning when it couldn't make cache dir

tests/test-utils.php
Related https://github.com/wp-cli/wp-cli/pull/4327
Reduces timeout on bad address request in `testHttpRequestBadAddress()` phpunit test to minimize delay (can be noticeable when running locally).
Also marks `testHttpRequestBadCAcert()` as skipped if curl not available as it's curl dependent.
=> Use short timeout for bad address request test.

features/help.feature, php/commands/help.php, tests/test-help.php
Related: #4336 #4444 
Note: It will parse at the head of description only.
Example:
```
This is a [reference link](https://wordpress.org/) and [second link](http://wp-cli.org/).
It should be displayed very nice!
It doesn't expect to be link here like [reference link](https://wordpress.org/).
```
Result:
```
This is a [reference link][1] and [second link][2].
It should be displayed very nice!
---
[1] https://wordpress.org/
[2] http://wp-cli.org/
It doesn't expect to be link here like [reference link](https://wordpress.org/).
```
=> Improve long desc

features/help.feature
Fix for issue https://github.com/wp-cli/wp-cli/issues/4466
I attached not only `| awk '{print length, $0}' | sort -nr | head -1` but also `| cut -f1 -d" "` to retrieve number only.
=> use awk instead of `wc -L`

README.md
`$` is only necessary when the example includes sample output too.
=> Remove `$` from examples meant to be directly copy/pasted

features/command.feature, php/WP_CLI/Dispatcher/CommandFactory.php, php/WP_CLI/Dispatcher/CommandNamespace.php, php/class-wp-cli.php
A command namespace is a command placeholder that can receive annotations, sub-commands and all other shenanigans that a normal composite command can have, with the following changes:
* A namespace will never replace a previously added command of the same name.
* A namespace will always be replaced by a command of the same name that is added later.
* An empty namespace shows a corresponding notice when invoked.
See #4385
=> Initial implementation of command namespaces.

features/framework.feature, php/WP_CLI/Runner.php
The latter isn't ever accurate in CLI context.
Fixes #4459
=> Generate `get_site_url()` without `set_url_scheme()`

features/command.feature
Related https://github.com/wp-cli/wp-cli/pull/4458
Uses "contain" not "be" to allow for varying formats of `var_dump()` when xdebug is enabled (for local testing) in `features/command.feature`.
=> Allow for var_dump format varying under xdebug in command tests.

features/bootstrap/FeatureContext.php, php/WP_CLI/Runner.php, php/class-wp-cli.php, php/commands/src/CLI_Command.php, php/utils.php, tests/test-utils.php, tests/test-wp-cli.php
Related https://github.com/wp-cli/wp-cli/pull/4481
Moves body of `WP_CLI::get_php_binary()` to `Utils\get_php_binary()` and removes version in `FeatureContext` to DRY up code, leaving stub `WP_CLI::get_php_binary()` for BC. Also changes it to return full Windows path (ie includes `.exe` extension) for PHP 5.3 for easier testing.
Also exports `WP_CLI_PHP_USED` and `WP_CLI_PHP` in `Feature::get_process_env_variables()` as could be useful for testing different PHP versions locally.
=> Move get_php_binary() to Utils to DRY code.

composer.json
Related https://github.com/wp-cli/wp-cli/pull/4488
Changes the require of `db-command` in `composer.json` back to `1.0`, in the hope of eventually getting the builds to work.
=> wp-cli/db-command dev-15-after-wp-config-load -> 1.0

composer.lock
```
- Updating wp-cli/db-command (dev-15-after-wp-config-load af36459 => v1.3.0):	 Checking out 7121cfdc0a
```
=> Update Composer dependencies (2017-11-06)

php/utils.php, tests/test-utils.php
When we use the ssh with scheme `vagrant`, it can get the hostname automatically like following.
```
$ wp theme list --ssh=vagrant:/var/www/html
+-----------------+----------+--------+---------+
| name            | status   | update | version |
+-----------------+----------+--------+---------+
| twentyeleven    | inactive | none   | 2.7     |
| twentyfifteen   | inactive | none   | 1.9     |
| twentyfourteen  | inactive | none   | 2.1     |
| twentyseventeen | active   | none   | 1.4     |
| twentysixteen   | inactive | none   | 1.4     |
| twentyten       | inactive | none   | 2.4     |
| twentythirteen  | inactive | none   | 2.3     |
| twentytwelve    | inactive | none   | 2.4     |
+-----------------+----------+--------+---------+
Connection to 127.0.0.1 closed.
```
=> Get the hostname automatically with `vagrant ssh-config`

features/framework.feature, php/utils-wp.php
```
Error: The site you have requested is not installed.
Your table prefix is 'cli_'. Found install with table prefix: wp_.
Or, run `wp core install` to create database tables.
```
Fixes #3825
=> Indicate other WP installs in db when install isn't found

php/WP_CLI/Extractor.php
Fixes a `throw Exception` in `Extractor.php` that was missing a `new`. Also globalizes all non-globalized `Exception`s for consistency.
=> Missing new on Exception throw in Extractor.

composer.lock
```
- Updating wp-cli/package-command (v1.0.7 => v1.0.8):	 Checking out b069ec3bb8
```
=> Update Composer dependencies (2017-11-08)

.travis.yml
While #4500 is more precise, this is an easy fix to implement.
=> Set DEPLOY_BRANCH=master in deploy stage to get auto-deploy running

composer.lock
```
- Updating wp-cli/search-replace-command (v1.1.1 => v1.1.2):	Checking out f593506b1b
```
=> Update Composer dependencies (2017-11-10)

features/make-phar.feature, utils/make-phar.php
Related https://github.com/wp-cli/package-command/issues/44
Strips the phpcs entries "dealerdirect/phpcodesniffer-composer-installer", "wp-coding-standards/wpcs" (squizlabs), and "wimg/php-compatibility" (added in https://github.com/wp-cli/wp-cli/pull/4339 and https://github.com/wp-cli/wp-cli/pull/4402) from the `autoload*`s in `utils/make-phar.php`.
Only partly addresses https://github.com/wp-cli/package-command/issues/44 in that that issue needs further investigation.
=> make-phar: strip autoloads of phpcs stuff.

composer.lock
```
Package operations: 0 installs, 12 updates, 0 removals
- Updating symfony/filesystem (v2.8.28 => v2.8.29):  Checking out 10507c5f24
- Updating symfony/config (v2.8.28 => v2.8.29):  Checking out f4f3f1d709
- Updating symfony/debug (v2.8.28 => v2.8.29):  Checking out a0a29e9867
- Updating symfony/console (v2.8.28 => v2.8.29):  Checking out 89143ce2b4
- Updating symfony/dependency-injection (v2.8.28 => v2.8.29):	 Checking out bc84511148
- Updating symfony/event-dispatcher (v2.8.28 => v2.8.29):  Checking out b59aacf238
- Updating symfony/finder (v2.8.28 => v2.8.29):  Checking out efeceae6a0
- Updating symfony/process (v2.8.28 => v2.8.29):  Checking out d25449e031
- Updating …
```
=> Update Composer dependencies (2017-11-13)

utils/wp-cli-updatedeb.sh
See https://github.com/wp-cli/builds/issues/53
=> Permit use of `php7.1-mysql` in Debian build

composer.lock
```
- Updating symfony/filesystem (v2.8.29 => v2.8.30):  Checking out 10507c5f24
- Updating symfony/config (v2.8.29 => v2.8.30):  Checking out f4f3f1d709
- Updating symfony/debug (v2.8.29 => v2.8.30):  Checking out a0a29e9867
- Updating symfony/console (v2.8.29 => v2.8.30):  Checking out 3eeaec6a5d
- Updating symfony/dependency-injection (v2.8.29 => v2.8.30):	 Checking out bc84511148
- Updating symfony/event-dispatcher (v2.8.29 => v2.8.30):  Checking out b59aacf238
- Updating symfony/finder (v2.8.29 => v2.8.30):  Checking out efeceae6a0
- Updating symfony/process (v2.8.29 => v2.8.30):  Checking out d25449e031
- Updating …
```
=> Update Composer dependencies (2017-11-15)

php/WP_CLI/Extractor.php, tests/test-extractor.php
Related: `package-command` error handling of bad input.
Improves error messages returned by `Extractor`, in particular for `ZipArchive` and shell tar.
Throws error for shell tar if reached (currently will just exit on error).
Adds docblocks to functions, unit tests.
=> Improve Extractor error messages.

features/aliases.feature, features/bootstrap.feature, features/bootstrap/FeatureContext.php, features/command.feature, features/config.feature, features/flags.feature, features/framework.feature, features/help.feature, features/skip-plugins.feature, features/steps/given.php, features/steps/then.php, features/steps/when.php, php/WP_CLI/Process.php, php/WP_CLI/Runner.php
Fixes #4504
Enables displaying PHP errors (except `E_DEPRECATED`) to stderr if running behat, first on starting WP-CLI and then after WP loads.
Changes `WP_CLI\Process` to throw an error if `stderr` is non-empty if running behat.
Changes `FeatureContext` to redirect composer messages (which are output to stderr) to stdout, and to redirect warning messages on caching wp core download, and to `skip-email`, so as not to pollute stderr.
Suppresses "Warning: Wildcard DNS may not be configured correctly" message on `Given a WP multisite install`, so as not to pollute stderr. Also adds `not` option to the `Then the return code should` step for situations where there could be OS-dependent return values.
Adjusts various tests to allow for these changes, and removes individual stderr handling. Also …
=> Enable displaying PHP errors to stderr if running behat.

features/bootstrap.feature, php/WP_CLI/Runner.php
Avoids annoying "Error: Site not found" failure when you'd expect these commands to work.
Because these operations can be global (`cache flush` always, `search-replace` with specific arguments), they're safe to run as long as the cache / database have been initialized.
In considering all possible implementations (e.g. registering a new `@when` invoke, etc.), this approach seems to have the least possible impact.
Fixes https://github.com/wp-cli/cache-command/issues/17
Fixes https://github.com/wp-cli/search-replace-command/issues/41
=> Run `wp cache flush` and `wp search-replace` on multisite even when site isn't found

composer.json, utils/git-pre-commit-hook
Reverts wp-cli/wp-cli#4489
See #4544, https://github.com/wp-cli/wp-cli/issues/4474#issuecomment-343651402
=> Revert "Install a `pre-commit` Git hook on `composer install` to sniff codebase"

php/WP_CLI/Dispatcher/Subcommand.php
Fixes https://github.com/wp-cli/wp-cli/issues/4546
=> Use \n in stream_get_line in Subcommand::prompt for git/cygwin bash compat.

features/framework.feature, php/utils-wp.php
Fixes https://github.com/wp-cli/db-command/issues/61
=> Don't show 'sitecategories' table unless global terms are enabled

composer.lock
```
- Updating symfony/filesystem (v2.8.31 => v2.8.32):  Checking out 15ceb6736a
- Updating symfony/config (v2.8.31 => v2.8.32):  Checking out f4f3f1d709
- Updating symfony/debug (v2.8.31 => v2.8.32):  Checking out e72a0340dc
- Updating symfony/console (v2.8.31 => v2.8.32):  Checking out 46270f1ca4
- Updating symfony/dependency-injection (v2.8.31 => v2.8.32):	 Checking out d3e81e5402
- Updating symfony/event-dispatcher (v2.8.31 => v2.8.32):  Checking out b59aacf238
- Updating symfony/finder (v2.8.31 => v2.8.32):  Checking out efeceae6a0
- Updating symfony/process (v2.8.31 => v2.8.32):  Checking out d25449e031
- Updating …
```
=> Update Composer dependencies (2017-12-06)

utils/make-phar.php, utils/wp-cli-rpm.spec, utils/wp-cli-updatedeb.sh
Per issue https://github.com/wp-cli/wp-cli/issues/4541
=> "utils" directory - use "installation" rather than "install"

composer.lock
```
- Updating dealerdirect/phpcodesniffer-composer-installer (v0.4.3 => v0.4.4): Downloading (100%)
```
=> Update Composer dependencies (2017-12-08)

features/bootstrap/FeatureContext.php, php/WP_CLI/DocParser.php, php/WP_CLI/Process.php, php/WP_CLI/Runner.php, php/class-wp-cli.php, php/commands/help.php, php/utils.php, tests/test-extractor.php, tests/test-file-cache.php, tests/test-help.php, tests/test-process.php, tests/test-utils.php, tests/test-wp-cli.php
Fixes https://github.com/wp-cli/wp-cli/issues/4566
Adds `Utils\proc_open_compat()` (and companion private `Utils\_proc_open_compat_win_env()`) function for Windows compatible `proc_open()`, and uses it instead of `proc_open()` throughout (there's another instance in `server-command`). Also escapes all instances of`get_php_binary()`.
Changes `DocParser\get_arg_or_param_args()` to use `"\n"` instead of `PHP_EOL` as it's been subbed already.
Also simplifies `Utils\get_temp_dir()` to just use `sys_get_temp_dir()` as it always returns some non-empty value.
Makes various Windows-compat changes to the `phpunit` tests, in particular not using `WP_CLI_PHP_ARGS`  and `bin/wp` but calling `php\boot-fs.php` directly as `bin/wp.bat` doesn't have `WP_CLI_PHP_ARGS` and the invocation was *nix-specific …
=> Add Utils\proc_open_compat() for Windows compat, plus misc other compat.

utils/wp-cli-rpm.spec
Removed PHP Requirement from spec file.
Added Post install message "PHP 5.3.29 or above must be installed."
Added man page creating steps.
Changed Release version.
=> Use a softer PHP requirement in RPM build

php/utils.php
As there is some overlap between parameters across commands, we need to make sure the dictionary of hard-coded suggestions doesn't get blindly applied to commands it wasn't meant for.
Fixes #4578
=> Only provide dictionary-based suggestions if they produce valid options.

php/commands/help.php
Fixes #4593
Sets code page to 1252 if on Windows < 10 and pager is `more.com` and PHP >= 7.1.
=> Fix "Not enough memory" error on Windows 7 more.com by setting code page.

features/aliases.feature, features/bootstrap/FeatureContext.php, features/help.feature, features/runcommand.feature, features/steps.feature, tests/test-help.php, tests/test-wp-cli.php
Related https://github.com/wp-cli/wp-cli/pull/4245
Adds processing of special variable `{INVOKE_WP_CLI_WITH_PHP_ARGS-}` to `FeatureContext::replace_variables()` so that PHP args can be given to either the wp-cli phar or the shell file, in order to test stuff under varying PHP conditions.
Uses it in `aliases.feature`, `help.feature` and `runcommand.feature` to test running with `proc_open()`/`proc_close()` unavailable, and removes corresponding phpunit tests.
Before (and still with the remaining phpunit tests) was only testing git not phar invocation. Will be useful in other cases also (eg https://github.com/wp-cli/package-command/issues/27).
=> Add processing of {INVOKE_WP_CLI_WITH_PHP_ARGS-} vars to FeatureContext.

features/bootstrap/FeatureContext.php
See https://github.com/wp-cli/wp-cli/pull/4597 and https://github.com/wp-cli/package-command/pull/64
Need to check for phar sig as `WP_CLI_BIN_DIR` defined to be `vendor/bin` outside of `wp-cli/wp-cli` and points to shell wp.
=> Fix INVOKE_WP_CLI_WITH_PHP_ARGS to check phar sig.

ci/behat-tags.php, features/cli.feature, tests/test-behat-tags.php
See https://github.com/wp-cli/embed-command/pull/29#issuecomment-355042624
Adds `@less-than-wp` tag, analog of `@less-than-php`, to `behat-tags.php`. Useful for testing old WP behaviour.
=> Add less-than-wp tag to behat-tags.php.

features/runcommand.feature
Related https://github.com/wp-cli/entity-command/pull/126 and https://github.com/wp-cli/entity-command/issues/123
Changes the runcommand test `Override erroring on exit` that checks for `NULL` returned to use `option pluck` instead of `option get` now that `option get` returns an error string if an option doesn't exist.
=> In runcommand test use pluck now that option get returns error string

php/utils.php, tests/test-utils.php
Related https://github.com/wp-cli/db-command/issues/65 and https://github.com/wp-cli/db-command/issues/66, and also https://github.com/wp-cli/wp-cli/pull/4527#discussion_r152706464
Adds `wpdb::esc_like()` polyfill to `utils.php`. Copied directly from core.
Will be used to close https://github.com/wp-cli/db-command/issues/65 and by-pass https://github.com/wp-cli/db-command/issues/66.
Should also be used in `search-replace-command` and `entity-command`.
=> Add Utils\esc_like() polyfill of wpdb version.

php/utils.php, tests/test-utils.php
Adds two helper functions:
* `WP_CLI\Utils\parse_shell_arrays( $assoc_args, $array_arguments )`
This takes an existing `$assoc_args` array, and parses possible shell arguments for all keys that are provided in `$array_arguments`
* `WP_CLI\Utils\is_json( $argument, $ignore_scalars = true )`
Helper function for the above parsing, that detects whether a given string is valid JSON.
See #4616
=> Add shell array parsing helper

composer.json
See https://github.com/wp-cli/wp-cli/issues/4625
Adds dev-master branch alias `1.5.x-dev` as per https://github.com/wp-cli/db-command/pull/79#issuecomment-357967577.
=> Add dev-master branch alias.

php/WP_CLI/Runner.php
Hi,
this PR checks for the existing of WordPress with `file_exists( ABSPATH . '/wp-includes/version.php' )` and in a separate check for the readability of this file.
This way, we can give a more precise error message. If its a readability problem, this PR sends `It seems, the WordPress core files do not have the proper file permissions.` and otherwise the known error message.
This solves #4594 
Thank you :)
=> Check for readablity of WordPress core files (solves #4594)

features/utils-wp.feature, php/utils-wp.php
Noticed on doing https://github.com/wp-cli/media-command/pull/62 PR that `Utils\wp_clear_object_cache()` was setting some non-defined properties on the `WP_Object_Cache` object.
The code appears to be Memcached and Memcached Redux plugin specific according to https://core.trac.wordpress.org/ticket/31463. See also `WP_UnitTestCase::flush_cache()` in core test suite https://github.com/WordPress/wordpress-develop/blob/4.9.1/tests/phpunit/includes/testcase.php#L321.
So this PR updates the `wp_clear_object_cache()` to use the standard `wp_cache_flush()` function, keeping the other stuff for BC but checking first and using `method_exists()` on `__remoteset` check.
=> Use wp_cache_flush in Utils\wp_clear_object_cache & check props.

features/utils-wp.feature, php/utils-wp.php, php/utils.php
See issue https://github.com/wp-cli/db-command/issues/73 and PRs https://github.com/wp-cli/db-command/pull/78 and https://github.com/wp-cli/wp-cli/pull/4606
Rewrites `Utils\wp_get_table_names()` to deal correctly with wildcards by getting the WP tables first and then filtering through the `$args`.
It's a backward compatibility (BC) change in that various buggy behaviours no longer happen, eg `wp db tables no_such_table` will return an error rather than `no_such_table`.
Also introduces some avoidable BC breaks:
- `scope` is not ignored when `network` given (it doesn't make sense to me that it should be).
- the tables are always returned sorted (rather than in `wpdb` order currently if not given `all-tables` or `all-tables-with-prefix`).
Also adds `Utils\esc_sql_ident()` from `DB_Command` …
=> Rewrite wp_get_table_names to deal correctly with wildcards.

features/command.feature, php/WP_CLI/Dispatcher/CompositeCommand.php, php/class-wp-cli.php, php/commands/help.php, php/utils.php, tests/test-utils.php
Related release checklist https://github.com/wp-cli/wp-cli/issues/4512 item "Document longdesc argument from #4513 in Commands Cookbook"
When attempting to do this, noticed a bug in that the `longdesc` arg to `WP_CLI\add_command()` is ignored (overwritten) if a synopsis is given as well.
So this PR appends the `longdesc` if given to the generated synopsis.
Also replaces the `PHP_EOL` appends with `"\n"` and trims with `"\r\n"` as `PHP_EOL` shouldn't be used in this instance (tested on WIndows 10).
Also adds `Utils\normalize_eols()` function and uses in `CompositeCommand::set_shortdesc()` and `set_longdesc()` in case given Windows input.
Also fixes the regex used to detect non-zero-length lines that aren't section headers and don't have leading spaces in `Help_Command::show_help()`, which …
=> Append longdesc if given synopsis on WP_CLI::add_command().

composer.lock
* Updating wp-cli/core-command v1.0.8 => v1.0.9
* Updating wp-cli/entity-command v1.1.4 => v1.2.0
* Updating wp-cli/export-command v1.0.5 => v1.0.6
* Updating wp-cli/media-command v1.1.3 => v1.1.4
* Updating wp-cli/package-command v1.0.10 => v1.0.11
* Updating wp-cli/scaffold-command v1.1.1 => v1.1.2
* Updating wp-cli/search-replace-command v1.1.4 => v1.2.0
=> Update to latest Composer packages

php/WP_CLI/Runner.php
`wp config get --global=<global>` => `wp config get <name> --type=variable`
`wp config get --constant=<constant>` => `wp config get <name> --type=constant`
`wp config get` => `wp config list`
Fixes https://github.com/wp-cli/config-command/issues/43
=> Handle old config syntax gracefully

utils/make-phar.php
For consideration/discussion.
This adds a `WP_CLI_ROOT/COMPOSER_VERSIONS` file to the phar (but doesn't create on disk) that lists the versions/gitrefs used from `composer.lock`, as a check to see what was used to build the phar.
Also updates usage and makes some strip regexs consistent (no functional change).
Also excludes `demo` folder (in `vendor/justinrainbow/json-schema`).
Also writes errors to STDERR and uses PHP_EOL for all messages.
=> Add COMPOSER_VERSIONS file generated from composer.lock to phar.

tests/test-behat-tags.php, tests/test-extractor.php, tests/test-utils.php
Fixes #4671 
Checks for correct extension in `test_behat_tags_extension()`.
Uses `--force-local` on Windows only in `test_extract_tarball()`.
Sorts expected/actual in `testExpandGlobs()` to allow for different filesystem glob order.
=> Fix phpunit extractor, glob, behat tests.

features/class-wp-cli.feature, features/utils.feature, tests/test-utils.php, tests/test-wp-cli.php
Closes #4673 
Moves remaining (see https://github.com/wp-cli/wp-cli/pull/4597) phpunit tests invoking PHP with directive to behat `INVOKE_WP_CLI_WITH_PHP_ARGS` tests.
=> Move phpunit PHP directive tests to behat.

tests/test-extractor.php
Closes #4671 
Related #4672 
Redirects `STDERR` to `STDOUT` for Mac tar verbose output and normalizes.
=> Normalize Mac tar output.

features/framework.feature
Fixes #4694 
Adjusts `framework.feature:313` test to allow for this core changeset https://core.trac.wordpress.org/changeset/42698 which got around a bug in `WP_Site_Query::query()` which doesn't ignore `domain__in` when empty.
Does this by manually setting `wp_blogs.domain` to null so the query works across all WP versions.
=> Empty domain in framework test after get_sites_by_path change.

composer.json, utils/git-setup-pre-commit-hook
Creates a Git pre-commit file to run phpcs once every commit (https://github.com/wp-cli/wp-cli/issues/4474).
=> Script to create the Git pre-commit hook.

php/commands/src/CLI_Command.php
See https://github.com/wp-cli/wp-cli/pull/4692#issuecomment-366808983
Removes colon from cli update info check to get builds working again.
Will probably revert https://github.com/wp-cli/wp-cli/pull/4613 also as unnecessary BC break.
=> Remove : from cli update info check.

php/utils.php
=> Append uniq id when extracting file from Phar

php/utils.php
If the editor does some amount of syntax highlighting, it probably needs
the extension to enable the highlighting.
See https://github.com/wp-cli/config-command/pull/48
=> Support launching system editor with specific temp file extension

utils/git-pre-commit-script, utils/git-setup-pre-commit-hook
This avoids causing unnecessary delays when committing files.
See https://github.com/wp-cli/wp-cli/pull/4622#issuecomment-366789280
=> Only check staged files during the pre-commit PHPCS verification

features/cli-info.feature, php/commands/src/CLI_Command.php
Reverts wp-cli/wp-cli#4613
See https://github.com/wp-cli/wp-cli/issues/4701 where it breaks self-updating.
Plus unnecessary BC break, less readable, my fault, apologies and thanks to @thrijith for the work.
=> Revert "update `wp cli info`"

features/bootstrap.feature
See https://github.com/wp-cli/wp-cli/pull/4715
Undoes one-off `require-php-5.4` tag on "bootstrap.feature:25" used to workaround PHP 5.4 requirement.
=> Undo temp one-off require-php-5.4 in bootstrap test.

composer.lock, php/WP_CLI/Formatter.php, php/WP_CLI/Runner.php, php/utils.php
```
Package operations: 0 installs, 17 updates, 0 removals
- Updating symfony/process (v2.8.32 => v2.8.34):  Checking out 905efe9002
- Updating symfony/finder (v2.8.32 => v2.8.34):  Checking out 9786ccb6a1
- Updating symfony/filesystem (v2.8.32 => v2.8.34):  Checking out 1f4e8351e0
- Updating symfony/polyfill-mbstring (v1.6.0 => v1.7.0):  Checking out 78be803ce0
- Updating symfony/debug (v2.8.32 => v2.8.34):  Checking out 35e36287fc
- Updating symfony/console (v2.8.32 => v2.8.34):  Checking out 162ca7d0ea
- Updating seld/jsonlint (1.6.2 => 1.7.1):  Checking out d15f59a67f
- Updating justinrainbow/json-schema (5.2.6 => 5.2.7):  Checking out 8560d43145
- Updating composer/spdx-licenses …
```
=> Update Composer dependencies (2018-02-28)

utils/auto-composer-update.sh
When our bot gets rejected because of PHPCS violations, it doesn't know
what to do. It's better the pull request is submitted.
=> Skip pre-commit hook in auto-composer-update

php/WP_CLI/Runner.php, php/utils.php, tests/test-utils.php
As discussed with @gitlost here: https://github.com/wp-cli/checksum-command/pull/39
Introducing `normalize_path` function (copied it from latest the WP Core :) ), and applied it to the `ABSPATH` constant, so that path concatenations of it have (more or less) consistent path separators.
=> Introducing `\WP_CLI\Utils\normalize_path` function. Using it for ABSPATH constant.

composer.lock
```
- Updating wp-cli/wp-config-transformer (v1.2.0 => v1.2.1): Downloading (100%)
```
=> Update Composer dependencies (2018-03-21)

features/runner.feature, php/WP_CLI/Runner.php
see #4537 
And https://github.com/wp-cli/ideas/issues/69
=> Abspath defined

features/help.feature, php/commands/help.php, php/config-spec.php
When running `wp help` on an environment where `proc_open()` or `proc_close()` aren't available, the command silently fails with no output (unless the `--debug` flag is used).
The command should output the help text using stdout in this situation, so the user still sees help text.
This change also improves the corresponding description of the `--debug` flag, and switches to returning `-1` from `Help_Command::pass_through_pager()` so that its return value matches that of `proc_close()` when there's an error.
=> Show help text even when `proc_(open|close)` aren't available

php/config-spec.php
Makes it clearer that these flags optionally accept a comma separated list of plugins or themes.
=> Improve the descriptions of the `--skip-plugins` and `--skip-themes` flags

php/commands/src/CLI_Command.php
This format is accepted already, it's just not documented and therefore isn't usable.
=> Add a missing accepted output format to `wp cli alias`

composer.lock
```
- Updating symfony/filesystem (v2.8.40 => v2.8.41):  Checking out 1ed4b26555
- Updating symfony/config (v2.8.40 => v2.8.41):  Checking out 93bdf96d0e
- Updating symfony/debug (v2.8.40 => v2.8.41):  Checking out fe8838e11c
- Updating symfony/console (v2.8.40 => v2.8.41):  Checking out e8e59b74ad
- Updating symfony/dependency-injection (v2.8.40 => v2.8.41):	 Checking out 3d7cbf34cd
- Updating symfony/event-dispatcher (v2.8.40 => v2.8.41):  Checking out 9b69aad7d4
- Updating symfony/finder (v2.8.40 => v2.8.41):  Checking out 79764d2116
- Updating symfony/process (v2.8.40 => v2.8.41):  Checking out 713952f2cc
- Updating …
```
=> Update Composer dependencies (2018-05-28)

README.md
Fixes https://github.com/wp-cli/wp-cli/issues/4823
=> Locking wp-completion.bash to v1.5.1

features/skip-themes.feature
Fixes tests failure caused by suspension of previously used themes on woordpress.org.
=> Fixing skip-theme tests

features/skip-themes.feature
This PR removes WP 4.4 requirement from skip-theme test by using stargazer and buntu themes.
=> Remove WP 4.4 requirement

composer.lock
```
- Updating wp-cli/scaffold-command (v1.1.3 => v1.2.0):  Checking out a897a54ba0
```
=> Update Composer dependencies (2018-07-30)

php/WP_CLI/Inflector.php, php/utils.php, tests/test-inflector.php, tests/test-utils.php
=> Add Inflector class and convenience function for pluralizing nouns

composer.lock
```
- Updating wp-cli/entity-command (v1.3.1 => v2.0.0):	Checking out e3f3d244ae
- Updating wp-cli/extension-command (v1.2.2 => v2.0.0):  Checking out 4fed9eeb94
- Updating symfony/polyfill-ctype (v1.8.0 => v1.9.0): Loading from cache
- Updating symfony/polyfill-mbstring (v1.8.0 => v1.9.0):  Checking out d0cd638f46
- Updating composer/ca-bundle (1.1.1 => 1.1.2):  Checking out 46afded972
- Updating composer/composer (1.7.0 => 1.7.1):  Checking out 5d9311d455
- Updating wp-cli/package-command (v2.0.0 => v2.0.2):	 Checking out d6637f39d9
- Updating phpspec/prophecy (1.7.6 => 1.8.0): Loading from cache
- Updating wp-cli/wp-cli-tests …
```
=> Update Composer dependencies (2018-08-10)

php/class-wp-cli.php
By default `var_export` will dump its output to stdout. Set the return
parameter to true to save it into the `$value` variable for further
processing as expected.
=> Fix `var_export` return in `WP_CLI::print_value`

composer.lock
```
- Updating symfony/finder (v2.8.44 => v2.8.45):  Checking out f0de0b5191
- Updating symfony/debug (v2.8.44 => v2.8.45):  Checking out cbb8a5f212
- Updating symfony/console (v2.8.44 => v2.8.45):  Checking out 0c1fcbb9af
- Updating symfony/process (v2.8.44 => v2.8.45):  Checking out 4be278e190
- Updating symfony/filesystem (v2.8.44 => v2.8.45):  Checking out 0b252f4e25
- Updating symfony/config (v2.8.44 => v2.8.45):  Checking out 06c0be4cdd
- Updating symfony/dependency-injection (v2.8.44 => v2.8.45):	 Checking out ad2446d39d
- Updating symfony/event-dispatcher (v2.8.44 => v2.8.45):  Checking out 84ae343f39
- Updating …
```
=> Update Composer dependencies (2018-08-29)

composer.lock
```
- Updating wp-cli/php-cli-tools (v0.11.9 => v0.11.10):  Checking out f99308f924
```
=> Update Composer dependencies (2018-09-05)

php/wp-cli.php
For the development use case where all repositories are checked out into a flat folder hierarchy (mirroring the GitHub org), the `vendor` folder will end up being a sibling to the `wp-cli` framework folder.
The bootstrapping code needs to allow for this setup as well.
=> Add sibling `vendor` folder location

README.md
Tweets are now limited to 280 characters instead of 140 characters.
=> Update README to account for the 280-character limit on Twitter

composer.lock
```
The "http://packagist.org/p/provider-2018-07%24bff2396d778869ecd4413810a6740d47f718b54e996a28f5e2ef065f1d677e79.json" file could not be downloaded: failed to open stream: Connection timed out
http://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
- Updating wp-cli/wp-config-transformer (v1.2.1 => v1.2.2): Downloading (100%)
```
=> Update Composer dependencies (2018-10-05)

composer.lock
=> Update Composer dependencies (2018-10-15)

composer.lock
```
- Updating composer/ca-bundle (1.1.2 => 1.1.3):  Checking out 8afa52cd41
```
=> Update Composer dependencies (2018-10-19)

php/utils.php
fix for #4856 to add dirname when searching for wp-config inline with WordPress
=> Use `dirname()` instead of `..` to locate `wp-config.php` to match Core behavior

features/utils-wp.feature, php/class-wp-cli.php, php/commands/src/CLI_Command.php
This PR uses the noun where appropriate. Please note only documentation is addressed, not code or tests. PR is a response to https://twitter.com/wpcli/status/1047158732805853184
#Hacktoberfest
=> Use "installation" instead of "install" in documentation

php/utils.php
Fix for #4856 Updated locate_wp_config() to match core.
=> Match the way WordPress Core locates `wp-config.php`

composer.lock
```
Nothing to install or update
PHP CodeSniffer Config installed_paths set to ../../phpcompatibility/php-compatibility/,../../phpcompatibility/phpcompatibility-wp/,../../wp-coding-standards/wpcs/
```
=> Update Composer dependencies (2018-10-31)

php/utils.php, tests/test-utils.php
I added unit tests for the broken cases and modified the regular expression so that it correctly parses these cases as well.
Fixes #4741
=> Fix parsing of arguments for `WP_CLI::runcommand()` with `launch=false`

composer.lock
```
Package operations: 0 installs, 5 updates, 0 removals
- Updating symfony/polyfill-ctype (v1.9.0 => v1.10.0): Loading from cache
- Updating symfony/polyfill-mbstring (v1.9.0 => v1.10.0):  Checking out c79c051f5b
- Updating composer/spdx-licenses (1.4.0 => 1.5.0):  Checking out 7a9556b22b
- Updating composer/composer (1.7.2 => 1.7.3):  Checking out e965b9aaa8
```
=> Update Composer dependencies (2018-11-02)

composer.lock
```
- Updating symfony/finder (v2.8.46 => v2.8.47):  Checking out 5ebb438d1a
- Updating symfony/filesystem (v2.8.46 => v2.8.47):  Checking out 56a92481a4
- Updating symfony/config (v2.8.46 => v2.8.47):  Checking out 506aaec58d
- Updating symfony/debug (v2.8.46 => v2.8.47):  Checking out 6a198c52b6
- Updating symfony/console (v2.8.46 => v2.8.47):  Checking out 48ed63767c
- Updating symfony/dependency-injection (v2.8.46 => v2.8.47):	 Checking out 8b7508c6af
- Updating symfony/event-dispatcher (v2.8.46 => v2.8.47):  Checking out 76494bc38f
- Updating symfony/translation (v2.8.46 => v2.8.47):	Checking out cb34ec9549
- Updating symfony/yaml …
```
=> Update Composer dependencies (2018-11-05)

composer.lock
```
- Updating wp-cli/wp-config-transformer (v1.2.2 => v1.2.3): Downloading (100%)
```
=> Update Composer dependencies (2018-11-12)

composer.lock
```
- Updating wp-coding-standards/wpcs (1.1.0 => 1.2.0): Downloading (100%)
PHP CodeSniffer Config installed_paths set to ../../phpcompatibility/php-compatibility/,../../phpcompatibility/phpcompatibility-wp/,../../wp-coding-standards/wpcs/
```
=> Update Composer dependencies (2018-11-14)

features/bootstrap.feature, php/WP_CLI/Bootstrap/IncludeFrameworkAutoloader.php, phpcs.xml.dist
This decouples the framework from the Composer autoloader, so that framework and bundled commands can be controlled independently, allowing overrides.
Fixes #4987
Depends on #5014
=> Use custom autoloader to load framework

php/WP_CLI/Dispatcher/RootCommand.php
This code doesn't add any value as the parent version would have been called anyway.
=> PHPCS: fix up the code base [4] - remove redundant function

php/commands/src/Help_Command.php
The `$link_count` is not going to change during the loop, so there is no need to repeatedly call `count()`.
=> PHPCS: fix up the code base [9] - function calls in for condition

php/class-wp-cli.php
* Use `self` when referencing a (static) class member from within the same class.
=> PHPCS: fix up the code base [11] - use self

php/WP_CLI/Bootstrap/IncludeFallbackAutoloader.php, php/WP_CLI/Configurator.php, php/WP_CLI/Dispatcher/CommandFactory.php, php/WP_CLI/Dispatcher/Subcommand.php, php/WP_CLI/Extractor.php, php/WP_CLI/Runner.php, php/utils-wp.php, php/utils.php, php/wp-settings-cli.php
* No assignments in conditions.
Where there was no doubt about what the possible output types could be, I've also adjusted the conditions from loose comparisons to strict.
=> PHPCS: fix up the code base [13] - assignments in conditions

php/class-wp-cli.php
* No assignments in conditions.
As this was an assignment in an `elseif`, the logic of the code needed some tweaking as well to turn the `elseif` into an `if`.
=> PHPCS: fix up the code base [14] - assignments in conditions

php/boot-fs.php
When an include fails, you'll receive a `warning` and PHP will try to continue execution. When a `require` fails, this causes a fatal error, which considering this statement is trying to load the main file, is more appropriate.
=> PHPCS: fix up the code base [17] - require vs include

php/boot-fs.php
fixes https://github.com/wp-cli/wp-cli/issues/5037
=> Bump PHP version check in bootstrap code to v5.4+

php/WP_CLI/Bootstrap/IncludePackageAutoloader.php, php/WP_CLI/Bootstrap/LoadRequiredCommand.php
PHP does not have a concept of named parameters, so assigning a parameter being passed in a function call to a variable within that call does not have a function, especially if that variable is not used anywhere within the same function (as it isn't in these cases).
=> PHPCS: fix up the code base [12] - assignment within function call

php/WP_CLI/Completions.php, php/WP_CLI/Configurator.php, php/WP_CLI/Dispatcher/CommandFactory.php, php/WP_CLI/Dispatcher/CompositeCommand.php, php/WP_CLI/Dispatcher/RootCommand.php, php/WP_CLI/Dispatcher/Subcommand.php, php/WP_CLI/DocParser.php, php/WP_CLI/Inflector.php, php/WP_CLI/Process.php, php/WP_CLI/Runner.php, php/WP_CLI/WpHttpCacheManager.php, php/class-wp-cli.php, php/utils-wp.php, php/utils.php, tests/bootstrap.php, tests/test-arg-validation.php, tests/test-commandfactory.php, tests/test-configurator.php, tests/test-doc-parser.php, tests/test-extractor.php, tests/test-file-cache.php, tests/test-help.php, tests/test-logging.php, tests/test-process.php, tests/test-synopsis.php, tests/test-utils.php, utils/contrib-list.php, utils/get-package-require-from-composer.php
Simple, mostly whitespace related, fixes to make the code comply with the WPCliCS rules.
* Align the equality operators in assignment blocks.
* No multiple assignments in one statement.
* One space between a control structure keyword and the open parenthesis.
* No space between a function call/language contruct keyword and the open parenthesis.
* One space on the inside of open/close parenthesis when there is content between them.
* Always use parenthesis when instantiating a new object.
* One space after equality operators.
* One space before and after concatenation operators.
* Don't use concatenation when it isn't necessary.
* There should be no space before a comma.
* Associative arrays with more than one item, should be multi-line.
* The double …
=> PHPCS: fix up the code base [1] - whitespace

php/WP_CLI/Dispatcher/CommandFactory.php, php/WP_CLI/FileCache.php, php/WP_CLI/Runner.php
Use brackets to prevent confusion over operator precedence.
=> PHPCS: fix up the code base [16] - operator precedence

tests/test-utils.php
Whether a full-blown function or a closure, the body of a function has to start on a new line, once indented and the close brace has to be on its own line.
As this would make the function call in which this closure was wrapped multi-line, I've moved the closure declaration to a variable declared before the function call and pass the variable in instead.
=> PHPCS: fix up the code base [7] - closure declaration

php/WP_CLI/Dispatcher/CommandFactory.php
* No assignments in conditions.
A minor refactor was needed to get rid of the assignment in condition here.
Note: this is a code layout change only. The functionality should still work exactly the same.
=> PHPCS: fix up the code base [15] - assignments in conditions

features/prompt.feature, php/WP_CLI/Dispatcher/Subcommand.php
I'm ignoring positional arguments for now and concentrate on associative arguments, except the ones of type `generic` (`--<field>=<value>`).
The current PR seems to work as expected, however I'm not sure yet how to write a test for this functionality.
Fixes #4762
=> Skip associative arguments that were already provided on `--prompt`

tests/test-doc-parser.php, tests/test-extractor.php, tests/test-logging.php, tests/test-utils.php
Multi-line function calls need to have each argument on a new line.
In a next iteration of this principle, it is expected that a sniff will be introduced to ban multi-line function call arguments.
With this mind, a number of function calls with multi-line parameters which are currently already causing errors to be thrown by PHPCS, have been fixed by moving multi-line function call arguments out of the function call and defining these as a variable before passing it to the function call.
Includes:
* A few multi-line function calls where the parameters have been put on their own line.
* A few multi-line function calls which didn't need to be multi-line and have been changed to single-line (one item associative arrays).
=> PHPCS: fix up the code base [6] - multi-line function calls

composer.lock
- Updating dealerdirect/phpcodesniffer-composer-installer (v0.4.4 => v0.5.0)
- Updating wp-cli/php-cli-tools (v0.11.10 => v0.11.11)
- Updating symfony/finder (v2.8.47 => v2.8.49)
- Updating wp-cli/db-command (v2.0.0 => v2.0.1)
- Updating wp-cli/entity-command (v2.0.1 => v2.0.2)
- Updating wp-cli/extension-command (v2.0.2 => v2.0.3)
- Updating symfony/yaml (v2.8.47 => v2.8.49)
- Updating symfony/translation (v2.8.47 => v2.8.49)
- Updating symfony/process (v2.8.47 => v2.8.49)
- Updating symfony/filesystem (v2.8.47 => v2.8.49)
- Updating symfony/event-dispatcher (v2.8.47 => v2.8.49)
- Updating symfony/dependency-injection (v2.8.47 => v2.8.49)
- Updating psr/log (1.0.2 => 1.1.0)
- Updating symfony/debug (v2.8.47 => v2.8.49)
- Updating symfony/console (v2.8.47 => v2.8.49)
- Updating …
=> Update Composer dependencies (2018-12-17)

php/WP_CLI/Bootstrap/IncludeFrameworkAutoloader.php
Something minor I noticed while reviewing how the bootstrap process works.
=> Fix typo: Autolaoder => Autoloader

.github/ISSUE_TEMPLATE
The links used to redirect to the new location (see https://web.archive.org/web/20170409053658/https://wp-cli.org/docs/bug-reports/). But now they return 404.
=> Bugfix outdated links in ISSUE_TEMPLATE

features/cli.feature, php/class-wp-cli.php
New wp cli api to validate that a global configuration does exists.
Related #4954
=> Validate that global configuration does exists

.travis.yml
This PR:
- Changes the default version of PHP used on jobs to 7.3
- Adds a PHP 7.3 job to the list.
One thing I am not sure of yet is how this gets pushed to the other repositories. Please advise the best way to tackle this.
=> Update the Travis build to include PHP 7.3.

features/cli-cache.feature, php/WP_CLI/FileCache.php
Check Cache file is accesible
Resolve #5011
=> Ensure cache directories are accessibles

README.md
This change fixes an invalid link in the readme. The curl command is properly using raw.githubusercontent.com but the clickable link was not. 
As documented in https://developer.github.com/changes/2014-04-25-user-content-security/
=> fix incorrect link in readme

features/help.feature
WP 5.1 includes a bit more error message output. This pull request makes
our tests looser so they pass for both WP 5.1 and earlier versions.
=> Fix failing test under WP 5.1

php/utils.php, tests/test-utils.php
Summary:
While building a command that run other commands, i realized that there's a bug with the `parse_str_to_argv` function that's used in `WP_CLI::runcommand`.
This is a seemingly valid string to be sent to the function which fails to properly be parsed in the current version
`command subcommand "param with space" "paramnotspaced" "param spaced with \" quotes escaped" --param="string with spaces" --param="string with \" quotes escaped" --param='single quotes'`
This string is not properly parsed or get the quotes escaped accordingly.
This issue was introduced somewhere around the last 4 months when this regex was modified. I've tested this in 2.0.0-alpha something and it was not present.
Hopefully this can be fixed for the next version.
=> Update regex to be more accurate

php/class-wp-cli.php
This closes #5098 
The PR updates the return value for the `add_command()` function.
=> update docblock for add_command() to properly reflect the return value

php/WP_CLI/FileCache.php, tests/test-file-cache.php
=> Fix FileCache::export() not ensuring parent directories exist for $target

php/utils.php, tests/test-utils.php
Added support for DB_HOST strings that include 'p:' for persistent DB connections. If present, the 'p:' modifier is replaced with '' to allow the correct parsing of the remaining host string.
=> Bug fix for Issue #5109

composer.json, composer.lock
This PR
💁‍♂️ We don't know yet whether this project will work with PHP 9000.
=> Fix: Limit ranges of PHP versions

php/WP_CLI/Dispatcher/CompositeCommand.php, php/WP_CLI/Runner.php, php/class-wp-cli.php
* Declare only one property per statement.
=> PHPCS: fix up the code base [18] - one property per statement

php/WP_CLI/Dispatcher/Subcommand.php
* Use the `$strict` parameter when calling `in_array()`.
N.B.: These should be reviewed critically!
=> PHPCS: fix up the code base [20] - strict array comparisons

php/class-wp-cli.php
Use `self` when referencing a (static) class member from within the same class.
=> PHPCS: fix up the code base [21] - use `self`

php/WP_CLI/ComposerIO.php, php/WP_CLI/Dispatcher/CompositeCommand.php, php/WP_CLI/Dispatcher/RootCommand.php, php/WP_CLI/PackageManagerEventSubscriber.php, php/class-wp-cli.php, php/commands/src/CLI_Command.php, php/utils.php, php/wp-settings-cli.php
Import `use` statements should always be fully qualified, so a leading backslash is unnecessary and explicitly recommended against.
Ref: https://www.php.net/manual/en/language.namespaces.importing.php
=> PHPCS: fix up the code base [22] - no \ prefixed use statements

php/WP_CLI/FileCache.php, php/class-wp-cli.php
Inline `@var` comments should use docblock format. This will also prevent them from being incorrectly marked as commented out code.
=> PHPCS: fix up the code base [23] - touch up inline comment

php/utils.php
Variable names should be in `snake_case`.
As this is a function local variable, it can be safely renamed without BC.
=>  PHPCS: fix up the code base [25] - rename a local variable

php/WP_CLI/DocParser.php
Variable names should be in `snake_case`.
As this is a function local variable, it can be safely renamed without BC.
=> PHPCS: fix up the code base [26] - rename a local variable

php/WP_CLI/FileCache.php
Variable names should be in `snake_case`.
As this is a function local variable, it can be safely renamed without BC.
=> PHPCS: fix up the code base [28] - rename a local variable

tests/test-logging.php
Variable names should be in `snake_case`.
As this is a function local variable, it can be safely renamed without BC.
=> PHPCS: fix up the code base [29] - rename two local variables

php/WP_CLI/Runner.php
=> PHPCS: fix up the code base [30] - rename a private property

php/WP_CLI/Inflector.php
=> PHPCS: fix up the code base [34] - rename a private property

php/WP_CLI/Iterators/CSV.php
=> PHPCS: fix up the code base [35] - rename a private property

php/WP_CLI/Configurator.php
Use words. This will also prevent these comments from being incorrectly marked as commented out code.
=> PHPCS: fix up the code base [24] - touch up inline comments

php/WP_CLI/Runner.php
=> PHPCS: fix up the code base [31] - rename a private property

php/WP_CLI/Iterators/CSV.php
=> PHPCS: fix up the code base [36] - rename a private property

php/WP_CLI/Runner.php
=> PHPCS: fix up the code base [32] - rename a private property

php/WP_CLI/Iterators/CSV.php
=> PHPCS: fix up the code base [37] - rename a private property

php/WP_CLI/Runner.php
=> PHPCS: fix up the code base [33] - rename a private property

php/WP_CLI/Runner.php
Method names should be in `snake_case`.
As this is a private method, it can be safely renamed without BC.
=> PHPCS: fix up the code base [38] - rename a private method

php/WP_CLI/Loggers/Base.php
=> Whitelist `_line` method as it is being used in third-party code

php/WP_CLI/DocParser.php, php/WP_CLI/FileCache.php
`DocParser::$docComment` -> `DocParser::$doc_comment`
`FileCache::$maxSize` -> `FileCache::$max_size`
Technically, both of these are breaking changes, as they are both protected, not private. However, neither a plugin search nor a GitHub search could find any instance where these classes were extended in third-party code.
Related #5166
=> Rename camelCase properties to snake_case

php/WP_CLI/Process.php
I don't see any valid reason why that one was kept in.
Related #5166
=> Remove access to inexistent `$STDERR` property

php/WP_CLI/Bootstrap/BootstrapState.php, php/WP_CLI/Bootstrap/DefineProtectedCommands.php, php/WP_CLI/Bootstrap/IncludePackageAutoloader.php, php/WP_CLI/Bootstrap/LoadRequiredCommand.php
Reverts wp-cli/wp-cli#5173
Changing the method names breaks autoload interactions between Phar & framework/commands you use outside of Phar (like when running the Phar WP inside of a command folder).
=> Revert "Rename camelCase methods into snake_case"

php/WP_CLI/Loggers/Execution.php
The override does provide a default value that the original method doesn't.
Related #5166
Related #5179
=> Whitelist "useless" override

php/WP_CLI/Dispatcher/Subcommand.php
Reverts wp-cli/wp-cli#5147
This breaks the synopsis validation and leads to changed behavior when detecting whether flags have values or not.
See for a related test failure: https://travis-ci.org/wp-cli/automated-tests/jobs/522583446#L2476-L2485
=> Revert "PHPCS: fix up the code base [20] - strict array comparisons"

php/utils.php
It produces the format that the wordpress.org API requires.
Related #5166
Related #5179
=> Whitelist urlencode

php/WP_CLI/FileCache.php, php/WP_CLI/Runner.php, php/WP_CLI/WpHttpCacheManager.php, php/utils.php
The  `WP_CLI\Utils\parse_url` helper now uses `wp_parse_url` if available, and falls back to the PHP `parse_url` otherwise.
Related #5166
Related #5179
=> Replace or justify the usage of the `parse_url()` function

php/class-wp-cli.php
When a given subcommand is already found:
- if it is a command namespace, we replace it with the new command, and attach all children of the namespace to the new command.
- if it is a regular command, we skip registration, to avoid double registration. This means only the first registration counts (making overrides through packages and requires precede bundled commands).
Fixes #5186
=> Avoid double registration of commands

features/utils-wp.feature, php/utils-wp.php
Part one of a feature discussed in [search-replace-command/issues/109](https://github.com/wp-cli/search-replace-command/issues/109) - adds new flags --views-only and --base-tables-only to restrict results.
Test coverage only included for use with --all-tables / --all-tables-with-prefix. This is because when these functions aren't passed wp_get_table_names() relies on retrieving tables names from $wpdb. I couldn't see how to register a view with / inject a view into $wpdb, so have left that test coverage out for now.
=> Add flags to include / exclude views in wp_get_table_names()

.gitignore, composer.json, composer.lock, php/WP_CLI/Bootstrap/BootstrapState.php, php/WP_CLI/Dispatcher/Subcommand.php, php/WP_CLI/FileCache.php, php/WP_CLI/Formatter.php, php/WP_CLI/Runner.php, php/WP_CLI/UpgraderSkin.php, php/class-wp-cli.php, php/commands/src/Help_Command.php, php/compat.php, php/utils-wp.php, php/utils.php, php/wp-settings-cli.php, phpcs.xml.dist, tests/phpunit6-compat.php, tests/test-bundled-commands.php, tests/test-logging.php
This basically updates the PHPCS ruleset to use the new `WP_CLI_CS` standard and adds a number of whitelist comments and exclusions.
As annotated in issue #5166, there is currently only one issue still remaining to be fixed:
```
FILE: php\utils-wp.php
------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
------------------------------------------------------------------------------------------
111 | WARNING | strip_tags() is discouraged. Use the more comprehensive
|         | wp_strip_all_tags() instead.
|         | (WordPress.WP.AlternativeFunctions.strip_tags_strip_tags)
------------------------------------------------------------------------------------------
```
Please see the individual commits for …
=> Implement CS checking based on the `WP_CLI_CS` ruleset

php/class-wp-cli.php
Instead of only reattaching commands fpr namespaces, we always re-attach them instead.
Fixes #5202
=> Always reattach subcommands

php/WP_CLI/Runner.php
=> Add warning message to let the user know when `WP_CLI_SSH_PRE_CMD` is in use

features/bootstrap.feature, features/help.feature
If I read the code and the test correctly, this is just testing for a bug that was now fixed with release 5.2 of WP Core.
=> Remove bug-provoking test for a bug in WPDB that was fixed

composer.json, composer.lock
We forgot to update the branch alias for the new alpha version, which breaks with the latest `wp-cli/core-command` dependency.
=> Update branch alias for new alpha version

.github/ISSUE_TEMPLATE/4-REGULAR_RELEASE_CHECKLIST.md
This was not done for last release, so some inter-dependencies broke, as the `dev` version does not meet the release criteria.
=> Add a check to update the branch alias

features/flags.feature, php/WP_CLI/Runner.php, php/utils.php, tests/test-utils.php
Hello!
This improves handling for `vagrant` scheme by caching the output of `vagrant ssh-config`, and using values within to convert the call to use the standard `ssh` scheme.
This helps speed up sample requests up to 3 seconds ( ie: sometimes **700%** ) in all calls.
Before:
```
time wp --ssh=vagrant:default cli version                                                                                  WP-CLI 2.1.0
Connection to 127.0.0.1 closed.
3.23 real         2.26 user         0.43 sys
time wp --ssh=vagrant:default option get siteurl                                                                          
https:///wordpress
Connection to 127.0.0.1 closed.
4.14 real         2.27 user         0.44 sys
```
After:
```
time wp --ssh=vagrant:default cli version …
```
=> Speed up vagrant scheme calls by caching vagrant ssh-config

.travis.yml
=> Fix: Move PHP version configuration to stage

php/WP_CLI/Bootstrap/RegisterDeferredCommands.php
This PR addresses https://github.com/wp-cli/wp-cli/issues/4893 to print the output of deferred additions in a prettier format.
Before:
```
Debug (bootstrap): Adding deferred command: premise-authnet cancel-subscription => {"parent":"premise-authnet","callable":[{},"cancel_subscription"],"args":{"is_deferred":true}} (0.828s)
```
After:
```
Debug (bootstrap): Adding deferred command:  premise-authnet cancel-subscription (parent: premise-authnet, callable: Array::cancel_subscription(), args: {"is_deferred":true}) (0.828s)
```
=> Improve "Adding deferred command..." debug output (Closes: #4893)

php/WP_CLI/Formatter.php
Fixes the PHPDoc parameter annotation for `Formatter::display_items()` (fixes #5269).
=> Fix PHPDoc annotation for Formatter:display_items

php/WP_CLI/Formatter.php, php/class-wp-cli.php, php/utils-wp.php
Replaces uses of `is_a()` function with with the faster (and more readable) `instanceof` operator.
=> Replace is_a() with instanceof operator

php/WP_CLI/DocParser.php, php/commands/src/Help_Command.php
PHP 7.4 deprecates the `implode( array $pieces, string $glue )` function
signature.
Switch to `implode( string $glue, array $pieces )`.
https://wiki.php.net/rfc/deprecations_php_7_4#implode_parameter_order_mix
This resolves some deprecation notices under PHP 7.4. E.g.:
> Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in …wp-cli/php/WP_CLI/DocParser.php on line 75
=> PHP 7.4 Compatibility: Update `implode()` calls.

php/WP_CLI/Compat/FeedbackMethodTrait.php, php/WP_CLI/Compat/Min_PHP_5_4/FeedbackMethodTrait.php, php/WP_CLI/Compat/Min_PHP_5_6/FeedbackMethodTrait.php, php/WP_CLI/UpgraderSkin.php
WordPress trunk is doing refactorings to use more PHP 5.6+ features since the minimum PHP version was raised.
As long as we stick to PHP 5.4, we need to provide compatibility mechanisms to deal with this.
This PR adds a `Compat` namespace to systematically provide compatibility code that can be easily retraced and removed later again.
This should solve the build failure found at https://travis-ci.org/wp-cli/wp-cli/jobs/586215547#L736
Related #5282
=> Add PHP-version-specific traits to extend the upgrader skin feedback method

php/WP_CLI/Iterators/CSV.php
This makes it possible to start a progress bar for a CSV file:
```php
$iterator = new \WP_CLI\Iterators\CSV( $csv_file );
$progress = \WP_CLI\Utils\make_progress_bar( 'Processing list', count( $iterator ) );
```
The use of `SplFileObject` avoids reading the entire file to memory.
=> Implement `\Countable` for `\WP_CLI\Iterators\CSV`

features/utils-wp.feature
The table `wp_blog_versions` was never used and will be removed in WordPress 5.3.
This PR removes all checks for that table from the Behat tests so they don't break with the next Core version.
=> Remove checks for `wp_blog_versions` table in Behat tests

php/utils-wp.php, php/wp-settings-cli.php
Reverts wp-cli/wp-cli#5300, as the `wp-settings-cli.php` is not actually being used for any WordPress Core version after `4.6-alpha-37575`:
https://github.com/wp-cli/wp-cli/blob/538d9be5ad490bd07b946dcd3b52b4d1c34dc193/php/WP_CLI/Runner.php#L1228-L1241
=> Revert "Refresh `wp-settings-cli.php` to reflect changes to Core `wp-settings.php`"

php/WP_CLI/Runner.php
The template functions might be needed in the starter content functionality for some themes.
This hopefully fixes the broken tests with TwentyTwenty starter content: https://travis-ci.org/wp-cli/automated-tests/jobs/605262104#L1103-L1109
=> Load template functions in Runner

.travis.yml, composer.json, composer.lock, php/WP_CLI/Dispatcher/CommandFactory.php
Also add PHP 7.4 to the testing matrix first to see if we detect this problem in our CI.
Fixes #5304
=> Patch `mustache/mustache` to avoid throwing notices on PHP 7.4

php/commands/src/CLI_Alias_Command.php, php/commands/src/CLI_Cache_Command.php, php/commands/src/CLI_Command.php, php/commands/src/Help_Command.php
This pull request converts the help docs for the alias, cli, cache, and help commands to use third-person singular verbs.
This is in response to issue #4542
=> Converted alias, cli, cache, and help commands help summaries to use third-person singular verbs.

php/WP_CLI/Runner.php
This is needed to keep the TwentyTwenty theme (and maybe others) to fatal when downgrading Core, as it is the recommended way of checking whether to initialize starter content, an action that can only be done directly in `functions.php`.
=> Polyfill `is_customize_preview()`

composer.json, composer.lock
Also revert PHP 7.4 patch from #5306 that is now no longer necessary.
Fixes #5325.
=> Update mustache/mustache to version 2.13

php/class-wp-cli.php
Fixes #5267.
Note: I don't know if returning $e->getMessage() or converting exception to string is preferred. PR does the former.
=> Support exceptions in WP_CLI::error_to_string method

php/utils.php, tests/test-utils.php
Due to the way wp-cli modifies the wp-config.php when loading, and the fact that Windows allows single quotes in account names, a user with a single quote in their account name will get fatal errors when the wp-config.php const replacement ends up like this: 
```PHP
/* That's all, stop editing! Happy publishing. */
/** Absolute path to the WordPress directory. */
if ( ! defined( 'ABSPATH' ) ) {
define( 'ABSPATH', 'C:\Users\local's\Local Sites\dickens-llc\app\public' . '/' );
}
```
Notice the single quote in the username breaking the quoted path. 
More details on this issue can be found here: https://github.com/wp-cli/wp-cli/issues/1631
This patch resolved the problem for us, and we're currently using it in a forked build. Would love to see it included in core!
=> Escape path before `wp-config.php` string replacement

php/WP_CLI/ComposerIO.php
Composer seems to sometimes output arrays of strings through the ComposerIO interface, and this breaks our trim logic that only expects single strings.
This PR turns the logic into a loop over an array of strings instead to avoid throwing a notice.
See https://travis-ci.org/github/wp-cli/automated-tests/jobs/666134609#L2615
=> Allow for array of strings in ComposerIO

features/utils.feature, php/utils.php
Change the `Utils\run_mysql_command()` so that it can also return data & errors when running a query via the `mysql` binary.
Fixes #5383
=> Let `Utils\run_mysql_command()` return data

php/commands/src/CLI_Command.php, php/utils.php
- Adds `MySQL binary`, `MySQL version` and `SQL modes`
- Syncs `cli info --json` to mirror info in `cli info`
Fixes #5385
=> Add database info to `cli info` command

.travis.yml, composer.lock, features/bootstrap.feature
This PR changes the Travis CI configuration to use the `xenial` Ubuntu distribution instead of the `trusty` one by default.
=> Bump Travis CI OS from `trusty` to `xenial`

php/class-wp-cli.php, tests/test-wp-cli.php
=> Throw exception when misusing `error_to_string()`

composer.json
Fixes #5365.
Tested with https://github.com/wp-cli/wp-cli-dev and seems to work, all tests seem to pass.
=> Include classmap in order to fix composer 2.0 deprecation notices.

features/flags.feature
A Travis failure was introduced somewhere in the WordPress Core 5.5 development cycle where the `$_SERVER` superglobal treats the server port as an actual number, not a string.
This broke one of our Travis tests: https://travis-ci.org/github/wp-cli/automated-tests/jobs/705037602#L1019-L1026
This PR differentiates between WP versions to support both interpretations.
=> Fix `SERVER_PORT` JSON encoding failure

features/help.feature, php/WP_CLI/Dispatcher/CompositeCommand.php, templates/man-params.mustache
Fixes https://github.com/wp-cli/ideas/issues/104
=> Allow user to suppress global parameters info from help display

php/utils-wp.php
- Updated link and name of [WP Redis](https://wordpress.org/plugins/wp-redis/) (it's now maintained by Pantheon)
- Added support for [Redis Object Cache](https://wordpress.org/plugins/redis-cache/), which doesn't have a public `$redis` property
=> Add support for Redis Object Cache

php/utils.php
This is needed to address https://github.com/wp-cli/db-command/issues/173.
=> Add $interactive arg for run_mysql_command()

php/WP_CLI/Runner.php
As already stated in the code __they're aware of the risks!__
Also good point had @iandunn in https://github.com/wp-cli/wp-cli/issues/1838#issuecomment-505592503
Composer (which is used here for running unit and behat test scripts) allows superuser through environment
=> Allow root from environment

tests/test-extractor.php
The non static `create_test_directory_structure` and `recursive_scandir` methods in `Extractor_Test` class are called statically in same class in other methods. This PR just add static keyword to those methods and fix the problem.
=> Fix non static methods in Extractor_Test class call statically

php/WP_CLI/PackageManagerEventSubscriber.php
=> Skip using removed `Operation::getReason()` for Composer v2 compat

php/utils.php
The previous didn't consider if there was only one quote character on a single line. It broke on the "// That's all, stop editing! Happy blogging." comment.
See https://regex101.com/r/9hXp5d/5 for the example.
See https://regex101.com/r/9hXp5d/7 for the fix in action.
Fixes https://github.com/wp-cli/extension-command/issues/247
=> Improve regex to match `__FILE__` and `__DIR__` magic constants

features/help.feature
On PHP 8 a fatal error is issued if a magic method doesn't match the [expected signature](https://www.php.net/manual/en/language.oop5.magic.php#object.set-state).
```
PHP Fatal error:  Method Test_Magic_Methods::__set_state() must take exactly 1 argument
```
=> [PHP 8] Add properties argument to __set_state magic method

php/WP_CLI/Dispatcher/CommandFactory.php, php/class-wp-cli.php, php/utils.php, tests/test-utils.php
On PHP 8, an array of a class name and instance method name is no longer
considered a callable. This commit adds an additional check to see if
the command is a pair of a class name and method name that exists on that
class before rejecting the command registration.
Fixes #5472.
=> Fix registering a command with a class and method name pair on PHP 8.

php/WP_CLI/Runner.php
The `Runner` has a magic `__get()` method that lets consumers retrieve the private properties in a read-only form.
This PR adds a docblock documenting these read-only properties so as to improve static analysis.
=> Add magic properties to docblock

php/class-wp-cli.php
All of these methods accept `string|WP_Error|Exception|Throwable`.
=> Update docblocks for methods that accept error objects

php/utils.php, tests/test-utils.php
- PHP setting 'curl.cainfo' enforces the CA file to use,
- Otherwise fallback to system-wide defaults, then use the embedded CA file.
Fixes #5111
=> Use custom certificate if provided

php/utils.php, tests/mock-requests-transport.php, tests/test-utils.php
This PR fixes #5463 in that it respects the given value of `$options['verify']` rather than overwriting it with the path to the default CA cert.
It does this partly by extracting the default CA cert detection/lookup into a new utility: `get_default_cacert`.
The tests added also include a very simple `Mock_Requests_Transport` class to make testing the `http_request` call much cleaner and simpler, but is only used in the added test. Regarding the way this class is loaded, normally I would expect it to be autoloaded but there didn't seem to be any existing configuration for this yet so I left that out for now for simplicity.
=> Fix 5463 `Utils\http_request` verify option

php/class-wp-cli.php, php/commands/src/CLI_Command.php, php/utils-wp.php, php/utils.php, tests/test-utils.php
This PR disables the automatic retrying of `Utils/http_request()` that was skipping certificate validation.
The new default is to produce a hard error on certificate errors.
This PR also adds a new `--insecure` flag to the `cli update` command that turns this retrying back on when explicitly requested, which allows manually going back to the previous behavior.
Subsequent PRs on the command repositories will add a similar `--insecure` flag to the appropriate commands on the following repositories:
=> Disable automatic retry by default on certificate validation error

php/WP_CLI/Fetchers/Base.php, php/WP_CLI/Fetchers/Comment.php, php/WP_CLI/Fetchers/Post.php, php/WP_CLI/Fetchers/Site.php, php/WP_CLI/Fetchers/User.php, php/WP_CLI/Runner.php
Moving the fetcher implementations out of the framework and into the `wp-cli/entity-command` broke the `--user` flag when the `wp-cli/entity-command` package was not loaded.
This PR moves the fetcher implementations back into the framework.
Fixes https://github.com/wp-cli/wp-cli/issues/5328
=> Move fetcher implementations back into framework

composer.lock, features/utils.feature, php/utils.php
This fixes the out-of-memory errors on `db export` to `STDOUT` by using `fpassthru()` when `$send_to_shell` is `true`, instead of using `stream_get_contents()`.
This is technically not a full fix, as the stream is still fully read when `$send_to_shell` is `false`, however there's no current use case I can think of where that would matter.
Fixes https://github.com/wp-cli/db-command/issues/195
=> Fix OOM issues when exporting to STDOUT

php/WP_CLI/Loggers/Quiet.php, php/WP_CLI/Runner.php, php/class-wp-cli.php, tests/test-extractor.php, tests/test-file-cache.php, tests/test-utils.php
This PR:
- makes the current logger instance accessible outside of `WP_CLI`, so it is easier to roll back any logger changes that are being done;
- adds colorization control to the `Quiet` logger, so that it doesn't create colorization success and error messages.
=> Make logger accessible and add colorization control to `Quiet` logger

php/WP_CLI/Runner.php
Currently, the `wp core multisite-install` command creates sites called "Fake Site".
```
Just another Fake Site site
 Welcome to Fake Site
```
This is hardcoded in Runner.php. This PR changes the terminology to replace `Fake Site` with `WordPress`, which is more expected and user friendly.
There's likely room for improvement here to use the WP default rather than hardcoding a new value, but this at least removes the unexpected `Fake Site` string.
Fixes #5515
=> Change "Fake Site" site name to "WordPress" wp core multisite-install subcommand

features/hook.feature, php/WP_CLI/Runner.php
This PR passes in some args to the `before_run_command` hook so callbacks have some more context to base their logic off of.
The reason for proposing this change is because of a particular use case I have where I'm implementing some logging to track CLI commands that are being run in our codebase. I currently have an implementation that looks something like:
```php
WP_CLI::add_hook( 'before_run_command', function() {
$runner  = WP_CLI::get_runner();
$command = $runner->find_command_to_run( $runner->arguments )[0];
log( $command->get_name() );
} );
```
This works for commands invoked from the command line but doesn't work for commands invoked via `WP_CLI::run_command` with `launch => false` set. This is because `run_command` will call the `Runner->run_command()` method directly so the …
=> Pass in args to before_run_command hook

composer.json
See details here -> https://github.com/Roave/SecurityAdvisories#stability
It's causing issues with compatibilities with other projects
=> Updated default branch for roave/security-advisories

features/bootstrap.feature, php/class-wp-cli.php
There was a regression in the code that handles command namespaces that made it impossible to extend an existing command class.
This PR reverts the regression and adds a test scenario to ensure this type of extension will not be regressing again.
Fixes #5274
=> Fix regression that broke extending existing commands

php/WP_CLI/Configurator.php
As per issue #5558 Fixed unused variable `$positional_arg` in foreach loop and replaced to `$positional` variable.
=> Fixed wrong variable used in parsing args.

php/WP_CLI/Runner.php
Starting with PHP 8.1, `mysqli` has a new default error reporting mode that throws exceptions.
As WordPress handles error conditions on its own, this is not needed.
The default error mode is already adapted with WP Core 5.9+, but on older versions the above changes means that you cannot even update WordPress sites on PHP 8.1, as they fatal with an uncaught exception.
Therefore, WP-CLI also sets the default error reporting mode now to avoid these fatals.
=> Fix default `mysqli` error reporting mode for PHP 8.1+

composer.json, php/WP_CLI/Compat/MustacheTokenizer.php, php/utils.php
Instead of pulling in a fork to get the temporary fix for PHP 8.1 in the PR https://github.com/bobthecow/mustache.php/pull/380, this PR uses a class extension instead that overrides the default tokenizer.
This leads to less downstream issues with Composer dependency resolution.
=> Use Mustache work-around for PHP 8.1 compat

features/bootstrap.feature, features/config.feature, php/WP_CLI/Runner.php
This PR adds byte-order marks (BOM) detection to the logic that parses the `wp-config.php` file for loading WP within the WP-CLI context.
If a BOM is detected, WP-CLI issues a warning and then strips that BOM for further parsing.
Fixes #5577 
Fixes #5578
=> Detect and ignore BOMs

features/help.feature, php/WP_CLI/Fetchers/User.php
There seems to be a fundamental difference between `get_user_by()` and `get_users()`. Where the former creates a new `WP_User` object and initiates it via an array of data, the latter puts the actual database result into the `WP_User`'s ` $data` property via its constructor.
The end result is that the set of available properties is different. As an example, when a user is fetched via `get_users()`, it knows about its `nickname`. If it is fetched by `get_user_by()`, the `nickname` property does not exist.
This PR changes the `UserFetcher` to rely on `get_users()` (instead of `get_user_by()`), to make all properties available.
=> Use proper `WP_User_Query` for fetching users

php/class-wp-cli.php
Previously if you were to do the following, you would get an undefined function error instead of the expected exception for `wp one` not being able to have subcommands:
```php
WP_CLI::add_command('one', function() {});
WP_CLI::add_command('one two', function() {});
```
=> Fix undefined function error

php/wp-settings-cli.php
Fixed: https://github.com/wp-cli/wp-cli/issues/5629
As per the inline document, it should be required in the filter.
=> Add missing `$upgrade` argument to `enable_maintenance_mode` filter

php/WP_CLI/Runner.php, php/utils.php
**Ensure `Runner::find_wp_root()` always returns a directory**
According to the docblock, the method is supposed to default to the current working dir, but in reality it could return `null` if nothing was found.
This breaks other methods like `::set_wp_root()` which expect a string.
Prevents PHP deprecation notices because `null` was passed to `realpath()`.
**Handle null values in `trailingslashit` util** 
Prevents PHP deprecation notices when inadvertently passing `null` to the function and thus `rtrim`.
=> Address some PHP 8.1 deprecation notices

composer.json
This fixes test failures in the test scenarios that build a custom Composer file.
=> Require `v3.1.6` of `wp-cli/wp-cli-tests`

features/config.feature, php/WP_CLI/Configurator.php, php/wp-cli.php
* Moves `config-spec.php` loading to a standalone method.
* Calls `WP_CLI_CONFIG_SPEC_FILTER_CALLBACK` against `$config_spec` if callback is defined.
* Introduces `WP_CLI_EARLY_REQUIRE` environment variable for early loading of a PHP file.
Fixes #5649
=> Load `config-spec.php` in a "filterable" way

features/context.feature, php/WP_CLI/Context/Admin.php
The `-context=admin` logic was hooking some of its logic to the `admin_init` action. However, as the loading was adapted, the requirement for triggering the `admin_init` action ended up within the action's closures, causing the entire construct to not be executed at all.
This PR changes the `--context=admin` logic to use `plugins_loaded` with the lowest possible priority instead of `admin_init`.
=> Use different action for admin context logic

php/utils.php
This PR adds a check to the `get_php_binary()` utility method so that when running `wp-cli` as a PHAR bundle the `wp --info` command will *always* output the shell's current PHP version.
Fixes https://github.com/wp-cli/wp-cli/issues/5615
I believe this is a _safe_ method of determining whether or not the `wp-cli` binary is a PHAR or not but if there's a preferred or better method I'll switch this to that.
Existing tests pass and I didn't add any new ones due to the usage of the constant.
=> Always return PHP_BINARY when using a PHAR bundle

php/class-wp-cli.php, php/commands/src/CLI_Command.php, php/utils.php
Adds the cache directory path to the `wp --info` output.
Fixes: #5580
=> Add cache dir path to info output FIX #5580

features/utils-wp.feature, php/utils-wp.php
Tests have been failing for WP trunk during the WP 6.1 development cycle because the `global_terms_enabled()` function has been incorrectly deprecated.
This PR internalizes that function to avoid errors.
See https://core.trac.wordpress.org/ticket/21734#comment:34
=> Internalize `global_terms_enabled()`

php/utils.php
Wrapping the commands in double quotes conflicts with various flags also using double quotes. 
For example when running `db export` you get.
`Warning: Failed to get current character set of the posts table. Reason: '"mysql --no-defaults --no-auto-rehash --batch --skip-column-names --host="localhost" --user="mat" --default-ch
aracter-set="utf8" --execute="SELECT' is not recognized as an internal or external command,
operable program or batch file.`
Removing the quotes resolves the issue.
=> Fix proc_open_compat util on Windows

php/utils.php
The PHP utilities can be used by the test framework, etc. without directly loading WP-CLI.
Introduced by #5672
Fixes https://github.com/wp-cli/wp-cli-tests/issues/154
=> Ensure `WP_CLI_ROOT` is defined before accessing it

php/WP_CLI/Dispatcher/CompositeCommand.php
This PR fixes the following deprecation warnings when running `wp --info` with PHP 8.2 RC6:
```
Deprecated: Creation of dynamic property WP_CLI\Dispatcher\CompositeCommand::$longdesc is deprecated in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CompositeCommand.php on line 38
Deprecated: Creation of dynamic property WP_CLI\Dispatcher\Subcommand::$longdesc is deprecated in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CompositeCommand.php on line 38
Deprecated: Creation of dynamic property WP_CLI\Dispatcher\CommandNamespace::$longdesc is deprecated in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CompositeCommand.php on line 38
```
Dynamic properties are deprecated in PHP 8.2. The solution was to simply declare …
=> PHP 8.2: explicitly declare CompositeCommand::$longdesc to fix deprecation warning

php/WP_CLI/Dispatcher/Subcommand.php, php/class-wp-cli.php
Hello!
**Why**: For `__invoke` commands, the `before_invoke` and `after_invoke` hooks run twice, creating potential unexpected behavior.
**Solution**: I propose an easy fix: pass the command name to the callback, so that it can choose when to run.
If you think it is a viable solution, I'll add tests :-)
Cheers,
Cocco
=> Add name context to before_invoke and after_invoke

php/utils.php
Docblocks are absolute (FQCN).
=> Fix return type of make_progress_bar

php/WP_CLI/WpOrgApi.php
Currently, the `wp core download` command returns a deprecated notice triggered by WpOrgApi class:
```
$ bin/wp core download --force
PHP Deprecated:  http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated in /Volumes/Sites/wp-cli/php/WP_CLI/WpOrgApi.php on line 135
Deprecated: http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated in /Volumes/Sites/wp-cli/php/WP_CLI/WpOrgApi.php on line 135
```
In this PR, I propose to fix the notice.
=> Fix deprecation notice triggered in WpOrgApi class in PHP 8.1

php/WP_CLI/Process.php
Fixes https://github.com/wp-cli/wp-cli/issues/5710
=> Check that `proc_open()` is available in `Process::run()`

features/config.feature
The current test fails on MacOS because of:
`sed: -I or -i may not be used with stdin`
After fixing that,  I found sed on MacOS works in text mode vs binary mode and it is difficult have it make a binary change like this. Use AWK instead since it works the same everywhere in this case.
Fixes #5723
=> Use AWK instead of sed to create BOM in feature test

features/runcommand.feature, php/class-wp-cli.php
Per https://wordpress.slack.com/archives/C02RP4T41/p1673268015148999?thread_ts=1672934225.683679&cid=C02RP4T41
I have a command that calls `WP_CLI::runcommand` a lot and I want to set some default global options for most of these (particularly `--skip-themes --skip-plugins`). I also have default global options for `WP_CLI::runcommand` itself.
Currently, this ends up looking something like:
```
private $default_cli_opts = array(
'return'       => 'all',
'exit_error'   => false,
);
private $default_command_opts = '--skip-themes --skip-plugins';
WP_CLI::runcommand( "config has set WPCACHEHOME --path=$path " . $this->default_command_opts, $this->default_cli_opts );
etc...
```
It would be nice to be able to keep these options in a single place like:
```
private $default_cli_opts = array( …
```
=> Add runtime_args to options array for runcommand

php/WP_CLI/Iterators/Transform.php
PHP 8.1 shows a PHP Deprecated warning for an improper return type for `WP_CLI/Iterators/Transform::transform()`.
Fixes https://github.com/wp-cli/wp-cli/issues/5742
=> fix PHP Deprecation for 8.1

features/flags.feature, php/WP_CLI/Fetchers/User.php
Also squelches with a warning when there's an ambiguous match.
To be documented with https://github.com/wp-cli/wp-cli/issues/5739
Fixes #5706
=> Use `WP_CLI_FORCE_USER_LOGIN=1` to force `--user=<login>`

php/commands/src/Help_Command.php
Not all versions of less offer `-r` as seen in #5758
Also, modern versions of LESS have the following warning when viewing man pages:
From `man less`
```
USE OF THE -r OPTION IS NOT RECOMMENDED.
-R or --RAW-CONTROL-CHARS is defined as:
Like -r, but only ANSI "color" escape sequences and OSC 8 hyperlink sequences are output in "raw" form.
```
Reference: https://man7.org/linux/man-pages/man1/less.1.html
Fixes #5758
=> Use -R instead of -r for fallback pager command

features/bootstrap.feature
The warning was added in https://github.com/wp-cli/cache-command/pull/86
=> Update test to reflect warning when `--url=<url>` is provided

composer.json, features/requests.feature, php/WP_CLI/Bootstrap/IncludeFrameworkAutoloader.php, php/utils.php, tests/mock-requests-transport.php, tests/test-utils.php
Fixes #5623
This PR upgrades the included dependency on the Requests library to v2.
It includes namespace changes to the integration points with the Requests library as well as a few tests to ensure it works across both old and new integrations of Requests into WordPress core.
=> Upgrade WP-CLI to Requests v2

php/utils.php
While trying to debug the following issue, I noticed that we have a triple slash in the Phar prefix:
I suspect this comes from an empty `WP_CLI_PHAR_PATH` that would already end up being `/`.
=> Use rtrim on phar-safe path to avoid double slash

features/command.feature
Fixes `Creation of dynamic property Foo_Class::$message is deprecated type errors`
=> Fix some PHP 8.2 depreciation notices in behat tests

php/utils.php
The Requests library already points to its own bundled certificates file in some instances. In case the library is also compiled into a Phar file, cURL will not be able to use the certificate, as it cannot read the file from within the Phar archive. We'll need to extract the file into a temporary location first for this to work properly.
This fixes the following issue observed during deployment runs:
=> Extract cacert from Phar for cURL

php/utils.php
Reverts wp-cli/wp-cli#5777
See https://github.com/wp-cli/wp-cli/issues/5779
=> Revert "Extract cacert from Phar for cURL"

php/utils-wp.php
Call the function  `wp_cache_flush_runtime` in `wp_clear_object_cache `. This function has been in core since 6.0.0 ( https://github.com/WordPress/wordpress-develop/commit/c98f4c04db13a1c3db14345db4cff116dd01bf51) and is designed to perform the what currently `wp_clear_object_cache` does. 
Checks to see if `wp_cache_flush_runtime` and `wp_cache_supports` exists before b/c
Fixes #5769
=> Use `wp_cache_flush_runtime` if supported.

php/utils-wp.php
Reports from Cloudways indicate that there is an intermittent issue with the `WP_Upgrader_Skin` class.
```
PHP Fatal error:  Uncaught Error: Class 'WP_Upgrader_Skin' not found in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/UpgraderSkin.php:13
```
I have yet not been able to replicate the issue, but this PR already adds hardening around that code section which potentially avoids fatal errors.
=> Harden loading of upgrader

php/WP_CLI/Iterators/Query.php
Fixes PHP 8.1 deprecation by adding `#[\ReturnTypeWillChange]` to Iterator methods.
Fixes #5806
=> Fix PHP 8.1 deprecation: ReturnTypeWillChange

php/commands/src/CLI_Command.php
[Link to original issue.](https://github.com/wp-cli/wp-cli/issues/5815)
[Link to comment about existing tests.](https://github.com/wp-cli/wp-cli/issues/5815#issuecomment-1645834087)
This fix escapes a command that was causing `wp cli update` to fail when the `$php_binary` path contained a space.
=> Escape shell command in `wp-cli update`

php/commands/src/CLI_Command.php
https://github.com/wp-cli/wp-cli/issues/5815#issuecomment-1663059289
=> Revert "Escape shell command in `wp-cli update`"

features/help.feature
Tests involving the WP release can now only run on PHP 7.0+ due to the new minimum requirement.
=> Run test only on PHP 7.0+

features/skip-themes.feature
The latest Gutenberg release now requires PHP 7.0 too. This fixes a test failure on PHP 5.6
=> Require PHP 7+ for installing Gutenberg

features/bootstrap.feature
They install the latest WP version, which now requires PHP 7.0
=> Require PHP 7.0 for tests installing WP via Composer

features/skip-themes.feature, php/utils-wp.php
Fixes https://github.com/wp-cli/wp-cli/issues/5240
Trying to fix this upstream is too much of a rabbit hole. Instead, let's give the user a more helpful pointer:
```
$ wp --skip-themes option get home
Fatal error: Uncaught Error: Call to undefined function genesis_register_sidebar() in /Users/danielbachhuber/projects/vanilla/wp-content/themes/functions.php:3
Stack trace:
#0 /Users/danielbachhuber/projects/vanilla/wp-settings.php(599): include()
#1 /Users/danielbachhuber/projects/wp-cli-dev/wp-cli/php/WP_CLI/Runner.php(1349): require('/Users/danielba...')
#2 /Users/danielbachhuber/projects/wp-cli-dev/wp-cli/php/WP_CLI/Runner.php(1267): WP_CLI\Runner->load_wordpress()
#3 /Users/danielbachhuber/projects/wp-cli-dev/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#4 …
```
=> Display a custom error message when `themes/functions.php` fatals

php/class-wp-cli.php
The `$callable` can be a class name or an object as well, so allow `object` and `string` types in the type hint.
I've noticed this issue while analyzing a plugin of mine with PHPStan on level 7.
=> Update type hint of $callable parameter in add_command() method

features/aliases.feature, php/WP_CLI/Configurator.php, php/WP_CLI/Runner.php
SSH has the capability to route traffic through a proxy. This is done using the [`-J xxx`](https://www.redhat.com/sysadmin/ssh-proxy-bastion-proxyjump) argument. The ProxyJump can be used for security purposes by limiting access to remote servers to specific IP addresses.
Previously it had to use wp-cli with a proxy in between. The only somewhat practical way was adding it to your personal `~/.ssh/config`:
```
Host production
HostName xxx.xxx.xxx.xxx
ProxyCommand ssh -q -W %h:22 vagrant
```
But this is technical and has to be done on every single machine in a team of multiple contributors.
This PR adds an option `proxyjump` to the alias specification so the `wp-cli.yml` config file can specify a comon proxy for all traffic to go through.
The change also includes a fix for the `key` …
=> Add support for the proxyjump key

features/requests.feature, php/WP_CLI/Bootstrap/IncludeRequestsAutoloader.php
Fixes https://github.com/wp-cli/wp-cli/issues/5816
Ensures WP-CLI works with older versions of WordPress with `--path=` is defined via an alias.
=> Respect alias `--path=` in `IncludeRequestsAutoloader`

phpcs.xml.dist
It looks like `WordPress.CodeAnalysis.AssignmentInCondition.Found` has been renamed upstream and is now `Generic.CodeAnalysis.AssignmentInCondition.FoundInWhileCondition`
I don't believe this repo actually does an assignment inside of a while condition at the moment -- which is why there weren't any test failures when updating to WPCS 3.0.
I had one of these in a local wp-cli project and when searching for the origin of that exclude I realized that it had been copied from the phpcs.xml file in this repo which I used as a starting point.
While I was here I also removed the PSR2 rule below it based on the comment suggesting it should be removed once PHPCS is above 3.5.0 (it is).
=> Update phpcs.xml to match new WPCS rules

features/requests.feature, php/WP_CLI/Runner.php
WordPress 6.4 added some memoization that impacts `get_template_directory()` and `get_stylesheet_directory()`. Fortunately, we only need to noop the global to fix `--skip-themes`.
Fixes https://github.com/wp-cli/wp-cli/issues/5839
=> Fix `--skip-themes` for WordPress 6.4

php/WP_CLI/Runner.php
This adds debugging output to better debug issues like here: https://github.com/wp-cli/automated-tests/actions/runs/6374307001/job/17298802403#step:14:549
=> Add debugging output for @when command registration

php/wp-settings-cli.php
**Documentation**:
Updated some inline documentation according to [PHP Documentation Standards](https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/)
Closes https://github.com/wp-cli/wp-cli/issues/5852
=> Updated Inline PHP Documentation

features/bootstrap.feature, features/framework.feature, features/help.feature, features/hook.feature, features/requests.feature, features/utils-wp.feature, features/utils.feature, php/utils-wp.php
One functionality change:
In `wp_not_installed()` the list of found table prefixes is now explicitly sorted in ascending order. Without that, order would differ between MySQL and SQLite.
=> Update tests to accommodate for SQLite

php/utils.php
Previously in https://github.com/wp-cli/handbook/pull/345 🙃
Edit: forgot to add 🕵️‍♂️ hack day: Related https://github.com/wp-cli/wp-cli/issues/5859
=> Add missing documentation for `$data` attribute in `http_request()`

php/WP_CLI/Exceptions/NonExistentKeyException.php, php/WP_CLI/Traversers/RecursiveDataStructureTraverser.php, tests/WP_CLI/Traversers/RecursiveDataStructureTraverserTest.php
Fixes: https://github.com/wp-cli/wp-cli/issues/5837
Related: https://github.com/wp-cli/wp-cli/issues/5859
=> Move `RecursiveDataStructureTraverser` to `wp-cli/wp-cli` package

features/prompt.feature, php/WP_CLI/Dispatcher/Subcommand.php
When using the `--prompt` argument on a command, the executed command gets logged, showing the command and arguments the prompt had collected.
This logged command, however, lacks all required `$args` and only lists the `$assoc_args` (that are not empty).
This patch will add the required arguments as well.
Fixes #5768 
Related: https://github.com/wp-cli/wp-cli/issues/5859
=> Add missing required arguments when using `--prompt`

features/aliases.feature, features/flags.feature, php/WP_CLI/Runner.php
Fixes: #5378 
Related #5859 
As reported in the above ticket, in case the SSH command fails it doesn't output the exact reason why it's failing because it uses the `-q` flag in it which suppresses SSH command logs as per its [man page](https://man7.org/linux/man-pages/man1/ssh.1.html#:~:text=%2Dq%20%20%20%20%20%20Quiet%20mode.%20%20Causes%20most%20warning%20and%20diagnostic%20messages%20to%0A%20%20%20%20%20%20%20%20%20%20%20%20%20be%20suppressed.).
Suppressing the SSH logs makes sense to keep the WP CLI output cleaner, but it can be hard to debug due to the lack of proper logs. This PR proposes to replace the `-q` flag with `-vvv` flag while using the `--debug` flag with the `wp` command.
<details><summary> <code>wp --ssh=wordpress:/my/path --version</code> </summary>
<br/>
```sh
> wp …
```
=> Add verbosity level and quiet flag in ssh command based on debug flag

php/utils.php
Adds the `has_stdin()` function to `WP-CLI\Utils` namespace to allow it to be used across both `wp-cli/entity-command` and `wp-cli/cache-command`.
=> Add `WP_CLI\Utils\has_stdin()` function

php/WP_CLI/Context/Admin.php
Fixed Issue: https://github.com/wp-cli/wp-cli/issues/5876
=> Updated Doc Block for Admin.php

features/runner.feature, php/WP_CLI/Runner.php
This PR suggests using `wp network meta` if the user tries using `wp network option`.
Related to: https://github.com/wp-cli/entity-command/issues/322
I'll submit a separate PR will be submitted to the entity-command repo to add a feature test.
=> Suggest 'network meta' intead of 'network option'

php/class-wp-cli.php, tests/test-configurator.php
In get_config(), use has_config() to test for key existence instead of equivalent isset() which throws a warning for null values.
A null value can occur if the option is present, but without a value. Certain config values, such as --url, default to null causing has_config() to be true, while throwing a warning in get_config(). This change provides consistency between has_config() and get_config().
Fixes #5353.
=> Use has_config() in get_config() to prevent warnings on null values

php/WP_CLI/WpOrgApi.php
Required for wp-cli/extension-command#394
=> WpOrgApi: allow specifying fields request param

php/WP_CLI/Formatter.php
Fixes #5744.
When a WP-CLI command outputs a table, the table formatter:
1. Checks whether colorization is enabled. If so, disables it.
2. Outputs the table.
3. If colorization was previously enabled, re-enables it.
The problem is that we're using `Colors::shouldColorize()` to determine whether colorization is enabled. `Colors::shouldColorize()` returns `true` if (a) the _terminal_ is capable of colors, AND (b) no output has yet been produced by the colorizer.
This means that if WP-CLI outputs a table _before_ it outputs any colorized messages, it will _always_ switch to color mode after the table has bveen printed.
You can demonstrate this for yourself by adding the line `WP_CLI::success( 'nothing here!' );` to the top of `function show_table`. This makes the problem go away (but prints …
=> Update `Formatter\show_table` to use `Runner->in_color` rather than `shouldColorize`

features/cli-bash-completion.feature, php/WP_CLI/Completions.php
Make options complete in a manner more consistent with other shell programs.
Closes #5845.
This relies on `array_key_last()` which may need to be polyfilled if it isn't already.
=> Standard completion of current option

php/class-wp-cli.php
Please see #5896 for details and code to replicate.
tl;dr In versions of PHP greater than 8.1.x, when `WP_CLI::error()` and `WP_CLI::halt()` are called in a separate command via `WP_CLI::runcommand()`, then `PHP Deprecated` notices are written to the logs. Passing an empty string is compatible with the signature of the `Exception` constructor and avoids the warnings.
Edit: since there are no functional changes in this PR, I haven't included tests.
=> Fix PHP deprecation warnings

php/utils.php
Please see #5898 for details.
tl;dr In versions of PHP greater than 8.1.x, when `Utils\http_request()` fails, then `PHP Deprecated` notices are written to the logs. Passing `(int) 0` is compatible with the signature of the `RuntimeException` constructor and avoids the warnings.
Since there are no functional changes in this PR, I haven't included tests.
=> Avoid PHP deprecation notices in PHP 8.1.x

features/cli-bash-completion.feature, php/WP_CLI/Completions.php
Further to #5873, I incorrectly handled options that end in `=` and have already been completed. Any candidates offered immediately after such an option are treated by shells as possible values to concatenate, not possible names of the current option. Consequently, this
```sh
wp config create --dbname=
```
will tab-complete to
```sh
wp config create --dbname=--dbname=
```
I have added an extra condition to prevent that case.
=> Correct completion case when ends in =

tests/test-commandfactory.php, tests/test-configurator.php, tests/test-file-cache.php, tests/test-inflector.php, tests/test-synopsis.php, tests/test-utils.php
Issue related: #5909
I updated inline documentation according to [PHP Documentation Standards -  Inline Comments ](https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/#5-inline-comments)
=> Docs: Fixes for inline comments

features/aliases.feature, php/class-wp-cli.php, php/commands/src/CLI_Alias_Command.php
This pull request aims to address the issue reported in #5391 where adding an alias without the `@` symbol would result in the alias being added but missing from the output of the `wp cli alias list` command because it does not have the `@` symbol. With the updates in this pull request, if the user forgets to provide the `@` symbol as the prefix, it will be added behind the scenes to ensure the alias can be listed correctly.
=> Ensure the alias has the leading `@` symbol when added

php/WP_CLI/Runner.php
Sometimes, the WP CLI process doesn't have access to PATH and it gives an error. This PR aims to resolve those binary using `env` which is already done for binaries like `mysql`.
Related: https://github.com/wp-cli/wp-cli/issues/5935
=> Update docker runner to resolve docker path using `/usr/bin/env`

features/config.feature, php/WP_CLI/Configurator.php
This Pull Request aims to fix issue #4958, where the inherited config using the `inherit` option is not properly merged when a command is run in nested directories. Currently, when running WP-CLI under sub-directories, like `./site/web/app/themes/mytheme/`, it only reads configuration from the `wp-cli.yml` file and fails to merge the configs from `../wp-cli.local.yml`.
For example, with the given directory structure:
```
.
├── wp-cli.local.yml
├── site
│   ├── wp-cli.yml
│   └── web
│       ├── app
│       │   ├── themes
│       │   ├── upgrade
│       │   └── uploads
│       └── wp
│           ├── wp-admin
│           ├── wp-content
│           └── wp-includes
└── trellis
```
And the configurations:
```
@dev:
ssh: vagrant@example.test/srv/www/example.com/current
path: web/wp
```
``` …
```
=> Fix `inherit` path in nested directory

php/WP_CLI/Iterators/CSV.php, tests/WP_CLI/Iterators/CSVTest.php
Fixes https://github.com/wp-cli/wp-cli/issues/5412
=> Fix breaking multi-line CSV values on reading

features/help.feature, php/WP_CLI/Dispatcher/CompositeCommand.php, php/commands/src/CLI_Command.php, php/commands/src/Help_Command.php, php/utils.php, templates/man.mustache
This would be a first step towards addressing #5838 and including details on when a specific command is run in the handbook documentation.
I've added the output to the help command as well so there will be parity between that and the handbook. 
If the parent command defines a `@when` tag, that is passed down to all subcommands. If a subcommand has its own `@when` tag, it will take the place of the parent tag. If there is no `@when` tag defined for a parent or subcommand, it won't show any hook information with the existing assumption that everything runs on the default hook unless otherwise specified.
So now a command like `wp help db reset` would output:
```
NAME
wp db reset
DESCRIPTION
Removes all tables from the database.
This command runs when the 'after_wp_config_load' hook is …
```
=> Include any non default hook information in CompositeCommand

utils/wp.fish
This pull request adds a Fish shell completion script for wp-cli.
- Adds a Fish completion script for the `wp` command.
- Handles file completions when completions include `<file> `.
- Handles unnecessary whitespace in completions.
- Tested in Fish shell version `3.7.1`.
- Verified completions for various `wp` commands and options.
- Works with aliases when in a directory that contains them.
Included a link to the Fish shell documentation for [where to put completions](https://fishshell.com/docs/current/completions.html#where-to-put-completions).
=> Add fish shell completion

php/WP_CLI/Runner.php
PHP 8.4 deprecates implicitly nullable parameters, i.e. typed parameters with a `null` default value, which are not explicitly declared as nullable.
As the minimums supported PHP version of this code base is PHP 5.6, adding the nullability operator to the type declaration is not an option at this time.
In this case, however, the parameter is found in the declaration of a `private` method, so removing the type declaration in favour of in-function type checking solves the deprecation without breaking BC (as `private`).
Includes updating the documentation to match (where relevant, i.e. only existing documentation has been touched).
Ref: https://wiki.php.net/rfc/deprecate-implicitly-nullable-types
=> PHP 8.4 | Fix implicitly nullable parameters

tests/UtilsTest.php
The `ReflectionProperty::setValue()` method supports three method signatures, two of which are deprecated as of PHP 8.3.
This adjusts the call to `ReflectionProperty::setValue()` in various methods in the `UtilsTest` class to pass `null` as the "object" for setting the value of a static property to make the method calls cross-version compatible.
**_Note: these deprecations were visible in the test summary, but the tests - as they currently are - are not set up correctly to fail builds on deprecation notices, which is probably why this went unnoticed._**
Ref: https://wiki.php.net/rfc/deprecate_functions_with_overloaded_signatures#reflectionpropertysetvalue
=> PHP 8.3 | ReportWidthTest: fix deprecation notices for ReflectionProperty::setValue()

php/WP_CLI/Iterators/CSV.php
As of PHP 8.1, PHP started throwing deprecation warnings along the lines of:
```
Deprecated:  Return type of [CLASS]::[METHOD]() should either be compatible with [PHP NATIVE INTERFACE]::[METHOD](): [TYPE], or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
```
These type of deprecation notices relate to the [Return types for internal methods RFC](https://wiki.php.net/rfc/internal_method_return_types) in PHP 8.1.
Basically, as of PHP 8.1, these methods in classes which implement PHP native interfaces are expected to have a return type declared. The return type can be the same as used in PHP itself or a more specific type. This complies with the Liskov principle of covariance, which allows the return type of a child overloaded method to be more …
=> PHP 8.1 | WP_CLI\Iterators\CSV: fix "missing return type" deprecation warnings

php/utils-wp.php
The `E_STRICT` constant is deprecated as of PHP 8.4 and will be removed in PHP 9.0 (commit went in today).
The error level hasn't been in use since PHP 8.0 anyway and was only barely still used in PHP 7.x, so removing the exclusion from the `error_reporting()` setting in the example code shouldn't really make any difference in practice.
Ref:
* https://wiki.php.net/rfc/deprecations_php_8_4#remove_e_strict_error_level_and_deprecate_e_strict_constant
=> PHP 8.4 | wp_debug_mode(): remove use of `E_STRICT`

features/requests.feature
Switch themes because `twentytwentyfive` (which is part of WP 6.7 / trunk now) requires a version newer than 6.2 and it would otherwise cause a fatal error further down.
=> Fix tests against WordPress trunk

features/requests.feature
This test runs WP-CLI 2.7.0 via Composer, which causes deprecation warnings on PHP 8.2
=> Skip Requests v1 test on PHP 8.2+

php/WP_CLI/Extractor.php, tests/CommandFactoryTest.php, tests/FileCacheTest.php, tests/HelpTest.php, tests/UtilsTest.php, tests/WP_CLI/WpOrgApiTest.php
Tests on PHP 8.1 and higher (which are running PHPUnit 10+) are failing with the below message:
```
An error occurred inside PHPUnit.
Message:  Interface "WpOrg\Requests\Transport" not found
Location: /home/runner/work/wp-cli/wp-cli/tests/mock-requests-transport.php:6
```
This may be due to the test classes being loaded (to count the number of tests) before the test bootstrap is being run (which includes the autoloaders).
If that "guess" is correct, this patch should fix this.
While these tests are not showing errors at this time, it is still best practice to include files in the test `set_up_before_class()` method, not when the file is being read.
This applies this change to all other test files which were using the anti-pattern.
=> UtilsTest: fix the test failure

php/wp-settings-cli.php
Fix: https://github.com/wp-cli/wp-cli/issues/6030
Replaced the deprecated link `https://codex.wordpress.org/AJAX_in_Plugins` 
with the updated link `https://developer.wordpress.org/plugins/javascript/ajax/`.
=> Fix: Update outdated AJAX documentation link

php/utils.php
Facilitates HTTP request mocking in tests
See https://github.com/wp-cli/wp-cli-tests/issues/210
=> Add hook to `http_request()` util

features/config.feature, php/WP_CLI/Runner.php
Slightly improves the existing regex to support `require wp-settings.php` calls stretched over multiple lines.
Fixes #6038
PHP 5.6 failures are known, see #6018.
The other one is fixed by #6041
=> Improve regex for detecting `wp-settings.php`

features/config.feature, php/WP_CLI/Runner.php
Addresses a logical mistake in #6039 that I didn't realize until tests in config-command [started failing](https://github.com/wp-cli/config-command/actions/runs/13064833741/job/36463433686#step:11:72).
Basically, the `wp-settings.php` call needs to be omitted, but the code after that still needs to be eval'd.
=> Ensure code after `wp-settings.php` call is loaded

php/wp-cli.php
To make requests identifiable in firewall logs and do not trigger false alarms, this allows setting a user agent in ENV VARS or defaults to a generic user agent.
=> Add configurable user agent to WP-CLI to detect in firewall logs

.gitignore, phpunit.xml.dist
Fixes a currently failing code coverage job because the PHPUnit config is outdated.
See https://github.com/wp-cli/wp-cli/issues/6035
The PHP 5.6 failures are known, see #6018
=> Allow collecting PHPUnit coverage

features/flags.feature, php/WP_CLI/Runner.php
#5974 reroll
1. `docker exec` and `docker-compose exec` provide an option to cleanly set the working directory before running a command
=> Use it instead and use `cd <...> ;` command-prefixing in vagrant/ssh cases
2. Using `docker` scheme, `wp post update 1 - <<<foo` didn't worked (issue #4972)
* Because STDOUT being a tty, `-t` is passed with no ability to inhibit this
* Because docker `-i` flag is necessary
=> As such:
* docker `-i` (`--interactive`) is introduced (with sensible autodetection)
* `WP_CLI_DOCKER_NO_TTY` and `WP_CLI_DOCKER_NO_INTERACTIVE` environment variables are introduced to optionally inhibit these respective flags
Special case to handle `behat` runs (see #5974)
=>  docker scheme: working-directory and stdin passing (reroll of #5974)

composer.json
See #6018
This makes sure the PHP 5.6 tests pass again.
We can re-add it after the v2.12.0 release when we bump the minimum PHP version requirement.
=> Temporarily remove `roave/security-advisories`

features/runner.feature, php/WP_CLI/Runner.php
Fixes [#5624](https://github.com/wp-cli/wp-cli/issues/5624)
**Summary**
This PR improves user experience by suggesting appropriate WP-CLI commands when a user attempts to run wp <taxonomy> or wp <post_type>, which do not exist. Instead of failing with an error, WP-CLI will now provide a helpful "Did you mean" message.
**Changes**
-  Added logic to detect when a user enters wp <taxonomy> <command> or wp <post_type> <command>.
-  Implemented a suggestion system that recommends:
`wp term <command> <taxonomy> for taxonomies.`
`wp post <command> --post_type=<post_type> for post types.`
-  If the exact command format cannot be inferred, a general suggestion for wp term or wp post is provided.
**Testing Instructions**
1. Run `wp category list` (or any taxonomy name instead of category).
- …
=> Improve command suggestions for taxonomies and post types

composer.json, features/config.feature, php/WP_CLI/Runner.php
While looking into #6053 I saw two bugs:
The first is that we called `touch` to create a config file if it wasn't present. That doesn't work because touch can't create the parent folders when they don't exist.
The only user of this code is the `alias add` command which I then saw had another bug. The function for getting the path of a project config file returned `null` when it couldn't find one instead of `false` as the docblock says it should. This caused a warning later on:
```
PHP  15. Mustangostang\Spyc::YAMLLoad($input = NULL) /Users/isla/source/wp-cli-dev/wp-cli/php/commands/src/CLI_Alias_Command.php:358
PHP  16. Mustangostang\Spyc->_load($input = NULL) /Users/isla/source/wp-cli-dev/spyc/src/Spyc.php:118
PHP  17. Mustangostang\Spyc->loadFromSource($input = NULL) …
```
=> Properly create missing wp cli config file when needed.

features/runcommand.feature, php/WP_CLI/Configurator.php
As a companion to `WP_CLI_EARLY_REQUIRE` but doesn't include the files until after wp has been through the boostrap process. This is the same as using `--require` from the command line, or require in a yaml config file. The purpose for another way of requiring a file is for use in codecov testing, where it otherwise is not practical to conditionally include a php file at normal runtime using the existing methods in a testing environment.
See https://github.com/wp-cli/wp-cli-tests/issues/241 for more conversation. This is what https://github.com/wp-cli/wp-cli/pull/6065 was meant to address, but it didn't end up working out for this specific case since we can't include our codcov generate files that early on before wp has been through bootstrap
=> Add WP_CLI_REQUIRE env var for including extra php files

composer.json, features/utils.feature, php/utils.php
See:
* https://github.com/wp-cli/db-command/pull/280#issuecomment-2751656704
* https://github.com/wp-cli/db-command/pull/275
* https://github.com/wp-cli/db-command/issues/271
* https://github.com/wp-cli/.github/issues/123
MariaDB currently adds symlinks for `mysql` to use `mariadb` under the hood, but that is being deprecated and people get warnings like `Deprecated program name. It will be removed in a future release, use 'mariadb' instead`
With this change, the idea is to offer better utils for commands like db-command to pick the right binary.
I suppose that could imply that we officially support MariaDB, but I guess since WordPress core itself [recommends](https://wordpress.org/about/requirements/) it, we should at least test it.
=> Detect MariaDB vs MySQL

php/commands/src/CLI_Command.php
When using a currently nightly build and running `wp cli update` without any arguments, it couldn't find any version, which caused some PHP warnings.
```
$ wp cli update
PHP Warning:  Undefined array key "available" in phar:///Users/pascalb/.local/bin/wp/vendor/wp-cli/wp-cli/php/commands/src/CLI_Command.php on line 330
Warning: Undefined array key "available" in phar:///Users/pascalb/.local/bin/wp/vendor/wp-cli/wp-cli/php/commands/src/CLI_Command.php on line 330
PHP Warning:  Trying to access array offset on null in phar:///Users/pascalb/.local/bin/wp/vendor/wp-cli/wp-cli/php/commands/src/CLI_Command.php on line 334
Warning: Trying to access array offset on null in phar:///Users/pascalb/.local/bin/wp/vendor/wp-cli/wp-cli/php/commands/src/CLI_Command.php on line 334
You have version …
```
=> Fix update step for nightlies

php/utils.php
For some reason `wp cli update` didn't work for me because the newly downloaded Phar (which we execute in a sub-process to see if it works) errored with "Could not find mysql binary"
There's no reason for that command to error, and it never did do that in the past. It's supposed to return an empty string, as indicated by the docblock.
=> Do not error if mysql binary not found

php/WP_CLI/Runner.php
If we don't intend to connect through docker, don't even exec() it in the first place: Less syscalls and more apparmor-friendly behavior
=> don't forcefully exec() `docker version`

php/WP_CLI/Runner.php
Could be set to use `/custom/path/wp` on the remote end but also `sudo -u user /some/wp` to allow running wp under a distinct user.
See also #5974
=> allow remote binary customization

php/utils.php, tests/UtilsTest.php
As described in https://github.com/wp-cli/cache-command/issues/92#issuecomment-2083462498, we need to let the existing `$wpdb->esc_like()` take precedence in order to allow compatibility layers like the SQLite integration plugin to still have a way to override things.
=> Make sure existing `esc_like()` takes precedence

composer.json, schemas/wp-cli-config.json, tests/SchemaValidationTest.php
A JSON schema and example wp-cli.yml file were added in #6095. This adds JSON schema validation for the YAML file (and any others that are added to that directory) using `justinrainbow/json-schema`. Notably, this package is already a transient dependency as it's used by `composer/composer`, so although this is now an explicit dependency it's not an additional dependency.
Two fixes are made to the schema:
1. Support for the `$schema` property
2. A more specific regex for the subcommand properties so it's not matched by single word keys
=> Add JSON schema validation

composer.json
Added in #6096 by accident, forgot to change it before merge.
=> Fix incorrect wp-cli-tests dependency

tests/DocParserTest.php, tests/HelpTest.php
This PR fixes following PHPCS error code:
`Detected heredoc without interpolation or expressions. Use nowdoc syntax instead`
=> Fix heredoc issue

features/skip-plugins.feature
Hello Dolly was moved from a single file to a directory in WordPress 6.9. Trying to make the tests more robust by replacing it with our own sample plugin.
No idea why some other tests are failing though, see for example https://github.com/wp-cli/wp-cli/actions/runs/17459015237/job/49579164998#step:11:138
Those are best handled in a separate PR.
=> Fix tests for Hello Dolly
